VKCOM/kphp

common/tlo-parsing/tl-dependency-graph.cpp
common/tlo-parsing/tl-dependency-graph.h

All dependencies in TL dependency graph are treated as not weak. Weak self-cyclic types are collected separately.

TL dependency graph improvements

---

server/php-runner.h

As far as I can tell those lines are useless.

remove unnecessary forward declaration

---

vkext/vkext.cmake

if vkext.ini has been modified manually apt will ask to overwrite it or leave it as it is

ask to overwrite vkext.ini if it has been modified by user

---

vkext/vkext-schema-memcache.cpp
vkext/vkext-schema-memcache.h
vkext/vkext.cpp

The same as [this](https://github.com/VKCOM/kphp/pull/18) but in vkext

Always treat TL long as int64_t in vkext

---

runtime/critical_section.h
runtime/interface.cpp
runtime/openssl.cpp
runtime/openssl.h

Call openssl methods under signal critical sections.

openssl critical sections

---

tests/kphp_ci_pipeline_runner.py
tests/python/lib/kphp_builder.py

everything works fine with custom environment variables

overwrite predefined environment variables

---

compiler/data/lambda-class-data.cpp
compiler/data/lambda-generator.cpp
compiler/pipes/preprocess-function.cpp
tests/phpt/lambdas/042_external_lambda_interface.php

prevent inferring assumptions of typed lamba's uses with reading assumptions at the same time which causes data-race and SIGSEGV from time to time.

prevent assumptions inferring for uses of lambda simultaneously

---

compiler/pipes/inline-defines-usages.cpp
tests/phpt/access/constants/01_basic.php

fix a CE when a private const is used to init other fields

---

docs/_config.yml
docs/kphp-internals/developing-and-extending-kphp/compiling-kphp-from-sources.md
docs/kphp-language/kphp-vs-php/phpdoc-annotations.md

Hi!
1) Add MacOS build instructions.
2) Add performance phpdoc annotations.

Update docs 12.2020

---

server/json-logger.cpp
server/json-logger.h
tests/python/tests/json_logs/test_exceptions.py
tests/python/tests/json_logs/test_warnings.py

This patch allows to remove special chars from json logs.

Filter special chars from json logs.

---

runtime/url.cpp

This patch syncs parse_url() implementation with latest PHP version.

Verify user info in parse_url().

---

runtime/url.cpp
tests/phpt/dl/1015_parse_url.php
tests/zend-test-list

The changes of parse_url was reverted in php, revert them from KPHP.
https://github.com/php/php-src/commit/6d96fdc68d990993a5177152edb9be9bebf0bf6c

Revert the parse_url fixes 

---

compiler/pipes/preprocess-eq3.cpp
tests/phpt/optimizations/009_replace_comparison_on_isset.php

x['key'] !== null to x.isset('key')

replacing comparison of array value by key with null on isset function for instance field

---

runtime/vkext.cpp
vkext/vkext.cpp

potential fix of broken new ios emoji encoding

---

common/tl/constants/kphp.h
server/php-engine.cpp
server/php-lease.cpp
server/php-lease.h

maintain kphp.startLeaseV2 with actor_id

---

runtime/job-workers/client-functions.cpp

Fix wait_net timeout for kphp_job_worker_wait().

---

tests/phpt/dl/1012_array_key_exists.php

Found during an unrelated chore.

fix a mispelled variable in test

---

net/net-http-server.cpp
net/net-http-server.h
server/php-engine.cpp
tests/python/tests/http_server/php/index.php
tests/python/tests/http_server/test_request_limits.py

Increase http server limits.

---

cmake/popular-common.cmake
common/rpc-headers.cpp
common/rpc-headers.h
common/tl/constants/common.h
runtime/rpc.cpp
vkext/.gitignore
vkext/rpc-tests/main.php
vkext/rpc-tests/memcache-rpc-tl-test.patch
vkext/vkext-rpc-include.h
vkext/vkext-rpc.cpp
vkext/vkext.cmake

maintain rpcInvokeReqExtra.no_result

---

common/dl-utils-lite.cpp
common/dl-utils-lite.h
common/macos-ports.h
compiler/stats.cpp
runtime/instance-cache.cpp
server/php-engine.cpp
server/php-master.cpp
server/php-runner.cpp
server/php-worker-stats.cpp
server/php-worker-stats.h

This patch adds a bunch of different memory stats.
WIP while #160 is not merged.

More memory stat.

---

runtime/instance-copy-processor.h
runtime/job-workers/job-interface.cpp
server/confdata-binlog-replay.cpp
server/job-workers/job-worker-client.cpp
server/job-workers/job-worker-server.cpp
server/job-workers/job-workers-context.cpp
server/job-workers/pipe-io.cpp
server/json-logger.cpp
server/json-logger.h
server/php-runner.cpp
server/server-log.cpp
server/server-log.h
server/server.cmake

Hi!
This patch adds an ability to write json logs from server parts.
It also uses the new logging logic for errors from job workers.

Add an ability to write json logs from the server code.

---

docs/_config.yml
docs/kphp-internals/developing-and-extending-kphp/compiling-kphp-from-sources.md

Markdown rendering is tested locally.

docs: add missing bits about timelib dependency

---

compiler/code-gen/vertex-compiler.cpp
runtime/null_coalesce.h

Hi!
This patch fixes the code generation of null coalesce:
before:
```
$x = null_coalesce($a[$b], $key, $fallback_lambda);
```
after
```
$x = NullCoalesce($a[$b], $key).finalize($fallback_lambda);
```
so now, `$a[$b]` is not held on `$fallback_labmda` call.
Also I've used a perfect forwarding for basic cases.

Implement null coalesce via class.

---

compiler/code-gen/code-gen-task.cpp

Replace long dash with short one for the compiler result table.

---

compiler/code-gen/files/function-header.cpp
compiler/code-gen/files/function-source.cpp
compiler/code-gen/files/global_vars_memory_stats.cpp
compiler/code-gen/files/init-scripts.cpp
compiler/code-gen/files/lib-header.cpp
compiler/code-gen/files/tl2cpp/tl-module.cpp
compiler/code-gen/files/tl2cpp/tl2cpp.cpp
compiler/code-gen/files/type-tagger.cpp
compiler/code-gen/files/vars-cpp.cpp
compiler/code-gen/files/vars-reset.cpp
compiler/compiler-settings.cpp
compiler/compiler-settings.h
compiler/kphp2cpp.cpp
compiler/make/cpp-to-obj-target.h
compiler/make/make.cpp

This patch enables a precompiled headers supporting for the clang compilation.

Support pch for clang build.

---

functions.txt
runtime/string_functions.cpp
runtime/string_functions.h
tests/phpt/string_functions/003_str_ireplace.php

- All functions for implementing `str_replace` now accept the `with_case` 
flag as the last parameter, which determines whether this function will 
be case insensitive.
- To search for a substring, a separate function `find_substr` has been 
created, which, when case sensitive, does a quick search, as is done
now with `memmem`, and when case insensitive, does `strcasestr`.

added str_ireplace function

---

server/php-master.cpp
server/server-stats.cpp
tests/python/tests/stats/php/index.php
tests/python/tests/stats/test_master_stats.py

This patch adds missing stats which is required for out monitoring.

Add missing stats

---

server/server-stats.cpp

Sometimes percentile stats show zeros. This patch is trying to fix it.

Less effect of zero stats.

---

runtime/job-workers/client-functions.cpp
server/job-workers/job-worker-server.cpp
server/job-workers/job-worker-server.h
server/server-stats.cpp
server/server-stats.h

2 new metrics were added:
1. Job response memory usage
2. Job common shared memory request memory usage

Add job memory metrics

---

functions.txt
runtime/job-workers/client-functions.cpp
runtime/job-workers/client-functions.h
server/job-workers/job-message.h
server/job-workers/job-worker-server.cpp
server/job-workers/job-worker-server.h
server/php-worker.cpp
tests/python/tests/job_workers/php/http_worker.php
tests/python/tests/job_workers/php/job_worker.php
tests/python/tests/job_workers/test_job_errors.py
tests/python/tests/job_workers/test_job_no_reply.py

Job workers: send no reply

---

runtime/job-workers/client-functions.cpp
server/job-workers/job-message.h
server/job-workers/shared-memory-manager.cpp
server/job-workers/shared-memory-manager.h
server/php-engine.cpp
tests/python/tests/job_workers/test_cpu_job.py
tests/python/tests/job_workers/test_job_shared_messages.py

Support --job-workers-shared-messages option.

---

tests/benchmarks/BenchmarkBasic.php
tests/benchmarks/BenchmarkMicro.php
tests/benchmarks/README.md

This patch adds basic benchmarks.

Add basic benchmarks.

---

functions.txt
runtime/interface.cpp
runtime/interface.h
server/php-runner.cpp

Implement function for disabling json log on timeout

---

docs/kphp-language/php-extensions/ffi.md

```
docs: extend FFI section
Explain auto conversions.
```

docs: extend FFI section

---

runtime/exception.h

Implement visitors for builtin Exception class

---

server/php-engine.cpp
server/php-queries-types.cpp
server/php-queries-types.h
server/php-queries.cpp
server/php-queries.h
server/php-runner.cpp
server/php-runner.h
server/php-worker.cpp
server/php-worker.h
server/server.cmake

Use inheritance and virtual methods instead of C-style manual emulation in php queries

---

compiler/pipes/remove-empty-function-calls.cpp

Such variables generated for tracking whether global scope of file loaded or not. For empty, i.e. doing nothing in global scope, files such variables is unused, so this PR remove it.

get rid of $called-globals for empty source files

---

builtin-functions/_functions.txt
runtime/array_functions.h
tests/phpt/array/017_array_unique.php
tests/zend-test-list

array_unique() now support 'flags' argument, as in [doc](https://www.php.net/manual/en/function.array-unique.php).

add support of 'flags' argument array_unique() function

---

common/server/stats.cpp
common/server/stats.h
common/server/statsd-client.cpp
common/server/tl-stats-t.h
common/stats/provider.cpp
common/stats/provider.h
runtime/memory_resource/memory_resource.cpp
server/php-master.cpp
server/statshouse/add-metrics-batch.cpp
server/statshouse/add-metrics-batch.h
server/statshouse/statshouse-client.cpp
server/statshouse/statshouse-client.h

added almost all statsd metrics

improved statshouse client

---

compiler/pipes/final-check.cpp
compiler/pipes/final-check.h
tests/phpt/array/018_array_indexing_failire.php
tests/phpt/array/019_array_indexing_ok.php
tests/phpt/array/020_array_literal_failure.php
tests/phpt/array/021_array_literal_ok.php
tests/phpt/array/022_array_set_value_failure.php
tests/phpt/array/023_array_set_value_ok.php
tests/phpt/dl/1019_negative_string_offset.php
tests/phpt/dl/467_rawid2long.php
tests/phpt/null_coalescing/3_string.php
tests/phpt/string_functions/005_string_indexing_failure.php
tests/phpt/string_functions/006_string_indexing_ok.php
tests/phpt/tup/110_tuple_indexing_failure.php

Forbid bad types in indexing arrays, strings and tuples

forbid bad types in indexing

---

common/tlo-parsing/tl-scheme-final-check.cpp
net/net-msg-test.cpp

Fix 2 minor compilation issues with clang++13

support compilation under clang++-13

---

builtin-functions/_functions.txt
runtime/string.inl
runtime/string_decl.inl
runtime/string_functions.cpp
runtime/string_functions.h
tests/cpp/runtime/string-test.cpp

RFC: https://wiki.php.net/rfc/add_str_starts_with_and_ends_with_functions
Added a function from a low priority block

Add str_starts_with() and str_ends_with() functions

---

common/server/statsd-client.cpp
common/server/tl-stats-t.h
common/stats/provider.h
runtime/memory_resource/memory_resource.cpp
server/confdata-stats.cpp
server/php-master.cpp
server/server-stats.cpp
server/statshouse/statshouse-client.cpp
server/statshouse/worker-stats-buffer.cpp

Prefixes of some metrics are now tags for those metrics for statshouse

confdata stats refactoring

---

builtin-functions/_functions.txt
runtime/array.inl
runtime/array_decl.inl
runtime/array_functions.h
runtime/mixed.inl
tests/phpt/array/024_array_unset.php
tests/phpt/array/025_array_pop.php

array_unset($arr, $key) function just return value corresponding to $key, and remove it from $arr.

implement array_unset() api function

---

tests/python/lib/kphp_run_once.py

fix vkext phpt for macOS

---

.github/workflows/Build.yml
.github/workflows/debian.yml
.github/workflows/ubuntu.yml

After this PR, it will be possible to view and download failed python tests artifacts 
Actions -> select needed workflow run -> scroll down:

GitHub actions: upload artifacts

---

compiler/kphp2cpp.cpp
docs/kphp-language/kphp-vs-php/compiler-cmd-options.md

for better optimization by default

-Os flag changed to -O2 by default

---

builtin-functions/_functions.txt
runtime/mixed.inl
runtime/regexp.cpp
runtime/string.inl
runtime/string_decl.inl
runtime/string_functions.cpp
runtime/string_functions.h
tests/phpt/string_functions/007_strspn.php

Also refactor offset handling in some string functions.

add strspn and strcspn functions

---

tests/python/lib/engine.py
tests/python/lib/kphp_server.py
tests/python/lib/tl_client.py

- fix RPC answers json decoder when tl-client responds with RPC error
- add option for debug dumps of incoming queries to engine

[tests] improve python tests lib

---

runtime/vkext.cpp
tests/phpt/string_functions/004_vk_win_to_utf.php
vkext/vkext.cpp
vkext/vkext.stub.php
vkext/vkext_arginfo.h
vkext/vkext_legacy_arginfo.h

* fixed vkext vk_win_to_utf8 escape parameter

unification of vk_win_to_utf8 function from vkext and runtime

---

.github/workflows/Build.yml
.github/workflows/macos.yml
cmake/init-compilation-flags.cmake
compiler/compiler-settings.cpp
docs/kphp-internals/developing-and-extending-kphp/compiling-kphp-from-sources.md

fix macos ci and build:
1) added shivammathur/php tap for php 7.4
2) removed unused packages
3) upgraded openssl version to 3
also refactoring kphp's dependency on openssl for mac os

macos github ci fix

---

.github/workflows/Build.yml
common/server/relogin.cpp

* removed default user kitten
* user will not be changed if he is already root

relogin refactoring

---

runtime/tl/rpc_tl_query.cpp

Fix incorrect assert at RPC logging

---

builtin-functions/_functions.txt
runtime/exec.cpp
runtime/exec.h
runtime/misc.cpp
runtime/misc.h
runtime/runtime.cmake
tests/phpt/dl/1040_exec.php
tests/phpt/dl/1041_exec_warnings.php

Add `exec()`, `system()` and `passthru()` functions.

add exec() family of functions

---

builtin-functions/_functions.txt
runtime/exec.cpp
runtime/exec.h
tests/phpt/dl/1042_escapeshell.php

add [escapeshellarg()](https://www.php.net/manual/en/function.escapeshellarg.php) and [escapeshellcmd()](https://www.php.net/manual/en/function.escapeshellcmd.php) functions

add escapeshellarg() and escapeshellcmd() functions

---

builtin-functions/_functions.txt
runtime/env.cpp
runtime/env.h
runtime/runtime.cmake
tests/phpt/dl/1041_getenv.php

add [getenv()](https://www.php.net/manual/en/function.getenv.php) function

add getenv() function

---

runtime/interface.cpp
runtime/interface.h
server/database-drivers/adaptor.cpp
server/php-engine.cpp
server/php-queries.cpp
server/slot-ids-factory.cpp
server/slot-ids-factory.h

Use non-deterministic random separate in each worker for generating IDs and some refactoring

Improve slot ids factories

---

compiler/pipes/check-func-calls-and-vararg.cpp
tests/phpt/cl/197_compile_time_location.php

Fixes https://github.com/VKCOM/kphp/issues/508

Fix CompileTimeLocation problems

---

builtin-functions/_functions.txt
runtime/interface.cpp
runtime/interface.h
runtime/php_assert.cpp
server/json-logger.cpp
server/json-logger.h

add function to enable demangled stacktrace in json logs

---

server/php-runner.cpp
server/php-runner.h
server/php-worker.cpp

Remove extra logs that were added here https://github.com/VKCOM/kphp/pull/795

remove extra logs of connection status

---

server/server-stats.cpp
server/statshouse/statshouse-client.cpp
server/statshouse/statshouse-client.h
server/statshouse/worker-stats-buffer.cpp
tests/python/tests/http_server/test_server_config.py

replaced host with cluster name for statshouse

improving statshouse metrics

---

runtime/resumable.cpp

Now we dump to log fork and 'started_resumable' which cause this warning.

add more logs for 'resumable is already waited' warning

---

runtime/rpc.cpp
runtime/rpc.h
server/confdata-binlog-replay.cpp

- enrich assert from confdata binlog update
- log all RPC errors under verbosity

Small logs enrichment

---

common/tl-files/common.tl
server/php-master.cpp
server/server-stats.cpp
server/server-stats.h

Added some new stats:
- `ready_for_accept_workers_[avg|max]` stats
- `qps_[avg|max]` stats

Added new stats to RPC engine.stat

---

common/tl/compiler/tl-tl.h

relates to https://github.com/VKCOM/kphp/pull/913

[tl-compiler] fix TLS_NAT_CONST magic

---

.github/workflows/Build.yml
.github/workflows/macos.yml
builtin-functions/kphp_toggles.txt
compiler/code-gen/declarations.cpp
runtime/instance-cache.cpp
runtime/instance-cache.h
runtime/interface.h
server/statshouse/statshouse-manager.cpp
server/statshouse/statshouse-manager.h

added metric to track the amount of memory that is used for the store instance to instance cache

added additional instance cache metric

---

server/php-engine.cpp

Swap start/end time in measurement (now there is an overflow)

Fix start/end time in measurement

---

compiler/compiler-core.cpp
compiler/compiler-core.h

Make `globals` hashtable bigger

Change compiler core globals hashtable 

---

.github/workflows/Build.yml
.github/workflows/macos.yml

python3.12 preinstalled in Github CI?

Fix Mac OS Build in Github CI

---

compiler/code-gen/files/init-scripts.cpp
compiler/compiler-settings.cpp
compiler/make/make.cpp
compiler/make/objs-to-k2-component-target.h

Compiling k2-component into dynamic library

Compiling k2-component into dynamic library

---

runtime-light/coroutine/task.h
runtime-light/stdlib/misc.cpp
runtime-light/streams/streams.cpp
runtime-light/utils/json-functions.h

Suppress and fix some warnings. For now, runtime is compilable without warnings.

Rid of warnings

---

compiler/code-gen/code-generator.h
compiler/code-gen/declarations.cpp
compiler/code-gen/files/init-scripts.cpp
compiler/code-gen/files/init-scripts.h
compiler/code-gen/vertex-compiler.cpp
compiler/compiler-core.cpp
compiler/compiler-core.h
compiler/compiler-settings.cpp
compiler/compiler-settings.h
compiler/data/function-data.h
compiler/kphp2cpp.cpp
compiler/make/make.cpp
compiler/make/objs-to-k2-component-target.h
compiler/pipes/calc-bad-vars.cpp
compiler/pipes/calc-func-dep.cpp
compiler/pipes/code-gen.cpp
compiler/pipes/parse-and-apply-phpdoc.cpp

This pr is part of light integration https://github.com/VKCOM/kphp/pull/1009

support runtime-light in compiler

---

compiler/code-gen/files/global-vars-reset.cpp

Without this check it fails in runtime on each worker start at `init_php_scripts_in_each_worker()`

Check that global var type and its init value type are the same

---

.github/workflows/Dockerfile.buster

fix for https://github.com/oerdnj/deb.sury.org/issues/2155
solve sury issue my fetching mirror with its gpg key
python3-wheel needed to fix installation mysql by wheel

sury issue

---

.github/workflows/Build.yml

Installing jsonschema right way

Fix mac os CI build

---

runtime-light/stdlib/rpc/rpc-api.cpp
runtime-light/stdlib/rpc/rpc-context.h
runtime-light/tl/tl-core.cpp
runtime-light/tl/tl-core.h
runtime-light/tl/tl.cmake

We may want use TL not only for RPC things, but also for communication via k2 streams. This PR is refactoring to simplify this use case

Split TL and RPC stuff 

---

.github/workflows/Build.yml
.github/workflows/debian.yml
.github/workflows/ubuntu.yml

Fixing caching images by using `--cache-from` docker option and tagging them

Fix CI docker caching images

---

tests/phpt/json/38_optimized_init_val.php

Add missed line for tests to work.

Fix #1028 build

---

.github/workflows/Build.yml
builtin-functions/kphp-light/functions.txt
runtime-core/runtime-core.cmake
runtime-light/runtime-light.cmake
runtime-light/stdlib/variable-handling.cpp
tests/kphp_tester.py
tests/phpt/mixed/non_primitive/008_forks.php
tests/phpt/mixed/non_primitive/014_class_as_int.php
tests/phpt/mixed/non_primitive/016_var_dump.php

Fix UB with reaching `unreachable` builtin when do var_dump() when mixed stores object and some fixes

 Fix objects in mixed in light runtime

---

tests/kphp_tester.py

Fix error with `k2-bin` path

---

.github/workflows/Build.yml
runtime-core/core-types/decl/array_decl.inl
runtime-core/core-types/decl/array_iterator.h
runtime-core/core-types/definition/array.inl

Get rid of zero length array extension and fixes build for jammy + gcc-11

Get rid of zero length array extension

---

runtime-light/stdlib/crypto/crypto-functions.cpp
runtime-light/tl/tl-functions.cpp
runtime-light/tl/tl-functions.h
runtime-light/tl/tl-types.cpp
runtime-light/tl/tl-types.h

Make TL-parsing logic as for JobWorkers

Refactor crypto for light runtime

---

runtime-light/coroutine/awaitable.h

This PR adds State to some awaitables to ensure they are never in inconsistent state.

K2: add State to start_fork_t, wait_fork_t, and wait_with_timeout_t

---

server/php-queries.h
server/php-runner.cpp
server/statshouse/statshouse-manager.cpp
server/statshouse/statshouse-manager.h

This PR adds following StatsHouse metrics:
- kphp_slow_rpc_response
- kphp_slow_job_worker_response

Add new StatsHouse metrics

---

builtin-functions/kphp-light/server.txt
builtin-functions/kphp-light/unsupported/unsupported-server.txt
compiler/make/objs-to-k2-component-target.h
runtime-common/core/memory-resource/resource_allocator.h
runtime-common/stdlib/server/url-functions.cpp
runtime-common/stdlib/server/url-functions.h
runtime-light/core/globals/php-script-globals.h
runtime-light/runtime-light.cmake
runtime-light/server/http/http-server-state.h
runtime-light/server/http/init-functions.cpp
runtime-light/server/http/init-functions.h
runtime-light/server/init-functions.h
runtime-light/state/init-functions.cpp
runtime-light/state/init-functions.h
runtime-light/state/instance-state.cpp
runtime-light/state/instance-state.h
runtime-light/stdlib/server/http-functions.cpp
runtime-light/stdlib/server/http-functions.h
runtime-light/stdlib/stdlib.cmake
runtime-light/stdlib/zlib/zlib-functions.cpp
runtime-light/tl/tl-types.h
runtime/url.cpp
runtime/url.h
third-party/abseil-cpp-cmake/abseil-cpp.cmake

In this PR I add:
- almost complete initialization of HTTP superglobals
- simplified implementation of header builtin

[k2] implement simple HTTP server

---

builtin-functions/kphp-full/kphp_toggles.txt
builtin-functions/kphp-light/kphp-toggles.txt
runtime-common/stdlib/string/mbstring-functions.cpp
runtime-common/stdlib/string/mbstring-functions.h
runtime-common/stdlib/string/string-context.h
runtime/interface.cpp

changed the output of the encodings for `mb_functions` to the correct function

---

builtin-functions/kphp-light/array.txt
builtin-functions/kphp-light/unsupported/arrays.txt
runtime-common/stdlib/array/array-functions.h
runtime-light/stdlib/array/array-functions.h
runtime/array_functions.h
tests/phpt/dl/1016_array_first_key.php

- `array_first_key`
- `array_key_first`
- `array_first_value`
- `array_last_key`
- `array_key_last`
- `array_last_value`

move some array functions into runtime-common

---

cmake/utils.cmake

Fix problem with absence of effect on programs behavior after runtime modification

force libkphp-full-runtime recombining when runtime is modified

---

builtin-functions/kphp-light/stdlib/error.txt
compiler/code-gen/code-generator.h
compiler/code-gen/vertex-compiler.cpp
tests/phpt/null_coalescing/8_throw_exceptions.php

This pull request fixes the incorrect handling of exceptions thrown from within null coalescing operator

[k2] fix codegen for null coalescing operator

---

.github/workflows/Dockerfile.docs
.github/workflows/docs-site.yml
docs/Dockerfile
docs/_config.yml
docs/_includes/footer.liquid
docs/kphp-internals/developing-and-extending-kphp/compiling-kphp-from-sources.md

Goals:
* Investigate issues, fix and reengage [site](https://vkcom.github.io/kphp) build.
* Update KPHP documentation to reflect changes in the project's build procedures after vendoring.

update KPHP documentation 

---

runtime-light/k2-platform/k2-api.h
runtime-light/k2-platform/k2-header.h
runtime-light/stdlib/file/resource.cpp
runtime-light/stdlib/file/resource.h

Support writing to `stderr` in K2 server mode

Implementation of stderr in K2

---

runtime-light/state/instance-state.cpp

Add missing `co_await` on `kphp::http::finalize_server` call

[k2] fix http server prologue

---

runtime-light/k2-platform/k2-header.h

Add two functions:
1. `k2_set_timezone`
2. `k2_localtime_r`

[k2] update k2-header

---

runtime/interface.cpp
runtime/openssl.cpp
runtime/runtime-builtin-stats.h
runtime/streams.cpp
server/server-stats.cpp
server/server-stats.h
server/statshouse/statshouse-manager.cpp
server/statshouse/statshouse-manager.h

General
-----------
Some expansion of https://github.com/VKCOM/kphp/pull/1347

add virtual builtins stats

---

docs/_config.yml
docs/kphp-internals/kphp-architecture/internals-vkext.md
docs/kphp-language/best-practices/embedded-profiler.md
docs/kphp-language/kphp-vs-php/list-of-additional-kphp-functions.md
docs/kphp-language/php-extensions/ffi.md

1. Fixed links that were entered on 404 pages
2. Changed the links from Russian to English documentation

updated links in documentation
