VKCOM/kphp

compiler/compiler-settings.cpp

Instead of doing an assert, do something with a more user-friendly
output for a somewhat common case where the user typed the filename incorrectly.
Imagine that you're doing this:
$ kphp2cpp foobar.php
Where `foobar.php` doesn't exist.
kphp2cpp message before:
```
Fatal error [gen by $KPHP/compiler/compiler-settings.cpp at 293]
In stage = []:
[file = unknown]
[function = unknown function:-1]
Assertion dir_pos != std::string::npos failed
Compilation failed.
It is probably happened due to incorrect or unsupported PHP input.
But it is still bug in compiler.
[pid 12570] [time 1605115955] SIGABRT caught, terminating program
[pid 12570] [time 1605115955] errno = No such file or directory
[pid 12570] [time 1605115955]
------- Register Values -------
[pid 12570] [time 1605115955] …
```

improve kphp2cpp error message for non-existing files

---

.github/workflows/Build.yml
.github/workflows/Dockerfile.buster
.github/workflows/Dockerfile.focal

Hi.
There are 5 builds:
1) buster/g++/c++14
2) focal/g++/c++14
3) focal/clang++/c++17/ubsan
4) focal/g++-10/c++20/asan
5) macos/clang++/c++14
Details
1) All linux builds work via Dockerfile, because it allows to cache prepared env, and reuse it later;
2) Macos build isn't cached, because it fails faster :) May be later it make sense to think about it;
3) Stages: (cmake + make) + run unit tests + build dummy php file and run it;
4) For Macos only cmake works, other fail and they are ignored;
5) The builds are started on creating pull request and pushing something to master.
Examples in my fork:
actions: https://github.com/AlexK0/kphp/actions
pr: https://github.com/AlexK0/kphp/pull/2

[tests] Add github actions config.

---

common/tl2php/combinator-to-php.cpp
common/tl2php/gen-php-code.cpp

TL long representation in PHP becomes `int64_t` instead of `mixed`.
Transition to it must be performed with taking into account that existing PHP code relies on `mixed` type. PHP code fixes are required for that. 
Moreover, transition must look 'simultaneous' for KPHP and vkext. For this reason the temporary 'toggle' is implemented as a private constant in one PHP TL class. Internal behavior of KPHP and vkext depends on this toggle. When it's off, TL long is represented as `mixed`, when it's on - as `int64_t`. When transition is completed, the toggle will be deleted and behavior will correspond `int64_t` TL long representation.

switch tl2php to int64_t TL long 

---

compiler/debug.cpp

To keep these in sync in the future, assert has been added.

add missing TokenType entries to TOKEN_TYPE_NAMES

---

compiler/code-gen/files/tl2cpp/tl-combinator.cpp
compiler/code-gen/files/tl2cpp/tl-module.cpp
compiler/code-gen/files/tl2cpp/tl2cpp-utils.cpp
compiler/pipes/check-tl-classes.cpp
compiler/tl-classes.cpp
compiler/tl-classes.h
functions.txt
runtime/memcache.cpp
runtime/memcache.h
runtime/rpc.cpp
runtime/rpc.h
runtime/tl/tl_builtins.h

Final step of new TL long transition described [here](https://github.com/VKCOM/kphp/pull/4).
TL long representation doesn't depend on the toggle anymore, it's always `int64_t`.
`store_long`, `RpcMemcache::increment` and `RpcMemcache::decrement` operate with `int64_t` instead of `mixed`.

Always treat TL long as int64_t in KPHP

---

compiler/gentree.cpp
compiler/lexer.cpp
tests/cpp/compiler/lexer-test.cpp
tests/phpt/phc/parsing/brackets.php
tests/phpt/phc/parsing/die.php

Instead of adding "(" and ")" to the tokens stream,
handle exit and die calls without "()" in GenTree.
The main benefit is that it'll be easier to implement
https://wiki.php.net/rfc/context_sensitive_lexer

handle exit and die calls without () in parser

---

compiler/vertex-gen.py

add final specifier to almost all vertices to avoid virtual call for `get_string` and similar methods

add `final` specifier to vertex classes if there are no derived

---

compiler/gentree.cpp
tests/phpt/parse_errors/fail_do_condition.php

This change fixes the mixed up cond/statement parse error messages.

make `do` statement parse more precise

---

compiler/vertex-desc.config.json
compiler/vertex-desc.json
compiler/vertex-gen.py
tests/cpp/compiler/lexer-test.cpp

Add "comment" optional field in vertex-desc.json for
vertices that may benefit from a little summary.
That comment is added to the docummented vertex type
as a C++ comment.
So, "comment": "lhs() and rhs()" for op_log_and_let will produce
something like this:
// lhs() and rhs()
template<>
class vertex_inner<op_log_and_let> : public vertex_inner<meta_op_binary> {
Another example:
// a simple var, like $foo; variable name is stored in str_val
template<>
class vertex_inner<op_var> final: public vertex_inner<meta_op_base> {
The <name>() notation in most comments refer to the named getter
of the vertex. In the example above, lhs() and rhs() are
accessors from meta_op_binary.
This improves readability of both places: json manifest and
generated C++ code (where we end up after "goto definition").

add comments for the generated vertex types

---

compiler/vertex-gen.py

So tests can be executed in environments that don't have Python 3.6.

replace f"" string with string concat in vertex-gen.py

---

compiler/pipes/preprocess-function.cpp
tests/phpt/msgpack_serialize/110_deserialize_class_without_annotation.php

Produce an error if `instance_deserialize` is called with non-serializable classes.

check that a class has the annotation when instance_deserialize is called

---

compiler/data/src-file.h

Old comments are misleading as documented fields are already contained inside a file-scoped object (they probably were moved from a FunctionData at some point in the past?).

fix SrcFile comments

---

docs/kphp-basics/installation.md

`apt-key` is now deprecated. Also, using config directories is considered good practice.

Docs: improve Debian repository instructions

---

compiler/debug.cpp
compiler/lexer.cpp
compiler/operation.cpp
compiler/pipes/gen-tree-postprocess.cpp
compiler/token.h
compiler/vertex-desc.json
tests/phpt/null_coalescing/12_assignment.php
tests/phpt/null_coalescing/13_assignment_call_rhs.php
tests/phpt/null_coalescing/14_assignment_throw_exceptions.php
tests/phpt/null_coalescing/15_assignment_lhs_fncall_error.php
tests/phpt/null_coalescing/16_assignment_lhs_fncall_error2.php
tests/phpt/null_coalescing/17_assignment_lhs_fncall_error3.php
tests/phpt/null_coalescing/18_assignment_lhs_fncall_error4.php
tests/phpt/null_coalescing/19_assignment_lhs_methodcall_error.php
tests/phpt/null_coalescing/20_assignment_lhs_methodcall_error2.php
tests/phpt/null_coalescing/21_assignment_lhs_methodcall_error3.php
tests/phpt/null_coalescing/22_assignment_this_reassign_error.php
tests/phpt/null_coalescing/23_assignment_error.php

Implemented as a pseudo op op_set_null_coalesce that is being
re-written as op_set+op_null_coalesce in GenTreePostprocessPass.
`$x ??= $y` => `$x = $x ?? $y`
We don't allow $x to be a function call to avoid issues with
evaluation order and the number of times $x being evaluated.
An example where the results are especially exciting in PHP `7.4.11`:
```php
<?php
class A {
/** @var ?int */
public $value = null;
}
function id($x) { echo "id()\n"; return $x; }
$a = new A();
id($a)->value ??= 10; // id() is called twice (!)
id($a)->value ??= 20; // id() is called only once
```
In KPHP such code would give a compile-time error right now.
It's more convenient to replace the pseudo op node than try to
parse tok_set_null_coalesce into op_set from the beginning.
We could have op_set_null_coalesce as …

add ??= operator support

---

common/tl2php/gen-php-code.cpp

Transition to new TL long described [here](https://github.com/VKCOM/kphp/pull/4) is finished now. It's not necessary to generate the toggle in tl2php anymore.

[tl2php] remove temporary toggle for new TL long switching

---

compiler/pipes/check-function-calls.cpp
compiler/pipes/preprocess-function.cpp
tests/phpt/errors/006_method_params_n.php
tests/phpt/errors/007_method_params_n_variadic.php

For instance methods we were reporting methods as receiving and expecting
as N+1 due to the implicit $this argument.
This example demonstrates the problem:
```php
class Foo { public function f($x) {} }
$foo = new Foo();
$foo->f(); // error: not enough arguments [found 1] [expected at least 2]
```
Variadic arguments make it even more exciting:
```php
class Bar { public function g($x, ...$y) {} }
$bar = new Bar();
$bar->g(); // error: function takes: 3 arguments; passed only 1
```
With this change, we report saner errors:
```php
$foo->f(); // error: not enought arguments [found 0] [expected at least 1]
$bar->g(); // error: not enought arguments [found 0] [expected at least 1]
```

fix 'too much'/'not enough' argument number errors messages for methods

---

compiler/stage.cpp

It makes it easier to use the location in the source code editor:
Compilation error [gen by $KPHP_ROOT/compiler/pipes/resolve-self-static-parent.cpp at 87]
=>
Compilation error [gen by $KPHP_ROOT/compiler/pipes/resolve-self-static-parent.cpp:87]
Most terminals also support this format to open the file ref in the associated app.

change the assert message header to be a proper location ref for IDE

---

compiler/compiler.cmake
compiler/compiler.cpp
compiler/data/virtual-method-generator.cpp
compiler/pipes/check-abstract-function-defaults.cpp
compiler/pipes/check-abstract-function-defaults.h
compiler/vertex-meta_op_base.h
tests/phpt/interfaces/015_default_in_derived_classes.php
tests/phpt/interfaces/133_different_defaults_in_derived.php

When we check that the default argument of interface or abstract method has the same value as every overloaded method from derived classes we have a data race. `InlineDefinesUsagesPass` tries can inline defines used as default value at the same time when we investigate such a situation.
Now we separate that check and do it after the synchronization pipe `GenerateVirtualMethods`.

fix race in resolving defines and checking defaults

---

compiler/pipes/fix-returns.cpp
compiler/pipes/fix-returns.h
tests/phpt/fork/016_forked_function_arg_returns_void_error.php

Hi,
here is a fix of SIGABRT which is raised on the following code
```php
<?php
function g() { echo "hi";}
function f($x) { return $x; }
function demo() {
$res = fork(f(g()));
}
demo();
```
So after this patch, KPHP checks the function calls which are passed to forked functions.

Check return of forked function args.

---

compiler/pipes/gen-tree-postprocess.cpp
runtime/profiler.cpp
runtime/profiler.h

Hi,
1) Replace `profiler_is_enabled()` call with `true` if profiler is enabled and with `false` if it is disabled;
2) Move `profiler_set_log_suffix()` and `profiler_set_function_label()` under `if(false)` for the disabled profiler.
I leave code under 'false' on purpose, so it is reachable and we can avoid compilation errors after profiler enabling.

Change the disabled profiler behavior

---

compiler/code-gen/files/global_vars_memory_stats.cpp
compiler/code-gen/files/global_vars_memory_stats.h
compiler/code-gen/files/init-scripts.cpp
compiler/code-gen/files/init-scripts.h
compiler/compiler-core.cpp
compiler/compiler-core.h
compiler/compiler-settings.cpp
compiler/compiler-settings.h
compiler/compiler.cpp
compiler/kphp2cpp.cpp
compiler/pipes/calc-bad-vars.cpp
compiler/pipes/code-gen.cpp
compiler/pipes/filter-only-actually-used.cpp
compiler/pipes/final-check.cpp
server/php-engine.cpp
server/php-script.cpp
server/php-script.h

usage: kphp <main-files>
=>
usage: kphp <main-file>
Supporting multiple main files doesn't seem to be useful
and it complicates code in some places where we need to
keep in mind that there could be several main files
although only the first one has real meaning.
Giving multiple positional arg to kphp command will result in an error:
Expected exactly 1 positional argument: main PHP file

remove support for multiple main files

---

compiler/compiler-core.cpp

When --composer-root is specified, kphp2cpp will try to locate
$composer-root/vendor folder. If it's a newly created composer project
without dependencies (or "composer install" was never executed)
there will be no vendor folder at all.
This change makes sure that we don't try to traverse the non-existing folder.

fix superfluous "No such file or directory" in composer mode

---

runtime/rpc.cpp
runtime/rpc.h
runtime/tl/rpc_request.h
runtime/typed_rpc.cpp

Here are 2 fixes:
- Update script runs counter on getting typed RPC TL response. Without it `rpc_tl_pending_queries_count()` always returns 0 if only typed RPC requests are used.
- Fix fatal error on inconsistent RPC TL API usage. Without it typed sending followed by untyped getting result or vice versa raises fatal error.

Some fixes in RPC lib

---

compiler/lexer.cpp
tests/cpp/compiler/lexer-test.cpp
tests/phpt/phc/parsing/instring.php
tests/phpt/phc/parsing/instring_complex.php
tests/phpt/phc/parsing/instring_complex_badsyntax_error.php
tests/phpt/phc/parsing/instring_complex_error.php
tests/phpt/phc/parsing/instring_complex_error2.php
tests/phpt/phc/parsing/instring_complex_error3.php
tests/phpt/phc/parsing/instring_complex_error4.php

This syntax is preferred by some programmers over {$...}.
The main reasoning behind this change is to make more PHP
programs compile as KPHP programs.
A more compilcated ${<expr>} form is not implemented, so
this will result in a compile error: "${a[0]}".
We may add more complete support for this syntax later.
Note: <expr> inside ${<expr>} is subtle and should
be handled separately, if ever attempted to be implemented.
For example, "${'foo'}" is identical to "$foo".
We don't support ${'foo'} variable syntax yet (which is a
valid freestanding PHP variable syntax btw).

add support for simple ${var} string interpolation expressions

---

.github/workflows/Build.yml
.github/workflows/Dockerfile.buster
.github/workflows/Dockerfile.focal
common/dl-utils-lite.cpp
common/dl-utils-lite.h
common/wrappers/string_view.h
runtime/exception.cpp
runtime/exception.h
runtime/interface.cpp
runtime/memory_usage.h
runtime/misc.cpp
runtime/php_assert.cpp
runtime/php_assert.h
server/json-logger.cpp
server/json-logger.h
server/php-engine.cpp
server/php-query-data.cpp
server/php-runner.cpp
server/server.cmake
tests/python/lib/engine.py
tests/python/lib/kphp_server.py
tests/python/tests/json_logs/php/index.php
tests/python/tests/json_logs/test_exceptions.py
tests/python/tests/json_logs/test_signals.py
tests/python/tests/json_logs/test_warnings.py

Hi,
In order to write JSON logs from signal handlers, JSON logger must be **_async-signal-safe_**.
https://man7.org/linux/man-pages/man7/signal-safety.7.html
So,
1) JSON logger has been refactored to become signal safe:
- no FILE stream API
- handmade buffered out
- raw file descriptor
2) Write JSON logs from SIGSEGV and SIGABRT handlers (for mater and workers) with error type -1 (except stack overflow, for it error type is 1)
3) Write JSON logs after uncaught exceptions, with additional tag `"uncaught": true` and error type 1
4) Add some python tests and integrate python tests into github workflow
Update:
5) Write `uncaught`  for each log record - set `true` if request has been unexpectedly terminated, false otherwise

Write JSON logs from signal handlers & after exceptions

---

compiler/gentree.cpp
tests/phpt/func_namespaces/fqn_simple.php
tests/phpt/func_namespaces/fqn_static_method.php
tests/phpt/func_namespaces/fqn_undefined_error.php
tests/phpt/func_namespaces/include/Foo.php
tests/phpt/func_namespaces/include/Utils/Foo.php

Since FQN names always resolve to the name without leading '\',
we can start with this and implement real function namespaces
support later (https://www.php.net/manual/en/language.namespaces.rules.php).
This change makes it possible to compile PHP projects that refer
to global functions using full qualified names.
Here is an example: https://github.com/symfony/polyfill-ctype/blob/main/Ctype.php#L36

permit FQN forms for the global function names

---

common/tl/query-header.cpp
common/tl/query-header.h
runtime/interface.cpp
server/php-engine.cpp
server/php-query-data.cpp
server/php-query-data.h

Allows to send extra RPC query headers to KPHP microservice. Saves them into `$_SERVER`. 
Without it you can't specify custom timeout for RPC request.

Extra RPC query headers for microservices

---

vkext/vkext-rpc.cpp

__Proof__: https://www.php.net/manual/en/internals2.ze1.zendapi.php
__TL;DR__
`INI_STR(name)` - Returns the current value of entry name as string. Note: This string is not duplicated, but instead points to internal data. Further access requires duplication to local memory.
__Description__:
This commit allows users in php code change unix_socket_directory through `ini_set("vkext.unix_socket_directory", your_new_path")`. Also it fixes possible `SIGSEGV` if someone used mentioned operation before.

Allow to change unix_socket_directory in runtime

---

compiler/pipes/cfg.cpp
compiler/utils/idgen.h
compiler/utils/idmap.h

For huge functions recursion could cause a SIGSEGV with the corrupted stack, it's better to be on the safe side.

use std::stack for CFG::cacl_used to avoid stack overflow

---

compiler/inferring/type-data.h

Hi. 
I've replaced uint8_t with PrimitiveType for TypeData, so it can be well printed in debugger.

Use PrimitiveType with bit filed.

---

compiler/class-assumptions.cpp
compiler/data/class-members.cpp
compiler/data/function-data.cpp
compiler/data/function-data.h
compiler/data/lambda-generator.cpp
compiler/debug.cpp
compiler/gentree.cpp
compiler/gentree.h
compiler/phpdoc.cpp
compiler/phpdoc.h
compiler/pipes/collect-main-edges.cpp
compiler/pipes/collect-required-and-classes.cpp
compiler/pipes/prepare-function.cpp
compiler/pipes/resolve-self-static-parent.cpp
compiler/vertex-desc.json
tests/phpt/typehints/params/02_question_tok_instead_of_params.php
tests/phpt/typehints/params/04_question_with_var.php
tests/phpt/typehints/return_types/13_static_is_not_allowed.php
tests/phpt/typehints/return_types/13_static_return_type.php

Previously, type hints (params of functions and return typehints) were parsed separately and stored as strings.
Now, KPHP parses type hints just the same as PHPDoc. This leads to support union type hints, like
function f(int|false $a): string|int
Also, 'mixed' is parsed correctly as a consequence:
function f(mixed $a): mixed
Moreover, a correct syntax is ANY type that can appear in PHPDoc. For instance, these examples are correct for KPHP, though they fail on PHP:
function f(int[] $arr): mixed[]
function f(tuple<int, string> $t): (int|false)[]
Multiple commits are squashed into a single, you can see development history in the PR.

support PHP8 union type hints and mixed typehint

---

compiler/pipes/analyze-performance.cpp
tests/phpt/performance_inspections/11_implicit_array_cast_warn.php

In terms of performance analysis, `make_clone()` does nothing, so it makes sense to ignore it.

Ignore make_clone() call in performance analysis.

---

common/dl-utils-lite.cpp
common/dl-utils-lite.h
common/fast-backtrace.cpp
common/fast-backtrace.h
common/kprintf.cpp
common/wrappers/pathname.h
runtime/interface.cpp
server/json-logger.cpp
server/json-logger.h
server/php-engine.cpp
server/php-runner.cpp
server/php-runner.h
tests/python/tests/json_logs/php/index.php
tests/python/tests/json_logs/test_timeouts.py

Hello!
1) Enable an ability to log server timeout events
2) Remove recursion from stack overflow logs (otherwise it's an impossible to find the stack overflow reason)
3) Add assertion details to SIGABRT log

Json logger improvements.

---

cmake/init-compilation-flags.cmake

It fixes paths in the compiler binary. e.g. `addr2line` gives a correct path `kphp/compiler/kphp2cpp.cpp` to source files instead of `kphp/build/../compiler/kphp2cpp.cpp`

add `debug-prefix-map` option to enhance paths to source files

---

runtime/zlib.cpp
server/confdata-binlog-replay.cpp
tests/phpt/dl/464_gzip.php

1) Fix confdata SIGSEGV on worker's termination and a possible shared memory corruption.
2) Don't crash zlib deconding on large data, because it is used on confdata loading. The warning will be written to json log.

Confdata fixes

---

.clang-tidy
compiler/code-gen/declarations.cpp
compiler/data/class-members.h
compiler/kphp2cpp.cpp
compiler/make/make-runner.cpp
compiler/phpdoc.cpp
compiler/phpdoc.h
compiler/pipes/check-classes.cpp
runtime/msgpack-serialization.cpp
runtime/msgpack-serialization.h
tests/phpt/msgpack_serialize/021_serialize_float32.php
tests/phpt/msgpack_serialize/022_cmp_float32_float.php
tests/phpt/msgpack_serialize/023_compound_float32.php

The new annotation for fields of serializable classes is implemented in the PR.
It should be used wisely in cases where you are 100% sure what you are doing.
Classes that are annotated as `@kphp-serializable` could use the tag `@kphp-serialized-float32` to let KPHP know which fields contain float value inside and will be serialized as 32-bit floats.
Sacrificing precision 4 bytes per float of a payload can be saved.

Serialize double as float

---

functions.txt
runtime/datetime.cpp
runtime/datetime.h
tests/phpt/dl/1026_hrtime.php

Not all PHP installations has hrtime enabled, so I had
to add a polyfill version of that function in tests.

implement hrtime() PHP function

---

.lldbinit
compiler/class-assumptions.h
compiler/data/class-data.h
compiler/data/define-data.h
compiler/data/function-data.h
compiler/data/lib-data.h
compiler/data/src-file.h
compiler/data/var-data.h
compiler/data/vertex-adaptor.h
compiler/debug.cpp
compiler/debug.h
compiler/inferring/key.cpp
compiler/inferring/key.h
compiler/inferring/multi-key.cpp
compiler/inferring/multi-key.h
compiler/inferring/node.cpp
compiler/inferring/node.h
compiler/inferring/type-data.h
compiler/location.h
compiler/token.h
lldb_addons.py
tests/cpp/compiler/lexer-test.cpp
tests/zend-test-list

It brings up visualizers to several classes, that are seen right in debugger.
Without expanding, we see function/class names:
As well as var names,
... type data,
... tokens,
... and many others.
Note, that FunctionPtr/ClassPtr and others are actually classes with `T *ptr` and overloaded `operator ->` proxying calls to FunctionData/ClassData/etc, that's why before this MR we had to expand two levels of nesting (FunctionPtr -> ptr FunctionData -> properties[]), and now we have to expand only one, this is implemented with lldb fake children. Moreover, when FunctionPtr/ClassPtr points to null, earlier we had to expand them to one-level to see that ptr=null, now such pointers are not expanded, which is very cute.
And even more! Now you can traverse AST tree right in debugger: for non-leaf …

Pretty printers for lldb: enhance CLion debugging experience

---

tests/phpt/dl/1015_parse_url.php
tests/zend-test-list

Hack tests for jessie, because there are no PHP updates for jessie.

Hack tests for jessie.

---

functions.txt
runtime/instance-to-array-processor.h
runtime/kphp_core.h
tests/phpt/cl/009_instance_to_array_with_class_names.php

Sometimes it's useful to get result of `instance_to_array` with class names. For example, it can be used as unique identifier of an object as `serialize(instance_to_array($obj, true))`. Instances of classes with the same set of fields are indistinguishable after `instance_to_array` without class names.
PR to kphp-polyfills: https://github.com/VKCOM/kphp-polyfills/pull/7

instance_to_array with class names

---

server/php-master-warmup.h
server/php-master.cpp

For tuning warm up parameters we need to know 'hotness' of instance cache at the end of warm up, e.g. when warm up timeout is expired. Here are 2 things to help with this:
- new stat metrics `new IC size` and `old IC size`, where `IC size` is the size of instance cache in corresponding master (new or old) at the end of warm up on graceful restart
- log instance cache sizes during warm up

Emit more info about warm up on graceful restart

---

common/php-functions.h
compiler/code-gen/vertex-compiler.cpp
compiler/gentree.cpp
compiler/inferring/expr-node.cpp
compiler/operation.cpp
compiler/pipes/analyze-performance.cpp
compiler/pipes/cfg.cpp
compiler/pipes/final-check.cpp
compiler/vertex-desc.json
runtime/array_functions.h
runtime/comparison_operators.inl
runtime/interface.cpp
runtime/kphp_core.h
runtime/math_functions.h
runtime/mixed.inl

Hi, this patch replaces some compare operations, and removes them from AST.
1) `$a  > $b`  to `$b < $a`
2) `$a  >= $b`  to `$b <= $a`
3) `$a  != $b`  to `!($b == $a)`
4) `$a  <> $b`  to `!($b == $a)`

Get rid of >, >=, !=, <> operations from AST.

---

compiler/gentree.cpp
compiler/gentree.h
compiler/pipes/calc-rl.cpp
tests/cpp/compiler/lexer-test.cpp
tests/phpt/parse_errors/fail_parens_dec.php
tests/phpt/parse_errors/fail_parens_inc.php
tests/phpt/parse_errors/fail_string_indexing.php
tests/phpt/phc/parsing/iife.php
tests/phpt/phc/parsing/literal_indexing.php
tests/phpt/phc/parsing/literal_indexing_error.php
tests/phpt/phc/parsing/literal_indexing_error2.php
tests/phpt/phc/parsing/parenthesized_postfix_expr.php

This change allows these expressions to be parsed:
"foo"[index]         string literal indexing
[$a, $b][index]      array literal indexing
("foo")[index]       parentheses expr indexing
(function() {...})() immediately invoked function expressions
(new Foo())->f()     parenthesized expr arrow access
All cases above are valid in PHP.
These are not valid in PHP, therefore they are forbidden in KPHP as well:
($x)++
($x)--
No codegen diff on vkcom.

allow literals and '()'-expressions to be postfix expr operands

---

server/php-master-restart.cpp
server/php-master-restart.h
server/php-master-warmup.h
server/php-master.cpp

`elements_stored` is the global number of elements stored in cache since server start, it always increases.
`elements_cached` is the current size of cache.

use elements_cached instead of elements_stored in warmup on graceful restart

---

runtime/json-functions.cpp
tests/phpt/dl/395_subnormal_doubles_in_json.php

Subnormal floats works in json_encode for vanilla PHP, so now it works for KPHP as well.

Allow subnormal floats usage in json_encode functions.

---

server/json-logger.cpp
tests/python/tests/json_logs/test_warnings.py

This patch enables the special chars relapsing and escaping for json log env.

Escape env in json logs.

---

compiler/pipes/optimization.cpp

Very-very seldom, but we had occasions, that build fails with an error
> called do_recalc on finished inferer in optimization-pass
It's a fluck, and relauching the compilation always helped.
Probably I have found the reason, here is the fix.
It could happen after type inferring (in optimization pass),
when multiple threads implicitly casted arrays to one and the same variable,
and the first thread created this variable but didn't reach setting tinf node,
and the second thread used that variable with the same name without creation.

fix race condition "called do_recalc on finished inferer"

---

compiler/code-gen/code-gen-task.h
compiler/code-gen/files/function-header.cpp
compiler/code-gen/files/function-source.cpp
compiler/code-gen/files/tl2cpp/tl2cpp.cpp
compiler/code-gen/vertex-compiler.cpp

Ensure, that two successive launches of codegen compile() (W << cmd) doesn't change the output.
This fact will be used in future optimizations.

small fixes to make and ensure that codegen is idempotent

---

compiler/pipes/extract-resumable-calls.cpp
compiler/pipes/extract-resumable-calls.h
tests/phpt/fork/019_ternary_operator_in_resumable_expr.php
tests/phpt/fork/020_logical_operators_in_resumable_expr.php
tests/phpt/fork/021_null_coalesce_in_resumable_expr.php

Hi there! 
This patch enables the following resumable call expressions:
1) For ternary operator
2) For && and || operations
3) For lhs of ?? operator
It forbids complex expressions in the lhs part of op_set with the resumable rhs: only non global vars are allowed.
So, the following code examples are available now (imagine that all functions are resumable)
```php
$v = check() ? true_case() : false_case();
$v = check() ?: false_case();
$a[] = check() ? true_case() : false_case();
$a[$key] = check() ? true_case() : false_case();
$i->a = check() ? true_case() : false_case();
if (check() ? true_case() : false_case()) {
// ...
}
```
```php
$v = check1() && check2();
$v = check1() || check2();
if ((check1() && check2()) || (check3() && check4())) {
// ...
}
```
```php
$v = get() ?? "null";
``` …

User friendly resumable expressions.

---

compiler/code-gen/vertex-compiler.cpp
docs/kphp-internals/kphp-architecture/internals-runtime.md
functions.txt
runtime/interface.cpp
runtime/interface.h
runtime/php_assert.cpp
runtime/php_assert.h
runtime/resumable.cpp
runtime/resumable.h
server/php-runner.cpp
tests/phpt/fork/019_wait_all_forks_on_finish.php
tests/python/tests/json_logs/test_exceptions.py

Hi!
1) I've made some style refactoring of resumable (for better understanding what's going on there)
2) I've added a function which enables waiting of all unfinished forks after finish request
```
bool set_wait_all_forks_on_finish(bool $wait);
```
It doesn't wait in case of
- critical errors: OOM, internal assertions, calling virtual methods on nullptr
- timeouts
- unhandled exceptions
Request is terminated in case of
- critical errors (look above) in the fork
- request timeouts during waiting the fork
In case of an exception from the fork, the request is not terminated, however the logs (json and plain) are written.

Implement function for waiting all forks on finish & resumable minor refactoring.

---

functions.txt
runtime/regexp.h
tests/phpt/regexp/001_string_result.php
tests/phpt/regexp/002_null_error.php

If `$subject` is a string, the result will be `?string`, not `mixed`.
We achieve this by the same trick as in `str_replace` return type.
The `^3|string|null` will resolve into either `string|null` or `mixed`.
It's `?string` when `^3` is a string; otherwise, any T+string will result in `mixed`.

improve preg_replace and preg_replace_callback typing

---

runtime/regexp.cpp
tests/phpt/regexp/003_preg_match_neg_offset.php
tests/phpt/regexp/004_preg_match_high_offset.php

Negative offset is interpreted as an offset from the end of the string.
If offset exceeds the `$subject` length, PHP returns false
with `PHP_PCRE_INTERNAL_ERROR` error (internally, it sets `PCRE2_ERROR_BADOFFSET`).
This behavior is tested on `PHP7.2`, `PHP7.4` and `PHP8.0`.
Fixes #145
----
Could be useful for the review: https://github.com/php/php-src/blob/2dc2436e08e1c80247a940dedeae67135e1c233a/ext/pcre/php_pcre.c#L1224-L1237

implemented negative offsets for regexps + offset overflow errors

---

runtime/array.inl
runtime/array_decl.inl
runtime/json-functions.h
runtime/msgpack-serialization.h
tests/phpt/msgpack_serialize/024_serialize_vector.php

Hi!
This small patch allows encode pseudo vectors as vectors for msgpack serialization.
So it works the same way as in a vanilla php implementation.

Check if array is pseudo vector for msgpack serialization.

---

runtime/array_functions.h
tests/phpt/array/014_array_rand.php

Php throw warning, if you pass in array_rand NUM that greater then array size.
Kphp does not throw it. But throws only when array size. == 0.
Message looks like: Parameter num of array_rand must be positive.
That happens cause
if num > size: we make num equal to size
so if we have num 5, size == 0, then we have num == 0
and that errors triggers.
I've made fix for right alert.

Fix warning in array_rand when num less then array size

---

functions.txt
runtime/openssl.cpp
runtime/openssl.h
tests/phpt/openssl/5_hash.php

This patch enables `sha224`, `sha384`, `sha512` algorithms for `hash()` and `hash_hmac()`.
Also `hash_hmac_algos()` was implemented.

Support sha224, sha384, sha512 for hash() and hash_hmac().

---

compiler/data/class-members.cpp
compiler/data/class-members.h
compiler/data/lambda-generator.cpp
compiler/gentree.cpp
compiler/gentree.h
compiler/pipes/parse-and-apply-phpdoc.cpp
compiler/pipes/sort-and-inherit-classes.cpp
tests/phpt/cl/005_cast_instance_to_array.php
tests/phpt/cl/008_fields_default_value.php
tests/phpt/cl/025_class_depends_kphp_inline.php
tests/phpt/msgpack_serialize/000_primitives.php
tests/phpt/msgpack_serialize/000_primitives_hints.php
tests/phpt/msgpack_serialize/005_with_namespaces_hints.php
tests/phpt/reqtyping/030_req_class_typing_1.php
tests/phpt/stacktrace/07_stacktrace.php
tests/phpt/stacktrace/09_stacktrace.php
tests/phpt/typehints/fields/01_field_type_hint.php
tests/phpt/typehints/fields/02_field_type_hint_self.php
tests/phpt/typehints/fields/03_field_type_hint_array.php

Now we can write simple types near class fields instead of `@var`:
```
class A {
public int $field = 0;
public ?self $me = null;
```
Both for instance and static fields.
KPHP can parse any syntaxically correct type hints (int[] and string|false for example), but PHP supports only some primitives and nullable (and union since php 8).

support php 7.4 class type hints

---

compiler/data/src-file.h
compiler/gentree.cpp
compiler/phpdoc.cpp
compiler/phpdoc.h
compiler/pipes/collect-main-edges.cpp
compiler/pipes/preprocess-function.cpp
docs/kphp-language/static-type-system/type-casting.md
tests/phpt/declare/01_strict_types.php
tests/phpt/declare/01_strict_types.php.inc
tests/phpt/declare/02_strict_types2.php
tests/phpt/declare/02_strict_types2.php.inc
tests/phpt/declare/03_strict_types_error.php
tests/phpt/declare/03_strict_types_error.php.inc
tests/phpt/declare/04_strict_types_kphpinfercast.php
tests/phpt/declare/04_strict_types_kphpinfercast.php.inc
tests/phpt/declare/05_strict_types_kphpinfercast2.php
tests/phpt/declare/05_strict_types_kphpinfercast2.php.inc
tests/phpt/declare/06_strict_types_kphpinfercast_error.php
tests/phpt/declare/06_strict_types_kphpinfercast_error.php.inc
tests/phpt/declare/07_strict_types_kphpinfercast_error.php
tests/phpt/declare/08_strict_types_kphpinfercast.php
tests/phpt/declare/09_strict_types_not_enabled.php
tests/phpt/declare/09_strict_types_not_enabled.php.inc
tests/phpt/declare/can_call_with_cast.php.inc
tests/phpt/declare/cant_call_with_cast.php.inc
tests/phpt/declare/infercast_func.php.inc

In PHP, strict_types=1 would break the code at the run time if given
argument types mismatch expected types (expressed via type hints).
Previously, in KPHP it would silently cast these types and we'll
get inconsistent behavior between PHP and KPHP.
This change makes KPHP code a little bit closer to PHP,
but instead of failing at the run time we enable more type checking
for cast params in `strict_types=1` files.
A lot of existing PHP code is not prepared for this, so
this behavior is activated only if `declare()` has a phpdoc
with `@kphp-strict-types-enabled`.
As in PHP, strict_types is checked at the call site.

make `strict_types=1` disable automatic cast insertion for a current file

---

functions.txt
runtime/string_functions.cpp
runtime/string_functions.h
tests/phpt/string_functions/001_strip_tags_7_4.php
tests/phpt/string_functions/002_substr_replace.php
tests/phpt/string_functions/003_strip_tags_mixed_arg.php

This change makes `string_tags()` compatible with PHP7.4 version of that function.
$allow can accept array of allowed tags.
Also fixed an issue where self-closing tags were not ignored.
They are ignored since PHP5.3.4, so using them is a logical error.
Instead of `<br/>`, users should use `<br>` which will match both
`<br>` and `<br/>` tags.
For `substr_replace()` function, implicit casts for string arguments
are removed to avoid unwanted array->string conversions.
Result type changed from `Optional<string>` to just `string`;
the corner-case behavior is adjusted to be identical to what PHP does.
This code is an example of natural `substr_replace()` usage:
```php
$s = substr_replace($s, $rep, $offset);
```
If `substr_replace()` returns optional, `$s` stops being string here.
We may add …

make strip_tags accept array as $allow, remove implicit cast from substr_replace

---

functions.txt

It's not needed an it seems that it was not removed
before the exceptions-related code was submitted.

remove the forgotten function from functions.txt

---

compiler/pipes/check-conversions.cpp
compiler/pipes/preprocess-function.cpp
tests/phpt/declare/10_strict_types_enabled.php
tests/phpt/declare/10_strict_types_enabled.php.inc
tests/phpt/declare/11_strict_types_enabled_error.php
tests/phpt/declare/11_strict_types_enabled_error.php.inc

When `strict_types=1` is used, there will be no implicit `string->regexp` and `mixed->regexp`
conversions, but in fact we don't need them as there are various overloadings
that can work with all such types (string, regexp, mixed).
With this change, it will be possible to use string-typed arguments
to `preg_*` functions when `declare(strict_types=1)` is used.

allow `T->regexp` implicit casts even with `strict_types=1`

---

compiler/data/performance-inspections.cpp
compiler/data/performance-inspections.h
compiler/pipes/analyze-performance.cpp
compiler/pipes/parse-and-apply-phpdoc.cpp
tests/cpp/compiler/data/performance-inspections-test.cpp
tests/phpt/performance_inspections/13_warn_tag_for_class.php
tests/phpt/performance_inspections/14_warn_tag_for_interface.php
tests/phpt/performance_inspections/7_array_reserve_warn.php
tests/phpt/performance_inspections/8_array_reserve_no_warn.php

1) Support performance inspections enabling for classes
2) Not retailed, but important: support new array_reserve_* functions.

Support performance inspections enabling for classes

---

.github/workflows/Dockerfile.buster
.github/workflows/Dockerfile.focal
common/smart_ptrs/unique_ptr_with_delete_function.h
functions.txt
runtime/runtime.cmake
runtime/zstd.cpp
runtime/zstd.h
tests/cpp/runtime/runtime-tests.cmake
tests/cpp/runtime/zstd-test.cpp
tests/kphp_tester.py
tests/phpt/zstd/1_compress.php
tests/phpt/zstd/2_uncompress.php
tests/phpt/zstd/3_compress_uncompress.php
tests/python/tests/http_server/php/index.php
tests/python/tests/http_server/test_zstd.py

This patch adds basic zstd functions for KPHP:
```php
function zstd_compress(string $data, int $level = 3) : string|false;
function zstd_uncompress(string $data) : string | false;
function zstd_compress_dict(string $data, string $dict) : string | false;
function zstd_uncompress_dict(string $data, string $dict) : string | false;
```
They have the same meaning as the functions from the PHP binding https://github.com/kjdev/php-ext-zstd

Implement zstd api.

---

common/smart_ptrs/intrusive_ptr.h
runtime/array_decl.inl
runtime/mixed.cpp
runtime/mixed.inl
runtime/mixed_decl.inl
runtime/runtime.cmake
runtime/string.cpp
runtime/string.inl
runtime/string_decl.inl

The aim of the patch is to improve the sentry backtraces. 
The main pain is that we have a over-inlining of the compiled code and as a result addr2line misses and produces very wired traces, e.g. a custom function call from the mixed destructor. 
I've made some experiments and found that a moving the mixed destructor to the cpp file helps here and after that addr2line shows fine traces.
So, I suggest:
- move string and mixed desctructors to cpp files
- remove force inlining from some descturtors
Yeh, it's unclear how it would affect the performance, but I believe, that we won't notice it, may be only with micro benchmarks.

Improve backtrace experience

---

runtime/regexp.cpp
tests/phpt/regexp/005_regexp_match2.php

`$match_all` param was ignored, so `preg_match` behaved like `preg_match_all`;
this led to return value being different from PHP.
```php
preg_match('/\d/', '123');
// => 1 in PHP
// => 3 in KPHP
```
It also led to a degraded performance as we did repeated regexp execution
to find all matches.
Here is a comparison of the old implementation (preg_match like preg_match_all)
and new implementation (that does not try to find all matches):
name            old time/op  new time/op  delta
PregMatchShort  1.39µs ± 3%  0.65µs ± 7%  -53.34%  (p=0.000 n=10+8)
PregMatchLong   47.2µs ± 1%   0.5µs ± 2%  -99.33%  (p=0.000 n=10+9)
Performance results are collected with ktest utility.

fix `preg_match($pat, $s)` overloading

---

common/stats/provider.cpp
common/stats/provider.h
runtime/memory_resource/memory_resource.cpp
server/cluster-name.cpp
server/cluster-name.h
server/confdata-stats.cpp
server/php-engine-vars.cpp
server/php-engine-vars.h
server/php-engine.cpp
server/php-master.cpp
server/php-worker-stats.cpp
server/server.cmake
tests/cpp/server/cluster-name-test.cpp
tests/cpp/server/server-tests.cmake
tests/python/lib/stats_receiver.py

Hi!
This patch replaces stats histogram -> gauge, so they look more stable in grafana.
UPDATE:
I've also enabled an ability to use cluster name as prefix for stats: it's useful, because it allows to split stats from several kphp servers on one host.

Replace histogram -> gauge stats.

---

compiler/code-gen/files/tl2cpp/tl-module.cpp

This header is useless, because it is existed in precompiled header as well.

Drop extra TL header.

---

functions.txt
runtime/job-workers/client-functions.cpp
runtime/job-workers/client-functions.h
tests/python/tests/job_workers/php/ComplexScenario/_http_scenario.php
tests/python/tests/job_workers/php/http_worker.php

Job now is represented as `future<KphpJobWorkerResponse>` instead of `int64_t`

Job workers: improve interface

---

runtime/regexp.cpp
tests/phpt/dl/496_regex.php
tests/phpt/regexp/006_preg_quote.php
tests/zend-test-list

This behavior is consistent with PHP7.3+
Output for 7.3.0 - 7.3.27, 7.4.0 - 7.4.16, 8.0.0 - 8.0.3
string(2) "\#"
Output for 5.6.0 - 5.6.40, 7.0.0 - 7.0.33, 7.1.0 - 7.1.33, 7.2.0 - 7.2.34
string(1) "#"
Part of the PHP7.2 -> PHP7.4 transition.

make preg_quote escape '#' sign

---

.idea/misc.xml
tests/.gitignore
tests/python/lib/testcase.py

So now, tmp dir for python tests can be excluded from clion project.

Move python tests in separate dir

---

compiler/pipes/preprocess-function.cpp
tests/phpt/lambdas/047_typed_lambda_through_var.php

Fix compilation when a typed lambda is passed through a temporary variable to function

fix passing lambdas through variables

---

compiler/pipes/check-classes.cpp
tests/phpt/msgpack_serialize/111_non_serializable_inner_class.php

Add a compile-time check that all fields in `kphp-serializable` classes do not contain `non-serializable` instances

add a check that all inner classes are serializable

---

compiler/pipes/resolve-self-static-parent.cpp
tests/phpt/cl/180_fail_self_in_static_methods.php

Stop replacing `self::` usages in static methods with `$this->` to avoid awkward error message `Variable $this has Unknown type`.

Fix self unknown this

---

compiler/pipes/preprocess-function.cpp
tests/phpt/lambdas/048_unknown_lambda.php

In the PR we pass through pipes the new-generated lambda's `_invoke` method as it is created implicitly in resolving assumptions and will be thrown away lately.

fix compilation error when typed lambda is declared but not used

---

compiler/gentree.cpp
compiler/stage.cpp
compiler/stage.h
tests/kphp_tester.py
tests/phpt/parse_errors/fail_without_error_from_lambda.php

Lambda parser returns `null function` if any error occurs. But it doesn't count previous errors.
In the PR counter of errors is added to distinguish new errors from old ones.
On top of that, negative regular expressions have been added to `kphp_tester.py` to check that extra errors do not arise.

remove a redundant error from parsing lambdas

---

runtime/regexp.cpp
runtime/regexp.h

It's always false; it makes the code slightly more complicated.
If we ever want to add conditional fixes to the regular expressions,
it could be a different flag or we can take it back, but the
current fixes are not needed.

remove unused fix_php_bugs flag from the regexp module

---

functions.txt
runtime/interface.h
tests/phpt/declare/03_strict_types_error.php
tests/phpt/declare/03_strict_types_error.php.inc

This will make this function usage safer when `strict_types=1` is used.
Right now it allows any argument and will fail at the run time if it
can't be converted to int.
Removed the template version as implicit cast param should insert `intval()`
calls where appropriate.

mark long2ip argument type as int

---

server/job-workers/job-worker-server.cpp
server/php-engine.cpp
server/php-master.cpp
tests/python/tests/job_workers/php/http_worker.php
tests/python/tests/job_workers/php/job_worker.php
tests/python/tests/job_workers/test_job_graceful_termination.py

Here is graceful termination logic for job workers. Now master process waits for termination of all job workers as well as all HTTP workers on graceful shutdown / restart.
Note: job workers are always terminated strictly after all HTTP workers.

Job workers: graceful termination

---

common/pid.h
common/tl/constants/kphp.h
server/lease-config-parser.cpp
server/lease-context.h
server/php-engine-vars.cpp
server/php-engine-vars.h
server/php-engine.cpp
server/php-lease.cpp
server/php-lease.h

Here is a try to fix bug with error -2005, "Task invoker is invalid".
It seems that this bug happens, because KPHP treats old lease target incorrect immediately after send `STOP_READY` to it on changing lease target, then gets task from lease target that was sent before `STOP_READY` receiving and rejects it.
To fix this, we will wait with some timeout for an acknowledgement that `STOP_READY` was received, and only after that treat lease target incorrect.

Fix race condition in task (lease) communication protocol

---

compiler/inferring/restriction-stacktrace-finder.cpp
tests/phpt/stacktrace/10_stacktrace.php
tests/phpt/stacktrace/11_stacktrace.php

fixes KPHP-1275
Two new tests were added, that didn't pass before

improve stacktrace on type mismatch when variable reassigning occurs

---

compiler/pipes/calc-bad-vars.cpp

Now, `wait()` is an implicit edge when building a call graph for calculating bad vars for all resumable functions. The reason is probably an assumption that "If I am resumable, some other function can modify globals if I am interrupted". 
That makes sense, but in fact, there is only 1 diff on vkcom when removing this condition.
Why do I want to remove this? The main reason is that I want to use the same call graph to implement function coloring. And of course, colors do not become reachable from any resumable function. Also, this change speeds up CalcBadVarsF for about 2 seconds even without other optimizations — because call graph connectivity becomes smaller.

drop wait() edges from a call graph of calculating bad vars

---

compiler/code-gen/files/init-scripts.cpp
compiler/code-gen/files/init-scripts.h
compiler/code-gen/files/tl2cpp/tl2cpp.cpp
compiler/code-gen/files/tl2cpp/tl2cpp.h
compiler/compiler-core.cpp
compiler/compiler-core.h
compiler/data/function-data.cpp
compiler/data/function-data.h
compiler/pipes/code-gen.cpp
compiler/pipes/code-gen.h

Dropped, or paralleled, or removed some computations that were previously done in a single thread:
* Don't get a vector of functions and sort it
* Extract preparing functions to execute() to be run in parallel.
* Async launch of tl-schema generation and other previously sync tasks.

optimize CodeGenF::on_finish() performed in a single thread

---

compiler/data/function-data.h
compiler/data/var-data.h
compiler/pipes/calc-bad-vars.cpp
compiler/pipes/calc-func-dep.cpp
compiler/pipes/calc-func-dep.h
compiler/pipes/check-ub.cpp
tests/phpt/warnings/1_ub_foreach_var_trycatch.php
tests/phpt/warnings/2_ub_foreach_var_trycatch2.php
tests/phpt/warnings/3_ub_var_trycatch.php
tests/phpt/warnings/5_ub_globals.php

"bad vars" for a function are used in check-ub.cpp.
They are modified non-primitive globals, that can lead to a potential ub when modified and accessed in subcalls.
Added comments about optimization points and some tests.

optimize bad_vars calculation performed in a single thread

---

compiler/function-colors.cpp
compiler/function-colors.h
compiler/pipes/calc-bad-vars.cpp
tests/phpt/colors/023_color_remover.php

Functions marked with this special color are dropped off the call graph, like they don't exist at all.
We'll use this in real code for routing points like callAct or for exit points like fatalExit.
Marked functions will allow us to deal with highly-connected indirectly-recursive call graph components, where every function is accessible from every other.
Using this special color for functions like callAct can split such components into smaller ones, which influences all palette rules at once.

support '@kphp-color remover' for manual splitting recursively-joined call graph components

---

common/pipe-utils.cpp
common/pipe-utils.h
functions.txt
runtime/interface.cpp
runtime/job-workers/client-functions.cpp
runtime/job-workers/job-interface.cpp
runtime/job-workers/job-interface.h
server/job-workers/job-message.h
server/job-workers/job-worker-server.cpp
server/job-workers/job-worker-server.h
server/php-engine-vars.h
server/php-engine.cpp
server/php-master.cpp
server/php-runner.cpp
server/php-worker-stats.cpp
server/php-worker-stats.h
server/php-worker.cpp
tests/cpp/server/job-workers/shared-memory-manager-test.cpp
tests/python/tests/job_workers/php/SyncJobCommand.php
tests/python/tests/job_workers/php/http_worker.php
tests/python/tests/job_workers/php/job_worker.php
tests/python/tests/job_workers/test_job_worker_wakeup.py

Here are the following enhancements for job workers:
1. Configuring epoll to wake up only one worker on event, instead of all
2. Fix job shared memory leak, when worker terminates before script is inited
3. Implement `kphp_job_workers_count()` function
4. Other minor improvements

Job workers: enhancements

---

runtime/array.inl
runtime/array_decl.inl
runtime/instance-copy-processor.cpp
runtime/instance-copy-processor.h
tests/phpt/array/015_array_replace_neg_keys.php

This patch fixes a bug when negative keys lead a crash from runtime.
Also I've done some refactoring.
Here I've also moved shared memory copying process for primitive types into runtime lib, it compiles with -O3 optimization level, so it works faster now!

Fix negative keys bug

---

compiler/data/function-data.h
compiler/pipes/calc-bad-vars.cpp
compiler/pipes/check-nested-foreach.cpp
compiler/pipes/check-nested-foreach.h
tests/phpt/fork/025_foreach_by_global_var_ref_error.php
tests/phpt/fork/026_foreach_by_class_static_var_ref_error.php
tests/phpt/fork/027_foreach_by_static_var_ref_error.php
tests/phpt/fork/028_foreach_by_instance_field_ref_error.php

Consider the following example 
```php
<?php
$global_var_x = [["x"], "y"];
function wait_once($i) {
static $flag = true;
if ($flag) {
wait($i);
$flag = false;
}
}
function foo() {
global $global_var_x;
sched_yield();
$global_var_x = 1;
return null;
}
function demo() {
global $global_var_x;
$i = fork(foo());
foreach ($global_var_x as &$value) {
wait_once($i);
$value = [1];
}
var_dump($global_var_x);
}
demo();
```
kphp2cpp compiles it, but if you try to run it, you'll get SIGSEGV or other runtime error. The problem is going form the foreach reference.
This patch forbids such kind of constructions: calling resumable function from foreach body which iterates by reference with non local scope viability variable: global vars, static vars, class static vars,and instance fields.

Forbid reumable calls in foreach by reference from non local vars

---

tests/phpt/cl/182_toString_magic_method_call_function.php
tests/phpt/phc/parsing/instring_simple_error.php

- Removed typehint for a class property, as it
is not supported until PHP 7.4;
- Fixed error message in the test when using a
class without `__toString()` when converting to
a string.

fixed tests for toString

---

compiler/class-assumptions.cpp
tests/phpt/smart_casts/05_unions.php
tests/phpt/smart_casts/06_unions_with_interfaces.php
tests/phpt/smart_casts/07_nullable_class.php

Teach extract_instance_from_type_hint() how to handle union types.
The algorithm used is close to the one that is used during the type inference.
We try to find a common base type for all union variants.
If there are multiple candidates, we'll give up.
This is good enough for most sane class hierarchies.
Fixes #217

enable instanceof smart casts for unions

---

common/tl/store.h
server/php-master.cpp
server/php-worker-stats.cpp

This patch fixes g++11 with fresh glibc 2.33+ build.

Fix gcc11 build.

---

compiler/code-gen/vertex-compiler.cpp
runtime/array.inl
runtime/array_decl.inl
runtime/mixed.inl
runtime/mixed_decl.inl

Currently, isset() and unset() functions of array calculate hash from compile time known strings at runtime. This patch modify such behavior and move calculation of hash at code generation phase.

Precompute hashes for isset() and unset()

---

compiler/data/class-data.cpp
compiler/data/class-data.h
tests/phpt/regress/issue215/test1.php
tests/phpt/regress/issue215/test2.php
tests/phpt/regress/issue215/test3.php

Previously, we used this approach:
* Collect all ancestors into `std::vector` (interfaces, base classes)
* Iterate over them, return the first member match
What we get wrong with this approach is that we could get an abstract method
instead of the implementation as the order of `get_all_ancestors()` doesn't
prefer classes to interfaces.
Consider this case:
```php
interface Iface { function f(); }
// Actually implements Iface, but doesn't state that
abstract class AbstractBase {
public function f() {}
}
abstract class AbstractBase2 extends AbstractBase {}
// Implements Iface via AbstractBase, which is a base class of AbstractBase2
class Concrete extends AbstractBase2 implements Iface {}
```
With the old approach, we'll get a compile-time error.
The new approach prefers non-abstract …

rewrite ClassData::get_instance_method()

---

server/php-master.cpp
server/server-stats.cpp
server/server-stats.h
tests/python/tests/stats/test_master_stats.py

This patch disable sending pid via mc stats because it breaks some monitoring scripts.

Don't sent pid on mc stats request.

---

functions.txt
runtime/job-workers/client-functions.cpp
runtime/job-workers/client-functions.h
server/job-workers/job-worker-client.cpp
server/job-workers/job-worker-server.cpp
server/job-workers/shared-memory-manager.h
server/php-engine.cpp
server/php-master.cpp
tests/cpp/server/job-workers/shared-memory-manager-test.cpp
tests/phpt/job_workers/1_interface_compilation.php
tests/phpt/job_workers/2_shared_immutable_messages_basic_compilation.php
tests/python/tests/job_workers/php/ComplexScenario/_http_scenario.php
tests/python/tests/job_workers/php/SharedImmutableMessageScenario/http_worker.php
tests/python/tests/job_workers/php/X2Request.php
tests/python/tests/job_workers/php/http_worker.php
tests/python/tests/job_workers/php/job_worker.php
tests/python/tests/job_workers/php/utils.php
tests/python/tests/job_workers/test_job_inside_job.py

If we allow to run jobs from job workers, we face with the problem of self-locks.
It happens in the following cases:
1. If all job workers simultaneously send a job. So there're no free job workers to serve this new job, because all of them are waiting for job response. The core reason of this case is that all jobs are processed synchronously, e.g. worker can't serve new job while another one is running.
2. When epoll reactor "binds" a new job event to the sender job worker process and never wake up another free job workers on this event. As far as I can see, the core reason of this case is internal events delivery mechanism of epoll in `EPOLLEXCLUSIVE` mode.
To solve the problems I've done the following:
1. Made timeout parameter of `kphp_job_worker_start()` function required. It must …

Job workers: starting job from job workers 

---

compiler/pipes/register-variables.cpp
tests/phpt/cl/192_access_to_undef_class.php

This simple PR fix crash of compiler on such code with undefined class Foo:
```
<?php
var_dump(Foo::$static_var_x);
```

Gracefully terminate on 'class not found' compile error

---

common/tl/compiler/tl-parser-new.cpp

If type of the argument is undeclared constructor, then its type can not be polymorphic.
If type can not be polymorphic, then constructor name and type name are differ in register of first letter.
This commit allows to concatenate tl-scheme files really in any order.
For example, now you can use primitive type int before its declaration:
```
....
@readwrite friends.deleteUser uid:int = Bool;
...
int#a8509bda ? = Int;
```

[tl-compiler] allow use constructor as argument type before constructor declaration

---

runtime/streams.cpp
tests/phpt/streams/csv_input.txt
tests/phpt/streams/fgetcsv.php
tests/phpt/streams/fputcsv.php

This is how it works in PHP7.4.
See https://bugs.php.net/bug.php?id=51496

allow empty escape_char in fgetcsv/fputcsv functions

---

compiler/gentree.cpp
compiler/pipes/cfg.cpp
tests/phpt/dl/1030_ternary_fails.php
tests/phpt/dl/1031_shorthand_ternary_fails.php
tests/phpt/optional/004_operations.php
tests/phpt/smart_casts/08_auto_drop_optional_inside_condition.php

Enable smartcasts for opset inside condition; this also involves smartcasts in shorthand ternary operator.

Enable smartcasts for opset inside condition

---

compiler/pipes/preprocess-function.cpp
tests/phpt/errors/008_reset_func.php
tests/phpt/errors/009_end_func.php

KPHP doesn't have `reset()` and `end()` functions, but
many times people want `array_first_value()` or `array_last_value()` instead.
Giving a better error message here is the least we can do.

suggest reset()/end() funcs alternative in error messages

---

compiler/compiler-core.cpp
compiler/compiler-core.h
compiler/compiler.cpp
compiler/data/src-file.cpp
compiler/data/src-file.h
compiler/gentree.cpp
compiler/pipes/collect-required-and-classes.cpp
compiler/vertex-desc.json
functions.txt
functions_spl.txt
functions_uberh3.txt

Just as before, we specify a path to a **root** `functions.txt` file.
That file can make a `require_once()` call to another file that
will be processed as a part of builtin declarations.
We achieve this behavior by marking the root functions file with
a flag `is_from_functions_file`. Then, every file required from
it will inherit that flag. `file->is_builtin()` will respect that flag.
This change is motivated not only by a need to logically separate the
definitions, but also to make it possible to move some declarations
to another namespace. For example, FFI-related `CData` class should
be declared in `FFI` namespace (`\FFI\CData`).
This is required to make our implementation (#295) closer to the PHP implementation.
I only did a minimal separation for now as a proof of concept.
We can …

make it possible to split functions.txt into separate files

---

runtime/url.cpp
tests/phpt/dl/481_parse_str_with_empty_string.php

Before:
```
array(1) {
[""]=>
string(0) ""
}
```
After:
```
array(0) {
}
```

fixed `parse_str` behavior with empty or `null` string

---

runtime/allocator.cpp
runtime/allocator.h
runtime/array.inl
runtime/instance-cache.cpp
runtime/instance-copy-processor.h
server/job-workers/job-worker-server.cpp

Most likely, SIGSEGV happened because some signal interrupted execution at the moment, when allocator was replaced to a shared memory resourse
relates to `KPHP-1349`

Try to fix SIGSEGV in job workers

---

runtime/tl/tl_builtins.h

fix SIGSEGV on TL Dictionary keys serialization in case of numeric strings

---

runtime/url.cpp
tests/phpt/dl/481_parse_str_with_empty_string.php

Function returns an empty array, not `null` if the string is empty, and also if it consists of whitespace characters,

fixed `parse_str` behavior

---

net/net-reactor.cpp
server/job-workers/job-worker-server.cpp
server/job-workers/job-worker-server.h

The main idea is to enable `EPOLLONESHOT` flag for fd we read new jobs from and rearm it only when job is already served.
relates to `KPHP-1353`

Prevent job workers from waking up on new job while another one is running

---

runtime/bcmath.cpp
tests/phpt/dl/483_bcmath.php

bcmath currently able to return numbers like -0, -0.0 etc. This behavior was fixed in php 7.4.23, 8.0.10, see https://bugs.php.net/bug.php?id=78238 for more details.

forbid bcmath to return negative zero numbers

---

tests/phpt/phc/codegen/long_opeq.php

After migrating to c++17 standard this test start failing. The reason is that prior c++17 evaluation order is unspecified, so compiler may call any functions. Thus fixating such order in test was a mistake.
But in c++17 [evaluation order](https://en.cppreference.com/w/cpp/language/eval_order) became more strict, and particularly in case of long_opeq.php test this order is determined.

fix long_opeq.php test

---

compiler/make/make.cpp

This happened after splitting custom make on pre make + compiling + linking

fix that ctrl+c stopped working on compilation stage

---

compiler/pipes/final-check.cpp
functions.txt
runtime/ffi.h
tests/phpt/ffi/typing/052_string_arg_error.php
tests/python/tests/ffi/php/util/string.php
tests/python/tests/ffi/test_ffi.py

PHP has 2 forms of that call:
1. With explicit length
2. Without explicit length
For (2) it requires the CData ptr to be `char*` or `const char*` (checked).
It also expects it to be null-terminated (unchecked).
If passed CData would be something incompatible, it gives a run time error.
KPHP would give a compile-time error for (2) function form.
For (1) both PHP and KPHP won't perform any type checking.
Refs #343

implemented `FFI::string()` function

---

compiler/pipes/inline-defines-usages.cpp
functions.txt
tests/phpt/constants/001_undefined.php

In `functions.txt`:
- Added missing `PHP_INT_MIN`
- Added `TODO`, `TODO_OVERLOAD` placeholder constants
- Renamed `INT_MIN` and `INT_MAX` with `PHP_INT_MIN` and `PHP_INT_MAX`
Example:
```
Compilation error at stage: Inline defines pass, gen by inline-defines-usages.cpp:37
test.php:18  in foo
echo UNDEFINED_CONSTANT;
Undefined constant 'UNDEFINED_CONSTANT'
```
Fixes #238

added compile-time error about undefined constant

---

compiler/code-gen/declarations.cpp
runtime/instance-copy-processor.h
runtime/job-workers/job-interface.h
runtime/refcountable_php_classes.h
tests/python/tests/job_workers/php/SharedMemoryPieceCopying/JobRequest.php
tests/python/tests/job_workers/php/SharedMemoryPieceCopying/JobResponse.php
tests/python/tests/job_workers/php/SharedMemoryPieceCopying/SharedMemoryContext.php
tests/python/tests/job_workers/php/SharedMemoryPieceCopying/SomeContext.php
tests/python/tests/job_workers/php/SharedMemoryPieceCopying/http_worker.php
tests/python/tests/job_workers/php/SharedMemoryPieceCopying/job_worker.php
tests/python/tests/job_workers/php/http_worker.php
tests/python/tests/job_workers/php/job_worker.php
tests/python/tests/job_workers/test_job_shared_immutable_message.py

Now we use `std::unordered_map` instead of updating additional `unique_index_` member to track such references. It prevents data races when copying of shared memory is performed simultaneously from several processes.
relates to `KPHP-1399`

Rework tracking references to the same instances on copying 

---

runtime/array.inl
runtime/array_decl.inl

This allow avoid multiple instantiation of same template function, but with different amount of args in it. Such approach may compiles faster.

use c++17 fold expression instead of variadic template recursive call

---

runtime/datetime.cpp

Reverts VKCOM/kphp#341
Reverted due to failures of 484_strftime on 29th February.
The problem needs to be revisited.

Revert "fixed gmmktime function work"

---

runtime/string.inl
tests/kphp_tester.py
tests/phpt/migration_php8/009_blank_no_warning.php

Fixed behavior when an empty string was considered a valid number, which led
to incorrect runtime warnings about the difference in behavior between PHP 7
and 8.
Added a new type of test `@kphp_runtime_should_not_warn` for tests that need to
make sure that the code in it does not generate warnings at runtime.

fixed `string::try_to_float_as_php8` function

---

runtime/zstd.cpp
tests/phpt/zstd/1_compress.php

php zstd 0.11.0 version starts to compress at zero level as described [here](https://pecl.php.net/package-info.php?package=zstd&version=0.11.0). This PR changed kphp behavior in same way.

zstd now compress at zero level

---

common/wrappers/overloaded.h
runtime/net_events.cpp
server/php-engine.cpp
server/php-queries.cpp
server/php-queries.h
server/php-worker.cpp

Before this PR, `std::variant` behavior was emulated via non-standard gcc extension -- [anonymous aggregate](https://gcc.gnu.org/onlinedocs/gcc/Unnamed-Fields.html). It's not allowed to have field of type with user-defined constructor in anonymous aggregates, which prevents making code be more like C++, than C.
This PR fixes the issue.

Use `std::variant` in `net_events` and `net_queries` instead of self-made union based struct

---

common/tl/tl.cmake

Move *.tl files located in vk-tl-tools package from /usr/share/vkontakte/tl-files/ to /usr/share/vkontakte/doc/tl-files/ to avoid conflict with other packages

avoid conflict with vk-tl-tool package

---

Dockerfile
common/tl/tl.cmake
docs/kphp-basics/installation.md

Move *.tl files located in vk-tl-tools package from /usr/share/vkontakte/doc/tl-files/ to /usr/share/vkontakte/examples/tl-files/ to avoid conflict with other packages.

avoid conflict with vk-tl-package

---

builtin-functions/_functions.txt
tests/python/tests/instance_cache/php/index.php

PR removes cast operator (:::) from instance_cache api. After patch calls with incorrect typing won't compile anymore. e.g. code:
```/** @kphp-immutable-class */
class A {
public int $x = 0;
}
instance_cache_store("key", new A, 'wtf');
```
Produce next error:
```Compilation error at stage: Calc actual calls, gen by type-inferer.cpp:53
demo.php:29  in global scope
instance_cache_store("key", new A, 'wtf');
pass string to argument $ttl of instance_cache_store
but it's declared as @param int
demo.php:29  in global scope
instance_cache_store("key", new A, 'wtf');
"wtf" is string
Compilation terminated due to errors```

introduce strict typing in instance_cache api

---

compiler/inferring/restriction-isset.cpp
tests/phpt/dl/1032_instance_can_be_null.php
tests/phpt/dl/1033_string_cant_be_null.php

Currently, such code:
```
<?php
class A{}
$arr = ["foo" => new A];
$obj = $arr["bar"];
if (isset($obj)) {
echo "smth";
}
```
Produce next compilation error:
```
Compilation error at stage: Infer types, gen by type-inferer.cpp:53
demo.php:8  in global scope
if (isset($obj)) {
isset, !==, ===, is_array or similar function result may differ from PHP
Probably, this happened because ExprNode $arr[.] at demo.php:6  in global scope : A can't be null in KPHP, while it can be in PHP
Chain of assignments:
ExprNode $obj at demo.php:8  in global scope : A
VarNode ($obj in global scope) : A
ExprNode $arr[.] at demo.php:6  in global scope : A
Compilation terminated due to errors
```
However, class instance can be null. PR fix this issue.

fix class instance can't be null issue

---

compiler/const-manipulations.h
tests/phpt/dl/1010_const_vars.php

This PR add support of array indexing inside const expression like:
```
class A {
const ARR = [1, 2, 3];
const ELEM = self::ARR[0];
}
```

add support of array indexing inside const expression

---

compiler/code-gen/files/type-tagger.cpp
compiler/code-gen/files/type-tagger.h

Currently autogenerated _tagger.cpp file consists of 3 quite big parts:
```
template<>
int Storage::tagger<Foo>::get_tag()  noexcept {
return -1717182174;
}
// tons of similar get_tag()
template<typename T>
typename Storage::loader<T>::loader_fun Storage::loader<T>::get_function(int tag) noexcept {
switch(tag){
case -2043716967: return Storage::load_implementation_helper<Foo, T>::load;
// tons of similar cases
}
php_assert(0);
}
auto unused_loaders_list __attribute__((unused)) = {
(void*)(Storage::loader<class_instance<C$A>>::get_function),
// tons of similar instantiations
};
```
So, it can be compiled as only one translation unit. This PR split _tagger.cpp into _tagger.cpp, but now containing only fist part of code (with get_tag() specializations), _loader.h with second part of code …

speed up tagger.cpp compilation

---

compiler/compiler-settings.cpp
compiler/make/cpp-to-obj-target.h
compiler/make/h-to-pch-target.h
compiler/make/make.cpp
compiler/make/target.h

Prior to this PR, we had this logic for pch generation:
1) generate kphp_out/objs/runtime-headers.h.gch.{flags}
2) move this file to /tmp/kphp_gch/{runtime_sha}/{flags}/runtime-headers.h.gch
3) copy runtime-headers.h nearby
With this PR, the logic changes to the following:
1) generate kphp_out/objs/pch_{flags}/ with arbitrary contents
2) move this dir to /tmp/kphp_gch/{runtime_sha}/{flags}/*
3) copy runtime-headers.h nearby
The reason behind this change is nocc — an internal tool for remote C++ compilation (like distcc) that will be open sourced some time later.
nocc will NOT compile pch locally — instead, it will compile pch remotely on demand. It does NOT emit runtime-headers.h.gch file locally — it emits runtime-headers.h.nocc-pch file INSTEAD OF .gch. 
In other words, this patch makes …

refactor pch target for nocc support

---

compiler/compiler-settings.cpp
compiler/compiler-settings.h
compiler/kphp2cpp.cpp
compiler/make/objs-to-bin-target.h
compiler/make/objs-to-obj-target.h

Prior this patch partial linking performed with hardcoded "ld", which works quite slowly.
After patch, linking will performed indirectly through compiler, and compiler may choose linker from special directory. Clang and gcc allow to specify such directory through "-B" option. At kphp level such dir may be specified through new "--compiler-toolchain-dir" cli option.

use default linker for partial linking

---

runtime/instance-to-array-processor.h

This refactoring mostly consists of DRY `instance_to_array()` implementation and removing recuring of variadic templates for tuple processing. The last one allow to reduce number of `process_tuple()` instantiations, e.g. for:
```
<?php
class A {
/** @var tuple(int, string, bool) $t */
public $t;
}
$arr = instance_to_array(new A);
var_dump($arr);
```
there was four instantiations:
while after only one:

refactoring instance_to_array()

---

tests/kphp_ci_pipeline_runner.py
vkext/vkext-schema-memcache.cpp
vkext/vkext.cmake

[vkext] return empty array instead of false in `rpc_tl_query` and `typed_rpc_tl_query`

---

compiler/code-gen/files/init-scripts.cpp
compiler/code-gen/files/shape-keys.cpp
compiler/code-gen/files/shape-keys.h
compiler/compiler.cmake
compiler/gentree.cpp
compiler/phpdoc.cpp
compiler/pipes/code-gen.cpp
compiler/type-hint.cpp
compiler/type-hint.h
runtime/shape.h
runtime/to-array-processor.h
tests/phpt/dl/1034_to_array_debug_shape.php
tests/phpt/dl/1036_to_array_debug_shape_nullable.php
tests/phpt/instance_cache/1_instance_cache.php
tests/phpt/shapes/019_shape_to_array.php

Currently, to_array_debug() print just index of key for 'shape' instead of real string name. After this PR it will be real string keys.

to_array_debug() now able to print shape keys

---

compiler/code-gen/files/type-tagger.cpp

Currently pch in not used in _loader_instantiations{i}.cpp translation units, because corresponding `#include` directive should be first in file.

enable using pch in _loader_instantiations{i}.cpp translation units

---

common/dl-utils-lite.cpp
server/php-master.cpp

Here are several small enhancements:
- improved `dl_passert` logging to make `perror` message available in sentry
- softer error handling in several places in master process (relates to `KPHP-1350`)
- more detailed logging on fork errors

Improved error handling in master process

---

compiler/pipes/final-check.cpp
tests/phpt/fork/030_fail_pass_resumable_lambda_to_builtin_function.php
tests/phpt/fork/031_ok_pass_fork_unreachable_resumable_lambda_to_builtin_function.php

Any lambda passed from client code is potentially resumable. Therefore any builtin function accepting lambda as a parameter (for example `array_map`, `array_filter`, `sort` etc.) must be resumable too and correctly behave when this lambda suspends.
Now, all such builtin function doesn't maintain case when passed resumable lambda suspends. It leads to critical error in runtime and unpredictable worker crashes.
Making all such builtin functions resumable will significantly increase code complexity and extensibility and seems not very useful. Therefore, in this PR it's suggested to forbid such cases in compiler.

Forbid to pass resumable lambdas to builtin functions

---

runtime/comparison_operators.inl
tests/phpt/dl/1034_array_lt.php

Such code: `[2, 1] < [1, 2]` says that first array less than second, while it don't.
This lead to e.g. incorrect sorting of such array:
```
$arr = [[3, 6], [3, 4], [1, 10], [3, 5], [6, 2], [1, 3]];
sort($arr);
print_r($arr);
// PHP:  [[1, 3], [1, 10], [3, 4], [3, 5], [3, 6], [6, 2]]
// KPHP: [[1, 3], [3, 4], [3, 5], [3, 6], [6, 2], [1, 10]]
```

fix bug in less than array operator

---

compiler/gentree.cpp
compiler/pipes/generate-virtual-methods.cpp
compiler/pipes/parse-and-apply-phpdoc.cpp
tests/phpt/class_inheritance/049_deligating_constructor_kphp_infer.php
tests/phpt/interfaces/signature_compatibility/callable_inherit_error.php
tests/phpt/interfaces/signature_compatibility/callable_inherit_ok.php
tests/phpt/interfaces/signature_compatibility/iface_return_derived.php
tests/phpt/interfaces/signature_compatibility/multi_level_doc_inherit.php
tests/phpt/phpdocs/027_type_hints_with_phpdocs.php
tests/phpt/phpdocs/101_typehint_doc_mismatch_1.php
tests/phpt/phpdocs/102_typehint_doc_mismatch_2.php
tests/phpt/phpdocs/103_typehint_doc_mismatch_3.php
tests/phpt/phpdocs/104_typehint_doc_mismatch_4.php
tests/phpt/typehints/return_types/15_for_assumption.php

Now we deal better with situations like
1) Inherit phpdoc from parent when necessary. For example:
```
interface I {
/**
* @param callable(IData):IData $cb
*/
function callAndShow(callable $cb);
}
class Work implements I {
// inherit a typed callable from I, don't turn this function into a template one
function callAndShow(callable $cb) {
}
}
```
2) Multi-level inheritance and phpdoc discovery throughout all ancestors
3) I've added a check and some tests that phpdoc matches type hint, to fire an error for code like this:
```
/** @return tuple(int, string) */
function f(): array { ... }
```
But finally I had to comment out this check, as vkcom has tons of mismatches (moslty having @return mixed, but :primitive type hint). Tests for this are marked with '@todo' since they don't pass until …

better behavior on phpdoc inheritance and "phpdoc + type hint" combinations

---

common/tl/methods/string.h

Without `decay_t<T>` it couldn't map `vk::tl::storer<std::vector<T> &>`, `vk::tl::storer<std::vector<T> &&>`, `vk::tl::storer<const std::vector<T> &>` etc to actual `vk::tl::storer<std::vector<T>>` explicit specializtation

[common/tl] fix type deducing at `vk::tl::store_to_buffer`

---

common/algorithms/hashes.h
compiler/class-assumptions.cpp
compiler/data/class-data.cpp
compiler/data/class-data.h
compiler/data/class-members.cpp
compiler/data/class-members.h
compiler/data/data_ptr.h
compiler/data/function-data.h
compiler/data/generics-mixins.cpp
compiler/data/generics-mixins.h
compiler/gentree.cpp
compiler/gentree.h
compiler/inferring/type-hint-recalc.cpp
compiler/lambda-utils.cpp
compiler/lexer.cpp
compiler/lexer.h
compiler/phpdoc.cpp
compiler/phpdoc.h
compiler/pipes/calc-locations.cpp
compiler/pipes/check-classes.cpp
compiler/pipes/check-tl-classes.cpp
compiler/pipes/collect-required-and-classes.cpp
compiler/pipes/parse-and-apply-phpdoc.cpp
compiler/pipes/register-ffi-scopes.cpp
compiler/pipes/resolve-self-static-parent.cpp
compiler/pipes/sort-and-inherit-classes.cpp
compiler/pipes/split-switch.cpp
compiler/vertex-desc.json
tests/cpp/compiler/phpdoc-test.cpp

There are three main purposes of this PR.
For functions, classes, fields, vars, etc. we now store `const PhpDocComment *phpdoc` instead of `vk::string_view phpdoc_str`.
Storing a meaningful object instead of a string is much more reliable, since we use methods like `phpdoc->has_tag(type)` instead of `phpdoc_tag_exists(phpdoc_str, type)`. 
Phpdoc comment is now parsed in gentree — it's split in tags, these tags are kept in `forward_list`. But the values of tags are analyzed later in the pipeline on demand.
When we stored `vk::string_view`, every time we had to access it like `phpdoc_tag_exists` / `phpdoc_parse_var_and_type_name` / etc. — at first we parsed `phpdoc_str`, when we did an actual query. Some doc comments were parsed more than once. Now they all are parsed exactly once in …

speedup phpdoc parsing and store PhpDocComment instead of phpdoc_str

---

common/resolver.cpp
common/server/statsd-client.cpp
common/server/tl-stats-t.h
common/stats/provider.h
server/php-engine.cpp
server/php-master.cpp
server/server-stats.cpp
server/server.cmake
server/statshouse/add-metrics-batch.cpp
server/statshouse/add-metrics-batch.h
server/statshouse/statshouse-client.cpp
server/statshouse/statshouse-client.h
server/statshouse/worker-stats-buffer.cpp
server/statshouse/worker-stats-buffer.h

sending raw stats to statshouse

---

compiler/pipes/collect-required-and-classes.cpp
tests/phpt/cl/030_resolve_from_phpdoc.php

If a class is used in @var and is not created actually,
```
/** @var ?A\B\SomeClass $obj */
$obj = null;
if ($obj) $obj->someMethod();
```
— now becomes visible to KPHP.
Before, KPHP didn't collect such classes. `if (0) new A\B\SomeClass` could help in that case.

Collect classes from @var phpdocs if they are unreachable from php code

---

compiler/compiler-core.cpp
compiler/compiler-settings.h
compiler/composer.cpp
compiler/composer.h
compiler/kphp2cpp.cpp
docs/kphp-language/kphp-vs-php/compiler-cmd-options.md
tests/python/tests/composer/test_composer.py

How `autoload.files` behaved before:
All vendored packages, direct and indirect dependencies
were traversed. composer.json files that were found
and scanned. Every autoload.files key was added to
the must-require file list. --composer-no-dev had
no effect on this as it only works with autoload-dev
section of the root composer file.
This lead to a problem: if there is are dev-only dependencies,
could be incompatible with KPHP. phpstorm, composer itself and
many other PHP packages that use too much runtime magic.
If they happen to have some `autoload.files` among them, our
project will stop to build even if `--composer-no-dev` is specified.
How `autoload.files` behaves now:
We start from collecting the dependencies list ("composer.require").
This operation is performed only for a root …

[compiler] improve composer autoload files handling

---

compiler/pipes/register-ffi-scopes.cpp
tests/python/tests/ffi/c/pointers.c
tests/python/tests/ffi/c/pointers.h
tests/python/tests/ffi/php/pointer/ptr2.php
tests/python/tests/ffi/test_ffi.py

Previously, we used empty string as a param name.
If there are multiple unnamed params, we'll end up with duplicated
param names with potentially different type hints.
This patch assigns autogenerated names, like `_unnamed_param1`
to these parameters, avoiding the collision error.
Also enabled one of the FFI tests from pointers;
it was intended to be enabled, but perhaps I forgot
to add it to the python script previously (?)
Fixes #424

[compiler] assign autogenerated names for unnamed ffi func args

---

compiler/code-gen/vertex-compiler.cpp

Such code:
```
function do_switch($condition, $case) {
switch ($condition) {
case $case:
return 'case';
default:
return 'default';
}
}
```
in master will be transpiled to:
```
//source = [demo.php]
//3: function do_switch($condition, $case) {
string f$do_switch(int64_t v$condition, int64_t v$case) noexcept  {
mixed v$condition_on_switch$uddfb36cd3d43ebe6_0;
bool v$matched_with_one_case$uddfb36cd3d43ebe6_0 = false;
//4:   switch ($condition) {
do {
v$condition_on_switch$uddfb36cd3d43ebe6_0 = v$condition;
v$matched_with_one_case$uddfb36cd3d43ebe6_0 = false;
//5:     case $case:
if (v$matched_with_one_case$uddfb36cd3d43ebe6_0 || eq2(v$condition_on_switch$uddfb36cd3d43ebe6_0, v$case)){
v$matched_with_one_case$uddfb36cd3d43ebe6_0 = true;
//6:       return 'case';
return …
```

avoid goto statement in autogenerated code for simple switch

---

common/algorithms/adjacent_find.h
common/algorithms/lower_bound.h
common/algorithms/sort.h
common/algorithms/stable_sort.h
common/algorithms/upper_bound.h
common/smart_iterators/transform_iterator.h
common/tl/store.h
common/wrappers/iterator_range.h
runtime/array_functions.h

- std::result_of replaced with std::invoke_result because result_of was deprecated in cpp 17

Improved cpp17 support

---

compiler/code-gen/vertex-compiler.cpp
compiler/inferring/type-data.cpp
compiler/inferring/type-data.h
compiler/inferring/type-hint-recalc.cpp
compiler/phpdoc.cpp
compiler/pipes/final-check.cpp
docs/kphp-language/php-extensions/ffi.md
runtime/ffi.h
tests/phpt/ffi/typing/010_cstr_field_read_error.php
tests/phpt/ffi/typing/054_const_ptr_error.php
tests/phpt/ffi/typing/055_const_ptr_error.php
tests/phpt/ffi/typing/056_const_ptr_error.php
tests/python/tests/ffi/c/pointers.c
tests/python/tests/ffi/c/pointers.h
tests/python/tests/ffi/php/pointer/cast.php
tests/python/tests/ffi/php/pointer/ptr2.php

* Fix compiler crash when simple instance type T was mixed
with a FFI pointer type
* Keep pointer constness inside TypeData,
Make `const T*` -> `T*` a type error (previously it failed
on g++ compilation phase)
* Make `T*` -> `const T*` conversion legal
* Fix typo in FFI docs
* Add `ffi_cdata<C, builtin_type>` example
Fixes #459
Fixes #362
Fixes #357

[compiler] improve FFI pointer typing

---

runtime/json-functions.cpp
runtime/json-functions.h
tests/benchmarks/BenchmarkJson.php
tests/phpt/json/encoder_warnings.php

This change allows json_encode functions to report
errors in a more helpful way.
json_encode(['a' => ['b' => INF]])
old message: strange double inf in function json_encode
new message: /['a']['b']: strange double inf in function json_encode
This is helpful if json_encode is called with various data
from multiple places. With precise object path hint, users
can fix their code easier.
The performance impact is small (~1.35% for the worst case):
name                   old time/op  new time/op  delta
Json::EncodeSafeArray  1.52µs ± 1%  1.54µs ± 1%  +1.35%
This is due to the fact that vector/map loop is now split into
two parts, reducing the redundant branching. Without this optimization,
code becomes ~8% slower. It comes with a little bit of code duplication.
The object path stack is a fixed …

[runtime] add JSON encoding error object path

---

.github/workflows/Dockerfile.buster
.github/workflows/Dockerfile.focal
CMakeLists.txt
builtin-functions/_functions.txt
cmake/init-global-vars.cmake
compiler/compiler-settings.cpp
docs/kphp-internals/developing-and-extending-kphp/compiling-kphp-from-sources.md
runtime/interface.cpp
runtime/interface.h
runtime/runtime.cmake
server/numa-configuration.cpp
server/numa-configuration.h
server/php-engine.cpp
server/php-master.cpp
server/server.cmake

Here're 2 new options for kphp server:
- `--numa-node-to-bind '0: 0-7, 12-28'`
- `--numa-memory-policy bind`
Given these options, kphp master process will distribute workers among specified numa nodes, binding them to the corresponding CPU ranges and setting specified memory policy for them.
Implementation is based on [libnuma](https://manpages.debian.org/testing/libnuma-dev/numa.3.en.html).

NUMA and CPU affinity

---

server/http-server-context.cpp
server/http-server-context.h
server/php-engine-vars.cpp
server/php-engine-vars.h
server/php-engine.cpp
server/php-master-restart.cpp
server/php-master-restart.h
server/php-master.cpp
server/php-master.h
server/server.cmake
tests/python/lib/kphp_server.py
tests/python/tests/http_server/php/index.php
tests/python/tests/http_server/test_multiple_http_ports.py

This change allows to pass several HTTP ports on server start. Master process will create listening socket for every port on start and then distribute each socket for each worker uniformly.
Graceful restart for several sockets is supported too. On graceful restart old master sends all corresponding open file descriptors to new master via unix socket with help of [SCM_RIGHTS](https://man7.org/linux/man-pages/man3/cmsg.3.html).

Multiple listening HTTP sockets

---

builtin-functions/_functions.txt
runtime/kphp_core.h
tests/phpt/memory_usage/9_memory_allocs.php

memory_get_allocations returns a tuple of `(num_allocations, memory_allocated)`.
The benefit of this function is that it can be used to
measure the allocations between two execution points:
how many allocations happened and how much memory we allocated.
[$old_num_allocs, $old_mem_allocated] = memory_get_allocations();
do_something();
[$new_num_allocs, $new_mem_allocated] = memory_get_allocations();
$num_allocs = $new_num_allocs - $old_num_allocs;
$mem_allocated = $new_mem_allocated - $old_mem_allocated;
This is especially useful in benchmarking (see ktest bench).
Since it returns a tuple instead of array,
it doesn't do any heap allocations on its own

add memory_get_allocations builtin KPHP function

---

compiler/code-gen/declarations.cpp
compiler/code-gen/vertex-compiler.cpp
runtime/memcache.h

484f63a commit allow kphp to mark virtual functions that override one from base class with `final` keyword.
78e355f commit fix problem caused by `goto` usage. Imagine this code:
```
int main() {
int a =0;
goto exit;
int *b = nullptr;
exit:
return 0;
}
```
This code violate C++11 §6.7/3:
> It is possible to transfer into a block, but not in a way that bypasses declarations with initialization. A program that jumps from a point where a variable with automatic storage duration is not in scope to a point where it is in scope is ill-formed unless the variable has scalar type, class type with a trivial default constructor and a trivial destructor, a cv-qualified version of one of these types, or an array of one of the preceding types and is declared without an initializer (8.5).
In order to fix …

several fixes caused by compiling vkcom with clang++-11 

---

common/php-functions.h
compiler/code-gen/vertex-compiler.cpp
runtime/string.inl
tests/phpt/regress/issue487/test.php
tests/phpt/regress/issue489/test.php

* When compiling a switch, don't apply a string-only-cases
optimization if any of the constant strings look like
something that can be interpreted as a numeric string by PHP;
this would lead to unexpected results like `" 1"` being matched
by PHP with `case "1"`, but rejected by KPHP
* For string::to_int, that is supposed to implement `(int)$x` as
well as `intval($x)` where `$x` is string-typed, skip leading
whitespace to be consistent with PHP behavior
Fixes #487
Fixes #489

[compiler,runtime] fix intval() related issues

---

builtin-functions/_functions.txt
compiler/gentree.cpp
compiler/pipes/check-func-calls-and-vararg.cpp
compiler/pipes/check-func-calls-and-vararg.h
runtime/exception.cpp
runtime/exception.h
tests/phpt/cl/197_compile_time_location.php
tests/phpt/cl/Classes/NamespaceTester.php

`CompileTimeLocation` introduces an ability to access a location of a caller inside a called function.
In other words, from `function f()` body, now it's available have an exact place, where `f()` was called from.
For example, we want to implement `log_info($message)`, to be used like this
```
log_info("start calculation");
$arr = [1,2,3,4,5];
foreach ($arr as $v) {
if ($v > 3) 
log_info("big v=$v");
}
log_info("end calculation");
```
which would print a text log like
```
start calculation (in demo5 at dev.php:55)
big v=4 (in demo5 at dev.php:59)
big v=5 (in demo5 at dev.php:59)
end calculation (in demo5 at dev.php:61)
```
**Before this MR, it was impossible to achieve this.**
Now, `log_info()` can be implemented and looks quite trivial:
```
function log_info(string $message, …
```

implement CompileTimeLocation (a parameter auto-filled on call side)

---

.idea/misc.xml
docs/kphp-internals/kphp-architecture/internals-compiler.md
tests/kphp_ci_pipeline_runner.py
tests/kphp_tester.py
tests/python/lib/file_utils.py
tests/python/lib/kphp_builder.py
tests/python/lib/kphp_run_once.py
tests/python/lib/nocc_for_kphp_tester.py
tests/python/lib/testcase.py
tests/python/tests/ffi/test_ffi.py
tests/python/tests/instance_cache/test_store_fetch_delete.py

After merging this PR, nocc (instead of distcc) will be used to run kphp tests 
1) in vk.com private infrastructure 
2) when using `kphp-tester.py`
All changes to kphp-dockerfiles have already been made.
After merging, some changes in teamcity configuration calling `kphp_ci_pipeline_runner.py` would also be needed.

use nocc for kphp tests, drop distcc

---

compiler/ffi/c_parser/parsing_driver.cpp
compiler/pipes/final-check.cpp
runtime/ffi.h
tests/python/tests/ffi/c/pointers.c
tests/python/tests/ffi/c/pointers.h
tests/python/tests/ffi/php/pointer/null_as_ptr.php
tests/python/tests/ffi/php/pointer/ptr2.php

Here is an example:
typedef void *VoidPtr;
void f(VoidPtr *x);
`x` type should be a pointer with elem type of `void` and `num`:
Pointer{Elem: Void, Num: 2}
But before this patch, we generated this:
Pointer{Elem: Pointer{Elem: Void, Num: 1}, Num: 1}
This caused the typechecker to treat these two as incompatible:
VoidPtr* vs void**
This patch also includes a fix that makes all `T*` compatible with `const T*`.

[compiler] merge typedefed pointers with external pointers

---

builtin-functions/_functions.txt
compiler/pipes/check-func-calls-and-vararg.cpp
compiler/pipes/check-func-calls-and-vararg.h
runtime/datetime.cpp
runtime/datetime.h
tests/phpt/func_specializations/hrtime.php
tests/phpt/func_specializations/hrtime_error1.php
tests/phpt/func_specializations/hrtime_error2.php
tests/phpt/func_specializations/microtime.php
tests/phpt/func_specializations/microtime_error1.php
tests/phpt/func_specializations/microtime_error2.php

This is a port of #251 PR without more problematic regexp
function specializations and refactoring.
preg functions will be ported separately as they require
more unrelated changes to be applied.
In addition to microtime, this patch includes hrtime which
is now generally available as KPHP min PHP version is 7.4 now.
microtime() -> microtime_string()
microtime(false) -> microtime_string()
microtime(true) -> microtime_float()
hrtime() -> hrtime_array()
hrtime(false) -> hrtime_array()
hrtime(true) -> hrtime_int()
The main idea is to get less mixed-typed values in the code
that uses functions those return value type depends on its arguments.

[compiler] add hrtime() and microtime() specializations

---

runtime/regexp.cpp
runtime/regexp.h

Also used a while loop instead of `do while`.
The extra offset+1 is performed at the call site, since it
has nothing to do with utf8 subsequent bytes.
This is a part of many patches that we need to apply to make
regexp code at least a little bit more maintainable.

[runtime] move 0xc0+0x80 utf8 to a separate method + add a comment

---

tests/python/lib/kphp_run_once.py

When running tests in GitHub actions, we can't normally download
the artifacts that would include PHP-vs-KPHP diff or other
useful output to debug what's going wrong.
We already have `GITHUB_ACTIONS` environment set to 1 when
running the tests there, so we can print relevant info to stdout
when running under GitHub actions.

print more info to stdout when running tests under GitHub actions

---

common/binlog/binlog-buffer-aio.cpp

Here's a fix for the case when binlog rotation related `LEV_ROTATE_TO` event is processed before new binlog arrived to the server.
Before these changes, such a case led to loss of all events from new binlog.
Now in this case server will wait new binlog for 120 sec.

[binlog] wait not existing binlog instead of error after LEV_ROTATE_TO processing

---

compiler/pipes/final-check.cpp
runtime/interface.cpp
runtime/interface.h
server/php-queries.cpp
server/php-queries.h
server/php-runner.cpp
server/php-runner.h
tests/phpt/shutdown_functions/throw_error1.php
tests/phpt/shutdown_functions/throw_error2.php
tests/phpt/shutdown_functions/throw_error3.php
tests/python/tests/shutdown_functions/php/index.php
tests/python/tests/shutdown_functions/test_shutdown_functions.py
tests/python/tests/shutdown_functions/test_shutdown_functions_errors.py
tests/python/tests/shutdown_functions/test_shutdown_functions_exceptions.py
tests/python/tests/shutdown_functions/test_shutdown_functions_timeouts.py

This is an alternative implementation that implements shutdown functions during the timeout in the script context.
See also: #517 
----
The most challenging part is that timeout is catched in a signal
handler of the running coroutine (run_context) which then
changes the state of the worker and switches the context to exit_context.
Running the shutdown handlers inside the run_context before switching it
is dangerous as arbitrary PHP code is not guaranteed to be safe for
the signal handling context.
If we run these shutdown handlers inside of the worker context,
we may suffer from the `exit()` calls done inside of the shutdown
functions that may cause us to attempt switching the context again
and entering a `finished` state instead of the `error` state we were in.
As a solution to this …

[runtime] make shutdown funcs called even after a timeout

---

builtin-functions/_functions.txt
runtime/regexp.h
tests/phpt/regexp/005_regexp_match2.php

Also add missing `$offset` parameter for mixed-typed pattern
parameter of `preg_match` function.
Fixes #546

[runtime] permit `$offset` argument of `preg_match_all`

---

server/php-engine.cpp

Previously, we were adding `argv[0]` twice when KPHP runs
a server in once mode (`-o`) or when we're running a cli script.
Once of the solutions is to re-organize the way we parse command-line
arguments so there is never such a situation where adding something
excessive is never an option. Another approach is to memorize and/or
recognize when we don't need to add this default argument anymore.
This PR implements the latter approach as it requires less changes
and fixed the issue.
Fixes #533

[runtime] fix argv[0] handling for server `-o` and cli modes

---

runtime/files.cpp
tests/phpt/dl/473_file.php

Remove hidden limit in function fgets when parameter is -1 and set it to size of file

[runtime] Remove hidden limit in fgets

---

server/php-runner.cpp
server/php-runner.h

There are 2 situations when timeout timer is reset:
1. When shutdown functions are being executed before
the timeout timer triggered
2. When timeout timer already triggered and we're running
shutdown functions from the timeout context
For (2), we start from the SIGALRM handler and set `tl_flag` to `true`.
This meant that any attempt to do a TL RPC request would cause
a script to forcefully enter the timeout state.
We used `php_script_set_timeout` function to reset the timer in both
cases. It has a side effect of setting `tl_flag` to `false`.
This made it possible to enter the unexpected state when timeout
is already happened, but `tl_flag` is false instead of true.
While it could be useful to run TL RPC queries after the timeout
inside shutdown functions, we need to fix the worker …

[runtime] preserve tl_flag value when resetting the timeout timer

---

common/tl2php/gen-php-code.cpp
common/tl2php/php-classes.cpp

[tl2php] generate `|null` for classes in PHP docs if needed

---

runtime/files.cpp

To suppress error like this:
```
==14436==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7f0c2e199118 at pc 0x0000008c7fbd bp 0x7f0c2e199070 sp 0x7f0c2e199060
READ of size 4 at 0x7f0c2e199118 thread T0
#0 0x8c7fbc in file_file_get_contents(string const&) /home/kitten/kphp/runtime/files.cpp:837
...
```
Warning appeared after https://github.com/VKCOM/kphp/pull/537
Spent too much time to find out the key reason of the asan warning. Will be treated as false-positive.

Suppress ASAN warning for g++ 10.3.0

---

common/tl-files/common.tl
common/tl/constants/engine.h
server/php-master-tl-handlers.cpp

It will be useful for tests that use RPC

maintain RPC `engine.sleep` query via master port

---

tests/python/lib/kphp_server.py
tests/python/tests/curl/test_curl.py

**Test refactoring**
Changing the default number of workers for python tests for greater clarity

[tests] change default server option to one worker

---

runtime/common_template_instantiations.cpp
runtime/common_template_instantiations.h

https://github.com/VKCOM/kphp/pull/537 breaks `@kphp-flatten` optimization for `array<double>` in ML related functions.
As it's explicitly instantiated in runtime sources it's compiled with `-O3` instead of `-Os`.
It spoils inlining of `array<double>::get_value` functions called from `@kphp-flatten` annotated ML related functions:
some strange `call` asm instructions are generated instead of normal inlining.
This PR prevents `array<double>` from being instantiated in runtime sources and fix the problem explained above.

Fix @kphp-flatten optimization for array<double>

---

builtin-functions/_functions.txt
runtime/interface.cpp
runtime/interface.h
server/php-queries.cpp
server/php-queries.h
tests/python/lib/http_client.py
tests/python/tests/http_server/php/index.php
tests/python/tests/http_server/test_request.py

Introduction
---------------
HTTP code 103 (Early hints) informational status code indicates to the client that the server is likely to send a final response with the header fields included in the informational response.
A client can speculatively evaluate the header fields included in a 103 (Early Hints) response while waiting for the final response. For example, a client might recognize a Link header field value containing the relation type "preload" and start fetching the target resource. However, these header fields only provide hints to the client; they do not replace the header fields on the final response.
More information [here](https://datatracker.ietf.org/doc/html/rfc8297)
Implementation
--------------------
Added new function `send_http_103_early_hints($headers ::: string[]) …

add function to send 103 http code

---

compiler/pipes/resolve-self-static-parent.cpp

Should be rolled back after switching vkcom to long ID

temporary allow direct using tl _result classes for vkcom

---

builtin-functions/_functions.txt
runtime/array_functions.h
tests/phpt/array/026_array_is_list.php
tests/python/lib/file_utils.py

This function works like `array<>::is_pseudo_vector`,
but also includes a fast path for arrays that are real vectors.
In the end, it behaves like php8 `array_is_list` function,
hence it has the same name.
Refs #290

add php8 array_is_list function

---

compiler/const-manipulations.h
compiler/pipes/collect-required-and-classes.cpp
tests/phpt/dl/1038_require_vs_dirname.php
tests/phpt/dl/1039_require_vs_dirname_fails.php
tests/phpt/dl/include/bar.php
tests/phpt/dl/include/foo.php

This PR adds support of `dirname()` calls inside `require_once()`, so that both next `require_once()` calls will be equals:
```<?php
require_once dirname(__FILE__) . '/filename.php';
require_once __DIR__ . '/filename.php';
```

allow dirname() calls inside require_once()

---

compiler/compiler-core.cpp
compiler/compiler-core.h
compiler/lexer.cpp
tests/cpp/compiler/lexer-test.cpp
tests/phpt/dl/1038_leading_slash_in_constants_defines.php

Despite that we don't support namespaces yet, such code could be operated properly though:
```
var_dump(\PHP_EOL); // constants
\defined('foo'); // deidined
```

add support of leading slash in context of constants and define/defined

---

compiler/debug.cpp
compiler/keywords.gperf
compiler/lexer.cpp
compiler/phpdoc.cpp
compiler/token.h
tests/phpt/phc/parsing/primitive_casts.php
tests/phpt/phpdocs/105_bool_in_phpdoc.php
tests/phpt/phpdocs/106_boolean_in_phpdoc.php

Add support of (boolean) and (integer) cast aliases. It makes possible to write such code:
```
(boolean) $var;
(integer) $var;
```

add (boolean) and (integer) cast aliases

---

compiler/phpdoc.cpp
tests/phpt/phpdocs/028_arrays_alternative_syntax.php
tests/phpt/phpdocs/029_arrays_alternative_syntax_errors.php

add support of alternative array syntax like array<int, string>, where key type will be just ignored.

add support of alternative array syntax like array<int, string>

---

builtin-functions/_functions.txt
runtime/string_functions.cpp
runtime/string_functions.h
tests/phpt/dl/429_addslashes.php

We already have addcslashes, so having the opposite operation
does make sense. This function is useful when parsing string
literals with C-style escape sequences like `\n` etc.

add stripcslashes function

---

compiler/debug.cpp
compiler/lexer.cpp
compiler/lexer.h
compiler/token.h
tests/cpp/compiler/lexer-test.cpp
tests/phpt/dl/1038_heredoc_strip_indent.php
tests/phpt/dl/1039_heredoc_invalid_indent.php

Add support of php 7.3.0 striping indent of heredoc and nowdoc string feature: the closing identifier may be indented by space or tab, in which case the indentation will be stripped from all lines in the doc string.

striping indent of heredoc string

---

builtin-functions/_functions.txt
builtin-functions/spl.txt
runtime/runtime.cmake
runtime/spl/array_iterator.cpp
runtime/spl/array_iterator.h
tests/phpt/spl/array_iterator.php

ArrayIterator provides a way to iterate the array without
using `foreach` statement or legacy `next()`/`current()` APIs.
In PHP it has almost identical performance to the above mentioned
pair of `next()`/`current()`.
In KPHP it works with minimal overhead when compared to a normal
`foreach` statement. This means that is can be used in lower
level components that need to iterate the array in unusual way.
Some performance comparison results:
Direct1000         7065.0 ns/op   0 B/op      0 allocs/op
ArrayIterator1000  8375.0 ns/op   0 B/op      0 allocs/op
CopyKeys1000       40541.0 ns/op  16088 B/op  1 allocs/op
Reslice1000        74655.0 ns/op  88088 B/op  1001 allocs/op
Direct - `foreach` array iteration.
ArrayIterator uses the newly introduced class.
CopyKeys uses `array_keys()` to …

add initial SPL ArrayIterator class support

---

builtin-functions/_functions.txt
net/net-connections.cpp
net/net-connections.h
runtime/interface.cpp
runtime/interface.h
tests/python/lib/engine.py
tests/python/lib/http_client.py
tests/python/lib/kphp_server.py
tests/python/lib/tl_client.py
tests/python/tests/http_server/php/index.php
tests/python/tests/http_server/test_ignore_user_abort.py

Introduction
---------------
**ignore_user_abort** — Set whether aborting should abort script execution. This implementation **matches the description** [here](https://www.php.net/manual/en/function.ignore-user-abort.php) with **one exception** unlike the implementation in PHP, the current version considers the **nesting level** and does not complete the script until it becomes zero
Description
---------------
```php
ignore_user_abort(?bool $enable = null): int
```
- **Parameter List**
Takes a flag **value** and sets it with the **appropriate** nesting level **change**. If the argument is **null**, then returns the current level **without changing** it
- **Return Values**
Return nesting level previous value
Usage
--------
```php
function important_work(...) {
ignore_user_abort(true);
... …
```

add function ignore_user_abort

---

server/numa-configuration.cpp
server/php-engine.cpp

Use `numa_available() < 0` instead of `numa_available() != 0` to check that NUMA is not available
The fragment from documenetation:
```
Before any NUMA API functions can be used, the program must call numa_available(). When this function returns a
negative value, there is no NUMA policy support on the system. In this case, the behavior of all other NUMA API
functions is undefined and they should not be called. 
```

fix NUMA availability checking

---

runtime/memory_resource/monotonic_buffer_resource.cpp
runtime/memory_resource/monotonic_buffer_resource.h
runtime/memory_resource/unsynchronized_pool_resource.cpp

This change adds some extra info to the OOM error messages to make fragmentation issues tracking easier.
The `buffer_free_space` measures how much memory the script buffer has left when the OOM happened. Ideally, this value should be low, like `0.1`, meaning there is only 10% memory left.
When calculating the fragmentation human-readable hint, we're taking the size of the allocation into the account.
Examples:
```
Warning: Can't allocate 524328 bytes (normal fragmentation, buffer free space: 0.70)
Warning: Can't allocate 72 bytes (low fragmentation, buffer free space: 0.02)
```

[runtime] add fragmentation-related info to OOM error messages

---

runtime/mixed.inl
runtime/regexp.cpp
runtime/string.inl
runtime/string_decl.inl
runtime/string_functions.cpp

Most PHP functions wrap negative offset and make it 0 if it overflows the length.
Direct string indexing and `isset()` checks, hovewer, are not doing that.
Rename `get_correct_index` function into `get_correct_offset` to make this difference more obvious.
`get_correct_index` is reverted to its original form. It should not be used to calculate the offset.
Also added `string::isset` method to use that in both string internal implementation and inside mixed isset check for strings.

[runtime] fix string indexing (was broken during the refactoring)

---

server/cluster-name.cpp
server/cluster-name.h
tests/cpp/server/cluster-name-test.cpp

This patch consists of the following improvements:
- Allow cluster name to contain digits and '-'
- Check cluster name for incorrect symbols on start instead of force quiet replacing them with '_'
- Handle the case when cluster name is longer than 108 bytes to be able to create `UNIX_SOCKET` for graceful restart. Before this patch, server just crashed when attempting to create such socket on graceful restart.

Improve cluster name

---

runtime/string_functions.cpp
tests/phpt/string_functions/008_misc.php

This change introduces two optimizations for the above mentioned functions:
1. If no characters need to be converted, return the argument as is. This is the best scenario, no allocations, no data copying. If there is such a character, save its offset (pos).
2. Use the char pos obtained at the first step and use `memcpy` to copy eveything before that pos, since we know that part doesn't need any case folding.
Benchmark results are provided below.
Execution time results:
name                   old time/op    new time/op    delta
Strtolower::1nop         42.2ns ± 3%    20.8ns ± 6%   -50.71%  (p=0.000 n=10+10)
Strtolower::8nop         72.4ns ± 2%    28.7ns ± 2%   -60.36%  (p=0.000 n=10+10)
Strtolower::32nop         182ns ± 1%      42ns ± 0%   -76.92%  (p=0.000 n=10+9)
Strtolower::128nop …

[runtime] optimize `strtolower` and `strtoupper`

---

runtime/string_functions.cpp
tests/phpt/string_functions/008_misc.php

Pre 8.2 behavior for different lengths is lenght delta. Previously, our version relied on `\0`, which is OK if you don't want to have exactly the same result values as PHP. Since it's such a minor optimization (if it actually optimizes anything), just follow what PHP does. This simplifies testing and reduces the risk that someone will use function result in some context where that difference matters.
See: https://github.com/php/php-src/blob/11491b63f800d150a00e9855f3a0a49e7bca50f7/Zend/zend_operators.c#L2608
For php8.2: https://github.com/php/php-src/blob/30ed8fb32da398f62bb08ebd59c607eeafc3621d/Zend/zend_operators.c#L3005

[runtime] fix strcasecmp behavior

---

compiler/pipes/check-func-calls-and-vararg.cpp
compiler/pipes/deduce-implicit-types-and-casts.cpp
tests/kphp_tester.py
tests/phpt/array/026_array_is_list.php
tests/phpt/errors/007_method_params_n_variadic.php
tests/phpt/variadic_args/012_php_doc_variadic.php
tests/phpt/variadic_args/016_unpack_positional.php
tests/phpt/variadic_args/102_pass_less_arguments.php
tests/phpt/variadic_args/111_bad_type_after_unpack.php
tests/phpt/variadic_args/111_unpack_non_variadic_fail.php
tests/phpt/variadic_args/112_bad_count_after_unpack.php
tests/phpt/variadic_args/112_unpack_non_variadic_fail.php
tests/phpt/variadic_args/113_unpack_to_cast.php

I've added a feature that can seem strange at first eye.
```php
function f($x, $y) { ... }
f(...[1, 2]);   // f(1,2)
f(3, ...[4]);   // f(3, 4)
f(...[], ...[5, ...[6, ...[]]], ...[]);  // f(5, 6)
```
This now works in KPHP too. It also works with default arguments and variadic arguments:
```php
function g($x, $y, ...$rest) {}
g(...[1, 2, 3, 4]);  // g(1, 2, [3,4])
g(5, ...[], ...[6, 7], ...[8]);  // g(5, 6, [7,8]);
```
This works only if arrays are fixed-size in compile-time. E.g., you can't call `f(...$some)` from the example above, only `f(...[$x,$y])`.
It will be useful in the near future, with variadic generics. 
Using variadic generics, you'd be able to proxy any `...$args`. For example,
```
function h($x, $y, $z, $w = 0.0) { ... }
// assume this is a variadic generic from the …
```

support unpacking fixed-size arrays to positional arguments

---

runtime/job-workers/client-functions.cpp

Almost always this warning is the consequence of external factors: net/cpu lags, network queries slowdown etc.

Downgrade warning `Can't send job: not enough shared messages` to notice

---

runtime/memcache.h
runtime/tl/rpc_function.h

Add `virtual_builtin_sizeof` and `virtual_builtin_clone` for some builtin classes
Without them compiler crashes on gcc when trying to use such classes in job worker methods

Add virtual_builtin methods for builtin classes

---

compiler/code-gen/vertex-compiler.cpp
tests/phpt/phc/parsing/negative_literals.php

Producing `-9223372036854775808_i64` literal will result in C++ compiler warning about integer overflow.
The recommended way to express min value is `(-9223372036854775807_i64 - 1_i64)`.

[compiler] add a special case for int64_t min value codegen

---

runtime/allocator.cpp
runtime/allocator.h
runtime/php_assert.cpp

Before the fix, it led to endless recursion from here
https://github.com/VKCOM/kphp/blob/01582fa6c0904ef6566fcd326ffeb58c35a777d9/runtime/allocator.cpp#L105

don't perform allocations in php_warning if script allocator is disabled

---

compiler/code-gen/vertex-compiler.cpp
compiler/pipes/collect-main-edges.cpp
compiler/vertex-desc.json
compiler/vertex-meta_op_base.h
tests/benchmarks/BenchmarkMultiSwitch.php

Instead of producing a mixed-typed variable for every switch statement, try to find a more suitable type.
Most of the switches are optimized to int and string switches, so in those cases having non-mixed var is very beneficial.
Even for expr (var) switches we can get a measurable improvement if all cases and condition expr itself evaluate to some properly-typed value, like int or string.
Here is a non-compherensive list of why mixed-typed vars are not optimal:
* Expensive destructor, `mixed::~mixed` shows up in the CPU profiles
* The need to do `mixed::as_string()` many times inside optimized string switches
* mixed-typed overloadings are used in `eq2()` calls
The implementation used in this PR tries to avoid excessive work from the compiler. If it can be assumed to be a int/string …

[compiler] better type inference for switch cond var

---

builtin-functions/_functions.txt
runtime/interface.cpp
runtime/interface.h
tests/zend-test-list

Added support for third  $rest_index param of [getopt()](https://www.php.net/manual/en/function.getopt.php) php function.

add support $rest_index param of getopt() 

---

compiler/code-gen/declarations.cpp
compiler/code-gen/declarations.h
tests/phpt/json/114_field_reorder.php
tests/phpt/memory_usage/2_classes.php
tests/phpt/msgpack_serialize/112_field_reorder.php

Some classes can benefit from fields reordering to occupy less space due to the unnecessary padding.
Suppose that we have a class like this:
```php
class Example {
public int $a;  // size=8
public bool $b; // size=1
public int $c;  // size=8
public tuple(bool, bool, bool, bool) $d; // size=4
}
```
It's layout in memory would look like this:
[ 4 ] ref_cnt
[ 4 ] ! padding
[ 8 ] a
[ 1 ] b
[ 7 ] ! padding
[ 8 ] c
[ 4 ] d
[ 4 ] ! padding (trailing padding due to struct alignment)
The total size would be 40.
With this patch, the compiler will re-arrange some fields to minimize the amount of padding we would get.
[ 4 ] ref_cnt
[ 4 ] d
[ 8 ] a
[ 8 ] c
[ 1 ] b
[ 7 ] ! padding (trailing padding due to struct alignment)
The result size will be 32.
The algorithm is quite simple:
1. Sort all fields by …

[compiler] re-order class fields to reduce objects size

---

runtime/string.inl
tests/cpp/runtime/string-test.cpp

Suppose that we have this string: `" -123"`
And we're calling `to_int` with it's pointer and `l=3` Without this fix, it would consume the space without taking `l` into the account, so the result would be `-12` instead of `-1`.

[runtime] fix length handling in `string::to_int(char*, uint32_t)`

---

runtime/string_functions.cpp
tests/phpt/pk/011_substr.php

PHP returns empty string, `""`
KPHP returned `false`
The old test was passing due to the missing `@ok` tag.

fix `substr` corner case with `start=length`

---

common/sanitizer.h
runtime/files.cpp
server/php-runner.cpp
server/php-runner.h
server/php-worker.cpp

Leak sanitizer(lsan) by default run along with address sanitizer(asan), but in case of kphp lsan fails every time with error:
There are 2 reason of that:
1) User code works within coroutine, whose stack memory is protected with `mprotect(run_stack, getpagesize(), PROT_NONE)` call. That makes lsan failed to examine stack memory.
2) __sanitizer_start_switch_fiber/__sanitizer_finish_switch_fiber sanitizer's hooks called incorrect. Quoting [comment](https://github.com/llvm-mirror/compiler-rt/blob/69445f095c22aac2388f939bedebf224a6efcdaf/include/sanitizer/common_interface_defs.h#L302) from sanitizer's source code:
> /// Before switching to a different stack, you must call
/// <c>__sanitizer_start_switch_fiber()</c> with a pointer to the bottom of the
/// destination stack and with its size. …

enable leak sanitizer

---

builtin-functions/_functions.txt
runtime/datetime-class.cpp
runtime/datetime-class.h
runtime/datetime.cpp
runtime/interface.cpp
runtime/runtime.cmake
runtime/timelib_wrapper.cpp
runtime/timelib_wrapper.h
tests/phpt/datetime/01_format.php
tests/phpt/datetime/02_create.php
tests/phpt/datetime/03_set_timestamp.php
tests/phpt/datetime/04_modify.php
tests/phpt/datetime/05_modify_wrong_modifier.php
tests/phpt/datetime/06_set_date.php
tests/phpt/datetime/07_set_time.php
tests/phpt/datetime/08_date_time_zone.php
tests/phpt/datetime/09_create_from_format.php
tests/phpt/datetime/10_get_offset.php

This PR adds some functionality of php [DateTime](https://www.php.net/manual/en/class.datetime.php) class. Namelly, the following functions:
```
class DateTime {
/** @kphp-extern-func-info can_throw */
public function __construct(string $datetime = "now", ?DateTimeZone $timezone = null);
public static function createFromFormat(string $format, string $datetime, ?DateTimeZone $timezone = null): ?DateTime;
public static function getLastErrors(): array|false;
public function modify(string $modifier): ?DateTime;
public function setDate(int $year, int $month, int $day): DateTime;
public function setISODate(int $year, int $week, int $dayOfWeek = 1): DateTime;
public function setTime(
int $hour,
int $minute,
int $second = 0,
int $microsecond = 0
): DateTime;
public function setTimestamp(int …
```

add DateTime class

---

tests/kphp_ci_pipeline_runner.py

`TestConfdataIngnoredUpdates::test_load_and_kill_worker` is flaky because of ASAN strange behavior:
ASAN detects some error, generates `engine_sanitizer_log` and kills kphp server at the middle of the test execution.
But `engine_sanitizer_log` doesn't contain anything sensible.
It leads to the test flaky failures.

[tests] disable flaky integration test on ASAN

---

runtime/datetime/timelib_wrapper.cpp
runtime/regexp.cpp
tests/phpt/timelib/strtotime.php
tests/python/lib/engine.py
tests/python/lib/kphp_builder.py
tests/python/lib/testcase.py
tests/python/lib/tl_client.py

This PR turns on memory leak sanitizer in tests. Also memory leaks have been fixed in timelib_wrapper.cpp and suppressed in regexp.cpp.

turn on memory leak sanitizer in tests

---

common/macos-ports.cpp
common/macos-ports.h
runtime/allocator.cpp
tests/cpp/runtime/_runtime-tests-env.cpp
tests/cpp/runtime/allocator-malloc-replacement-test.cpp

Get rid of deprecated [malloc hooks](https://man7.org/linux/man-pages/man3/malloc_hook.3.html). These hooks is removed from further versions of glibc making compilation of kphp unsuccessful under e.g. ubuntu 22.

eliminate deprecated malloc hooks

---

runtime/allocator.cpp
runtime/allocator.h
runtime/kphp-backtrace.cpp
runtime/kphp-backtrace.h
server/php-engine.cpp
server/php-queries.cpp
server/server-log.cpp

Most likely, the key reason of the error - _malloc_ replacement isn't rolled back correctly sometimes.
In production it happens in 2 cases: at `qmem_clear` function on runtime environment freeing and at `rpcx_execute` on receiving   
RPC response. 
Now we force _malloc_ rollback in this 2 cases to fix the error itself and then report the critical error with the stacktrace of last _malloc_ replacement to be able to investigate it more precisely.
relates to `KPHP-1511`

Fix unexpected memory piece error

---

runtime/interface.cpp
server/php-runner.cpp
server/php-worker.cpp

What's the problem
-------------------------
In the code below the environment is initialized and the timeout recovery point is set. But what if sigalarm handler will work inside function init_runtime_environment or higher in the code? Jumping on a non-existent mark leads to `SIGSEGV`
```c++
init_runtime_environment(data, run_mem, mem_size);
if (sigsetjmp(timeout_handler, true) != 0) { // set up a timeout recovery point
on_request_timeout_error(); // this call will not return (it changes the context)
}
```
Solution
-----------
Let's wrap it in critical section. Thanks to this we will ignore the timeout as well as other signals and process them after the recovery point is set.
```c++
dl::enter_critical_section();
is_running = true;
init_runtime_environment(data, run_mem, mem_size);
if …
```

[runtime] fix sigsegv in init_runtime_environment

---

runtime/bcmath.cpp
tests/phpt/dl/483_bcmath.php
tests/phpt/dl/483_bcmod_warnings.php

Add support of floating point arguments in `bcmod(string $num1, string $num2)`. Previously only integers were supported.

add floating numbers in bcmod()

---

builtin-functions/_functions.txt
runtime/bcmath.cpp
tests/phpt/dl/483_bcmath.php
tests/phpt/dl/483_bcpow_warnings.php
tests/phpt/dl/668_bcpow.php

Add support of floating point arguments in `bcpow(string $base, string $exp)`, $exp argument are allowed to be negative.  Previously only integers and positive exponent were supported.

add floating numbers in bcpow()

---

builtin-functions/_functions.txt
runtime/datetime/date_interval.cpp
runtime/datetime/date_interval.h
runtime/datetime/datetime.cpp
runtime/datetime/datetime.h
runtime/datetime/datetime_immutable.cpp
runtime/datetime/datetime_immutable.h
runtime/datetime/timelib_wrapper.cpp
runtime/datetime/timelib_wrapper.h
runtime/runtime.cmake
tests/phpt/datetime/12_create_interval.php
tests/phpt/datetime/13_create_interval_from_date_string.php
tests/phpt/datetime/14_create_interval_wrong_date.php
tests/phpt/datetime/15_interval_format.php
tests/phpt/datetime/16_add_sub_date_interval.php
tests/phpt/datetime/17_sub_relative_interval_warning.php
tests/phpt/datetime/18_diff_date_interval.php

This PR is the last in `DateTime` - related family of patches. Previous was: [1](https://github.com/VKCOM/kphp/pull/598) and [2](https://github.com/VKCOM/kphp/pull/648). It adds `DateInterval` class and related functionality in `DateTime` and `DateTimeImmutable`, namely `add/sub/diff` methods.

add DateInterval

---

tests/kphp_ci_pipeline_runner.py
tests/python/lib/file_utils.py

Before that we built engines on each pipeline run. Now we just install them from deb packages.

[tests] install engines from deb packages for integration tests

---

vkext/rpc-tests/main.php
vkext/rpc-tests/memcache-rpc-tl-test.patch
vkext/vkext-schema-memcache.cpp
vkext/vkext.cpp

**The problem**
In typed serialization mode TL type `Maybe %(Vector string)` corresponds PHP type `string[]|null`.
But if you tried to store `["asdf", "asdf"]`, you would get the following error:
```
Unknown constructor asdf for type Maybe
```
So it mistakenly was expected to be like in untyped mode, i.e.: `["_" => "resultTrue", "result" => ["asdf", "asdf"]]`.
It happened because typed mode was determined by the condition like `type of serialized object is not array` in case of Maybe storing. But this condition is not hold in case of `Maybe<Vector>` or `Maybe<Tuple>`.
**Solution**
Let's use special `typed_mode` flag to distinguish typed and untyped storing mode. We will set it at every typed storing entrypoint and reset after that.

[vkext] Fix RPC TL `Maybe<array>` storing

---

runtime/array_functions.h
tests/benchmarks/BenchmarkImplode.php
tests/phpt/array/026_implode.php

Some stats from a real-world app:
~0.7% calls with count=0
~56%  calls with count=1
~43%  calls with count>1
The count=0 case can be optimized by returning the empty string right away, but since it's so rare, this change is not applied. Our allocator knows how to allocate an empty-sized string efficiently.
The count=1 case can be optimized by returning the sole array element. This may require a to_string conversion, so we're wrapping it in `f$strval`. Since this is a frequent case, this optimization will be applied.
This optimization is quite common in languages with immutable (or COW) strings:
https://cs.opensource.google/go/go/+/refs/tags/go1.19.2:src/strings/strings.go;l=435
Benchmark results:
name               old time/op    new time/op    delta
Implode::Implode1    58.0ns ± 0% …

[runtime] add count=1 special case for `implode()` function

---

builtin-functions/_functions.txt
runtime/interface.cpp
runtime/mbstring.cpp
runtime/mbstring.h

| Name         | PHP | KPHP | Comment                                                                          |
|:-------------|:---:|:----:|:---------------------------------------------------------------------------------|
| cp1251       |  ✅  |  ✅   | It's okay, it accepts it as **windows-1251**                                     |
| utf-8        |  ✅  |  ✅   | It's okay, it accepts it as **UTF-8**                                            |
| utf8         |  ✅  |  ❌   | In KPHP error `encoding "utf8" doesn't supported"`, PHP accepts as **UTF-8**     |
| windows1251  |  ❌  |  ✅   | In PHP error `Invalid encoding "windows1251"`, KPHP accepts as **windows-1251**  |
| lol-1251-kek |  ❌  |  ✅   | In PHP error `Invalid encoding "lol-1251-kek"`, KPHP accepts as **windows-1251** |
| …

detect incorrect encoding names for mb_functions

---

compiler/code-gen/naming.h
compiler/code-gen/vertex-compiler.cpp
tests/benchmarks/BenchmarkConcat.php
tests/phpt/optimizations/010_str_concat.php

Instead of creating a tmp string for string_build on the rhs of append, append directly to the string:
```
$s .= $p1 . $p2 ...; // creates a tmp string for $p1 . $p2 ...
=>
$s->reserve(strlen($s) + strlen($p1) + strlen($p2) ...);
$s .= $p1;
$s .= $p2;
```
These patterns will be optimized:
$s .= $p1 . $p2
$s .= $p1 . $p2 . $p3
...
Due to the fact that we compile `"<$x>"` as string build of `"<"`, `$x` and `">"`, these patterns will be optimized too:
$s .= "<$x>";
$s .= /* any string interpolation expr */
...
See Interpolated benchmark results
Since we rewrite some sprintf into a string build, these calls might benefit from this optimization too if it's append op with sprintf on the rhs.
Benchmark results:
name                               old time/op    new time/op    delta …

[compiler] optimize `op_append` with concat rhs

---

server/job-workers/job-worker-server.cpp

using job_response->job_id after job_writer.write_job_result results in undefined behavior because job_response will be released from another process when it reads the response

fixed undefined behavior in job worker when verbosity-job-workers >= 2

---

compiler/pipes/collect-main-edges.cpp
tests/phpt/dl/1040_nohint_always_throw.php
tests/phpt/exceptions/inheritance/29_throw_from_lambda3.php
tests/phpt/phpdocs/030_hint_but_always_throw.php

With this MR, such code becomes valid:
```php
function getInt(): int {
throw new Exception("todo");
}
$i = getInt();  // int, though getInt() never returns
```
Same for exit/die and more complex situations when a function never returns (e.g. all cases of a switch throw)

better handle functions that always throw/exit

---

compiler/pipes/final-check.cpp
compiler/pipes/optimization.cpp
tests/phpt/phc/parsing/impure.php
tests/phpt/phpdocs/108_return_Unknown.php
tests/phpt/phpdocs/109_param_Unknown.php

Such a function previously crashed in `kphp_assert`:
```
/**
* @return A|null[]
*/
function wrongReturn2() {
$m = [];
for ($i = 0; $i < 1; ++$i)
$m[] = new A;
return $m;
}
```
(notice an invalid `@return`)

fix a crash in OptimizationPass on indexing phpdoc leading to tp_Error

---

compiler/class-assumptions.cpp
compiler/compiler.cpp
compiler/pipes/convert-invoke-to-func-call.cpp
compiler/pipes/convert-invoke-to-func-call.h

Currently at VK.com, very-very rarely there is a compilation error "invalid ()-invocation of a non-lambda". This PR fixes the problem. The reason you can find in #443.
The solution is not to parallelize lambdas and outer functions when performing replacing `()` to `__invoke()`. Now, a lambda passes this pass only after a parent function does, within the same thread. It prevents traversing a parent function in parallel when calculating assumptions for it.

fix a race leading to 'invalid ()-invocation of a non-lambda'

---

compiler/code-gen/vertex-compiler.cpp
compiler/gentree.cpp
compiler/gentree.h
compiler/pipes/generate-virtual-methods.cpp
compiler/pipes/instantiate-generics-and-lambdas.cpp
compiler/pipes/transform-to-smart-instanceof.cpp
compiler/pipes/transform-to-smart-instanceof.h
compiler/vertex-util.cpp
compiler/vertex-util.h
docs/kphp-language/static-type-system/generic-functions.md
tests/phpt/generics/027_constexpr_switch.php
tests/phpt/generics/028_constexpr_services_cont.php
tests/phpt/generics/130_not_constexpr_switch_1.php

Suppose you want something like `$factory->getInstance<T>()`, to be used like
```php
$factory->getInstance(FooService::class)->fooMethod();
$factory->getInstance(AnotherService::class)->anotherMethod();
```
Here is a possible implementation:
```php
/**
* @kphp-generic TService
* @param class-string<TService> $serviceClass
* @return TService
*/
function getInstance(string $serviceClass) {
switch ($serviceClass) {
case FooService::class:
return $this->foo ?? ($this->foo = $this->createFoo());
case AnotherService::class:
return $this->getAnother();
// more services
}
if (isset(self::HIDDEN[$serviceClass])) {
throw new Exception("$serviceClass is private and can not be used");
}
throw new Exception("$serviceClass not found");
}
```
Let's see how `getInstance<FooService>` would look like: …

handle switch over a constexpr string, a pattern for generic factories

---

compiler/data/modulite-data.cpp
compiler/data/modulite-data.h
compiler/modulite-check-rules.cpp
compiler/modulite-check-rules.h
compiler/pipes/calc-real-defines-values.cpp
compiler/pipes/inline-defines-usages.cpp
tests/phpt/modulite/005_inheritance/005_inheritance.php
tests/phpt/modulite/005_inheritance/ConnectNoMod005/ErrNoMod005.php
tests/phpt/modulite/005_inheritance/SakCommon005/.modulite.yaml
tests/phpt/modulite/005_inheritance/SakCommon005/ErrSak005.php
tests/phpt/modulite/005_inheritance/plain005/.modulite.yaml
tests/phpt/modulite/005_inheritance/plain005/plain005.php

Consider the following:
```php
class A {
const C = 1;
}
class B extends A {
}
```
In KPHP internals, `B::C` refers to `A::C` actually.
(when we parse `"B::C"` in yaml, we call `$b->get_constant('C')`, it returns a member of `A`)
What bug is fixed here:
**if B and A belong to different modulites, this fact leads to unexpected errors**
Same for methods and properties.

fix modulite issue on inheriting Derived in modulite1 from Base in modulite2

---

runtime/msgpack/object_visitor.cpp
tests/cpp/runtime/msgpack-test.cpp
tests/cpp/runtime/runtime-tests.cmake

We previously had only phpt tests for Message Pack. This PR adds GTest unit tests to check the correctness of `f$msgpack_deserialize/f$msgpack_serialize` without building kphp2cpp.

Implement unittests for msgpack

---

runtime/interface.cpp
server/php-runner.cpp
server/php-worker.cpp
tests/python/tests/shutdown_functions/php/index.php
tests/python/tests/shutdown_functions/test_shutdown_functions.py
tests/python/tests/shutdown_functions/test_shutdown_functions_errors.py
tests/python/tests/shutdown_functions/test_shutdown_functions_exceptions.py
tests/python/tests/shutdown_functions/test_shutdown_functions_timeouts.py

Here're 2 bug fixes:
1. Before that shutdown functions called from timeout were always terminated at the first from script to net context swap because of 2 reasons: 
a) `PhpScript::time_limit_exceeded` flag wasn't reset
b) Optimization that terminates script preventively 10 ms before timeout uses script finish time for calculating this => 
shutdown functions always were terminated at that point, despite script timeout was reset.
2. Also there's a problem that some suspended forks started from script can be resumed from shutdown functions, which is incorrect and can lead to critical runtime errors. Now it's fixed the same way as at #762

Fix shutdown functions called from timeout behaviour

---

.clang-tidy

We have hundreds alerts that looks like:
Let's remove it, given that they are essentially useless and spoiling to much code.

suppress clang-tidy alert that variable may be declared as const.

---

compiler/code-gen/vertex-compiler.cpp
compiler/generics-reification.cpp
compiler/pipes/early-optimization.cpp
compiler/pipes/instantiate-generics-and-lambdas.cpp
compiler/rewrite-rules/replace-extern-func-calls.cpp
tests/phpt/generics/018_classof_keyword.php
tests/phpt/generics/020_extends_hint.php
tests/phpt/generics/027_constexpr_switch.php
tests/phpt/generics/123_no_use_in_lambda_typeof.php
tests/phpt/generics/131_invalid_classof.php

Now, `classof($generic_arg)` is handled at generic functions instantiation and produces a constexpr string, so that `switch(classof($generic_arg))` is treated as a constexpr switch within a generic function.
This gives an ability to implement function overloading for arguments if that arguments are instances (even without a common base):
```php
function overloaded(object $o) {
// common code
switch (classof($o)) {
case ModelA::class:
...
break;
case ModelB::class:
...
break;
}
// common code
}
```
From this PR, `classof()` became more strict: think of it like a compiler keyword available only for generic parameters. `classof(new A)` and `classof($local_var)` won't work.
The latter syntax is much more pretty and will be available some time after.
For now, it can't be used in PHP, since …

classof() compatible with constexpr switch for function overloading

---

compiler/pipes/check-modifications-of-const-vars.cpp
compiler/pipes/erase-defines-declarations.cpp
tests/phpt/constants/002_modification.php

For now KPHP successfully compiles the following example:
```php
<?php
function getInt(int $x) { // 1
return ($x + 4) * 2; // 2
} // 3
const INT_CONST = getInt(17); // 4
INT_CONST = 123; // 5
```
The behavior differs from PHP, it should be Compile Error on line 3.
But naturally we should temporarily support such possibility because there are some cases in vkcom code base that use this feature and cannot stop doing this effortlessly. At the moment, KPHP also compiles line 5 because it is supposed on later passes that line 4 is impossible.
Yes, primarily  we should do our best to prohibit construction on line 4, but for now **this PR causes Compile Error at reset of global constants that are initialized by non-const values.**

Causing Compile Error at reset of global constants that are initialized by non-const values

---

docs/kphp-language/php-extensions/ffi.md

This note explains what to do if `const char*` function result is not a proper C-string (i.e. it's not a null-terminated string).

docs: add a note about const char* return values

---

runtime/resumable.cpp
tests/python/tests/shutdown_functions/php/index.php
tests/python/tests/shutdown_functions/test_shutdown_functions_timeouts.py

Here're 2 improvements:
- Fix forcible stopping running resumables by resetting `first_free_started_resumable_id` global.
- Forcibly stop forked resumables as well, by unbinding them from their waiting resumables.

Shutdown from timeouts fix

---

runtime/oom_handler.cpp
runtime/oom_handler.h
server/php-runner.cpp
tests/python/tests/http_server/php/test_oom_handler.php
tests/python/tests/http_server/test_oom_handler.py

- Remove critical section from OOM handler to allow timeout in it
- Don't call shutdown functions from timeout inside OOM handler

Allow timeouts inside OOM handler

---

CMakeLists.txt
cmake/init-compilation-flags.cmake

Use custom_php_project.cmake only when KPHP_CUSTOM_CMAKE=ON option passed to make CMakeLists.txt

hide custom_php_project.cmake under KPHP_CUSTOM_CMAKE option

---

builtin-functions/_functions.txt
runtime/datetime/datetime_functions.cpp
runtime/datetime/datetime_functions.h
runtime/interface.cpp

General
-----------
This pr adds a function `set_use_updated_gmmktime(...)` to enable the updated implementation of the gmmktime function
Details
---------
In the past, the source code of gmmktime used the trick of changing the environment variable "TZ" and using `mktime`. This could cause it to not work correctly on some platforms. Now taking the timestamp is done with `timegm`. The magic constants were also removed

[runtime] add flag for the implementation version of gmmktime 

---

runtime/rpc.cpp
runtime/rpc.h
runtime/typed_rpc.cpp

General
----------
Before this pr responses that was gotten from functions `rpc_tl_query_result_one(...)` and `typed_rpc_tl_query_result_one(...)` changed rpc error code to `TL_ERROR_UNKNOWN` independently of it's real error code. It leaded to situations like this
```
array(2) {
["__error"]=>
string(23) "Timeout in KPHP runtime"
["__error_code"]=>
int(-4000)
}
```
But [here](https://github.com/VKCOM/kphp/blob/master/runtime/rpc.cpp#L644) error message composed with a different code

[runtime] save rpc error code in rpc_tl_query_result_one()

---

builtin-functions/_functions.txt
runtime/interface.cpp
runtime/rpc.cpp
runtime/zlib.cpp
runtime/zlib.h
tests/phpt/pk/016_gzip.php

General
-----------
This pr add two functions [`deflate_init(...)`](https://www.php.net/manual/en/function.deflate-init.php) and  [`deflate_add(...)`](https://www.php.net/manual/en/function.deflate-add.php) from php, new class [`DeflateContext`](https://www.php.net/manual/en/class.deflatecontext.php) which store compression context and several constants from zlib.
Details
--------- 
Since incremental compression is performed in several steps, functions have been added for dynamic memory allocation for zlib

[runtime] add incremental compression

---

compiler/function-pass.h
compiler/vertex-meta_op_base.h

*  Fix drawback - there was wrong location with call `on_exit_vertex`
*  Add optimization - iterative DFS in `run_function_pass`. Tagged pointers are used to define direction: top-down or bottom-up.
I measured the build time of vkcom and found out that this optimization accelerated the build time by an average of 4%. Note: if I do not use tagged pointers (and use additional memory, which means direction of traversal), then the time difference becomes invisible. Therefore, in the absence of tagged pointers, I left the old algorithm.

[compiler] Improve AST traversal DFS in case of x86_64 

---

.clang-tidy
builtin-functions/_functions.txt
runtime/curl-async.cpp
runtime/curl-async.h
runtime/curl.cpp
runtime/curl.h
runtime/interface.cpp
runtime/net_events.cpp
runtime/runtime.cmake
server/curl-adaptor.cpp
server/curl-adaptor.h
server/php-queries.cpp
server/php-queries.h
server/php-worker.cpp
server/server.cmake
server/slot-ids-factory.cpp
server/slot-ids-factory.h
tests/python/tests/curl/curl_test_case.py
tests/python/tests/curl/php/index.php
tests/python/tests/curl/test_curl_resumable.py
tests/python/tests/curl/test_curl_resumable_reuse_handle.py
tests/python/tests/curl/test_curl_reuse_handle.py

This PR introduce `curl_exec_concurrently()` function which may be used as drop-in replacement for regular `curl_exec()` with the only difference that it meets our [fork](https://vkcom.github.io/kphp/kphp-language/best-practices/async-programming-forks.html) concept.
Let's assume we have a simple server running on `localhost:9000`, which can accept `sleep_time_s` url param and sleep specified amount of seconds before responding. So e.g. it will respond on `localhost:9000/?sleep_time_s=0.5` request after 0.5 second.
Now let's send 2 request and see what happens:
```
function run_curl_request($remote_sleep_s) {
fprintf(STDERR, "\nstart run_curl_request($remote_sleep_s)\n");
$ch = curl_init("localhost:9000/?sleep_time_s=$remote_sleep_s");
$resp = curl_exec_concurrently($ch);
curl_close($ch); …
```

implement curl_exec_concurrently()

---

runtime/interface.cpp
runtime/resumable.cpp
runtime/runtime.cmake
server/php-engine.cpp
server/php-queries.cpp
server/php-queries.h
server/php-runner.cpp
server/php-runner.h
server/server.cmake
server/signal-handlers.cpp
server/signal-handlers.h
tests/python/tests/http_server/php/test_oom_handler.php
tests/python/tests/http_server/test_oom_handler.py
tests/python/tests/shutdown_functions/php/index.php
tests/python/tests/shutdown_functions/test_shutdown_functions_timeouts.py

General
-----------
Enable shutdown functions if timeout was in script context and script call swap context or start resumable
Details
---------
Remove longjmp from sigalrm handler. Instead of this remember timeout fact and set up second timeout that is deadline to call shutdown functions from runtime

enable shutdown functions on several timeout situations

---

compiler/gentree.cpp
tests/phpt/tup/001_tuple_create.php
tests/phpt/tup/111_internal_comma.php

Code like `tuple(1,2,)` was compiled with error. This PR fixes this issue,  such code is going to be successfully compiled.

Allow trailing comma in tuples

---

runtime/interface.cpp
runtime/interface.h
server/php-engine-vars.cpp
server/php-engine-vars.h
server/php-engine.cpp
server/signal-handlers.cpp
server/signal-handlers.h
tests/python/tests/shutdown_functions/test_shutdown_functions_timeouts.py

- Don't delay timeout if there's no shutdown functions
- Add option for hard-timeout to turn it off in case of emergency (by default 1 sec is enabled)
- Never delay timeout in job workers because it's critical

Shutdown functions on timeout: improvements

---

compiler/code-gen/declarations.cpp
compiler/code-gen/declarations.h
compiler/code-gen/includes.cpp
compiler/code-gen/naming.h
compiler/data/class-data.cpp
compiler/data/class-data.h
compiler/pipes/code-gen.cpp

Currently all member function definitions of auto generated classes are located in header files. This slows down compilation. Here I move definitions of next functions in sources files:
1) `msgpack_pack()` and `msgpack_unpack()`
2) `accept()` method for `JsonEncoder`
3) and template:
```
template<class Visitor>
void generic_accept(Visitor &&visitor) noexcept;
```
This also requires explicit instantiation of template in source file.
This measures allow to reduce total size of all object files at ~30% and cold compilation time at ~35% in vkcom.

move function bodies of auto generated classes in source files 

---

runtime/kphp_tracing.cpp
runtime/kphp_tracing_binlog.h
runtime/resumable.cpp
runtime/resumable.h

Here're 2 fixes:
- Changed offset for fork id calculation. Before, calculated ids didn't fit 24 bits which caused overflows
- Implement dynamic precision to store wait net times > 16 sec to 24 bits

Fixes in tracing binlog writer

---

server/php-runner.cpp
tests/python/tests/shutdown_functions/php/index.php
tests/python/tests/shutdown_functions/test_shutdown_functions_timeouts.py

In this https://github.com/VKCOM/kphp/pull/841 pr shutdown functions began to execute after the soft timeout check. 
This pr fix error with script state and add tests to verify checking soft timeout in several cases

reset script state before run shutdown functions

---

.github/workflows/Dockerfile.buster

Last month MySQL started rotating out their GPG signing keys for packages.
Currently, the signing key is stored under /etc/pki/rpm-gpg/RPM-GPG-KEY-mysql-2022 and it is set to expire on 2023-12-14. I assume aptitude is marked mysql as a config no replace file, which means that any attempts to add new signing keys won't work without user intervention because all that will happened is that a ".rpmnew" repo file will be made.

Fix MySQL installation

---

runtime/curl.cpp

Currently, f$curl_multi_close() function isn't signal safe unlike e.g. f$curl_close().

make f$curl_multi_close() signal safe

---

builtin-functions/_functions.txt
common/dl-utils-lite.cpp
common/dl-utils-lite.h
common/stats/provider.cpp
compiler/pipes/register-kphp-configuration.cpp
compiler/pipes/register-kphp-configuration.h
runtime/interface.cpp
runtime/interface.h
runtime/runtime.cmake
runtime/thread-pool.cpp
runtime/thread-pool.h
server/php-engine.cpp
server/php-master.cpp
server/server-stats.cpp
server/server-stats.h
tests/phpt/kphp_configuration/9_thread_pool_ratio.php
third-party/BS_thread_pool.hpp

General
----------
Main goal of this pr is to add simple third-party thread pool to test some hypotheses. The implementation from [here](https://github.com/bshoshany/thread-pool) was chosen as the baseline. In the future, this [library](https://yaclib.github.io/YACLib/ ) may be chosen.
Details
---------
An option `thread-pool-ratio` has been added to define the number of threads. That define threads count ratio of the overall cpu numbers
Also this pr add simple parallel function `do_parallel_job(...)` to check if the system is working well

add third party thread pool

---

runtime/curl.cpp

`CurlEpollFdTracker` was added as a fix of another problem but it didn't help (a37c78294177ed2ed91aea92f07bca6fb253acf7).
Moreover it led to another crash in runtime from `free_runtime_environment`, because iterating over the array like this:
https://github.com/VKCOM/kphp/blob/8a5a52083a945cc7fbfab294e95df32d2bb9051d/runtime/curl.cpp#L1036
uses non-const iterator, which can mutate the array and invokes script memory allocations. In case of `memory limit exceeded` error, `free_runtime_environment` is always called, which in turn calls the code described above. And it leads to `SIGSEGV` in the end.

Removed CurlEpollFdTracker completely

---

runtime/curl.cpp

Sometimes `SIGSEGV` is raised on production from `curl_epoll_cb` on accessing data from script memory.
`curl_epoll_cb` runs after script termination, when script memory is already freed, despite the related `fd` is removed from epoll on script termination.
It happens because sometimes epoll callbacks can be invoked **after** the related 'fd' is removed from epoll. Our net_reactor at first stores epoll events from `epoll_wait`, and only then runs the related callbacks (see `epoll_fetch_events()`), and sometimes it happens that between events fetching and processing script termination is happened.
Usually this situation is handled via some additional connection flags (`conn_expect_query`, `C_WANTRD` etc.) in callbacks like `server_read_write_gateway` and related. But in `curl_epoll_cb` we …

Fix curl resumable epoll related crash

---

runtime/array.inl
runtime/array_decl.inl
runtime/instance-copy-processor.cpp
runtime/instance-copy-processor.h
tests/phpt/memory_usage/10_arrays.php

Currently `estimate_memory_usage()` function shows incorrect results for both vector and map internal storage.
It actually shows how much memory is needed for copying this array, rather than how much memory it currently takes. So it takes only `size` to calculate the memory amount and ignores `capacity`.
This logic is used in `InstanceDeepCopyVisitor` to check if it will be enough memory for copying beforehand. So in this PR this logic is extracted to separate function `calculate_memory_for_copying`.
And `estimate_memory_usage` for arrays now returns the correct size based on `capacity`.

fix function estimate_memory_usage() function

---

common/common.cmake
common/server/crash-dump.cpp
common/ucontext/ucontext-portable.h
common/ucontext/ucontext.cpp
common/ucontext/ucontext.h
compiler/compiler-settings.cpp
docs/kphp-internals/developing-and-extending-kphp/compiling-kphp-from-sources.md
server/php-runner.h
tests/tests.cmake

Removing the dependency on the libucontext library makes it easier to build for macOS on arm processors

Removing the dependency on the libucontext library

---

common/tlo-parsing/tlo-parser.cpp

Due to bug `tl-compiler` always generates `ExprNat` instead of `NatConst` for `NatExpr` case.
Correct .tlo format must fit this scheme:
https://github.com/VKCOM/kphp/blob/c8dc706e0bd125ae1aa9dea0e8f528bd8e146994/common/tl-files/tl.tl#L46 
Here's a fix to maintain correct .tlo format in `tlo-parser`.

[tlo-parsing] Fix typo in tlo schema parser

---

common/fast-backtrace.cpp
common/fast-backtrace.h
server/json-logger.cpp
server/json-logger.h
server/signal-handlers.cpp

General
-----------
Before this pr, all timeouts in net-context were ignored and not logged. Now alarm signals will be logged and write script backtrace

add json log for timeout in net

---

common/tl/compiler/tl-parser-new.cpp
common/tl/compiler/tl-tl.h
vkext/vkext-rpc-tl-serialization.cpp

- keep old _incorrect_ behaviour in `tl-compiler` for backward-compatibility
- maintain _correct_ and _incorrect_ tlo format in `vkext` just in case
relates to https://github.com/VKCOM/kphp/pull/913

TLS_NAT_CONST typo fixes

---

runtime/rpc.cpp
runtime/runtime.cmake
runtime/tl/rpc_req_error.cpp
runtime/tl/rpc_req_error.h
runtime/tl/rpc_response.cpp

- Refactored RpcReqError fetching to get rid of copy-paste
- Maintained RpcReqError with headers. When it comes with headers they're just skipped and an error TL object is returned as usual.
relates to #915

maintained RpcReqError with headers in kphp

---

server/php-engine-vars.cpp
server/php-engine-vars.h
server/php-engine.cpp
server/php-runner.cpp
server/php-worker.cpp
server/server-stats.cpp
server/server-stats.h
server/statshouse/statshouse-manager.cpp
server/statshouse/statshouse-manager.h
tests/python/lib/kphp_run_once.py
tests/python/lib/kphp_server.py

- don't fetch net events right before script termination (relates to #893)
- added total allocation metrics: `kphp_memory_script_allocated_total`, `kphp_memory_script_allocations_count`
- removed maximum script timeout limit
- make `disable-sql` option deprecated and turned on unless SQL port is given

Small unrelated improvements

---

server/php-engine.cpp
server/statshouse/statshouse-manager.cpp
server/statshouse/statshouse-manager.h

It's a preparation for ml-runtime that could be time consuming
We want to have some metrics to monitor

Master-process initialization time stats

---

compiler/compiler-settings.cpp

Example:
```
int main() {
int a = 7;
int b;
b = 10;
return 0;
}
```
Output with _-Wall_:
> $clang++-16 main.cpp -Wall
> main.cpp:4:7: warning: unused variable 'a' [-Wunused-variable]
>   int a = 7;
>       ^
> main.cpp:5:7: warning: variable 'b' set but not used [-Wunused-but-set-variable]
>   int b;
>       ^
> 2 warnings generated.
Output with _-Wno-XXX_ and _-Wall_ at the end:
> $clang++-16 main.cpp -Wno-unused-variable -Wno-unused-but-set-variable -Wall
> main.cpp:4:7: warning: unused variable 'a' [-Wunused-variable]
>   int a = 7;
>       ^
> main.cpp:5:7: warning: variable 'b' set but not used [-Wunused-but-set-variable]
>   int b;
>       ^
> 2 warnings generated.
> 
But if _-Wall_ is before the other _-Wno-XXX_ arguments, everything is compiled successfully

Moving options -Wall before extra_cxx_flags to resolve conflicting -Wno-XXX options for clang

---

runtime/array_decl.inl
runtime/confdata-global-manager.cpp
runtime/confdata-global-manager.h
runtime/confdata-keys.cpp
runtime/confdata-keys.h
server/confdata-binlog-events.h
server/confdata-binlog-replay.cpp
server/confdata-binlog-replay.h
server/confdata-stats.cpp
server/confdata-stats.h
server/php-engine-vars.cpp
server/php-engine-vars.h
server/php-engine.cpp
server/php-master.cpp
server/signal-handlers.cpp
server/statshouse/statshouse-manager.cpp
server/statshouse/statshouse-manager.h
tests/cpp/runtime/confdata-functions-test.cpp
tests/python/lib/engine.py
tests/python/lib/file_utils.py
tests/python/tests/json_logs/test_signals.py

Here're two new approaches:
To prevent OOM errors on confdata overflows we start to throttle events, when too little shared memory left. There're two modes:
- Soft OOM (85%) - replay only existing keys related events until server restart. Ignore new keys.
- Hard OOM (95%) - replay nothing. Ignore all events, don't read binlog at all.
If server enters any OOM modes, it can't go back out of it. Manual server restart is needed for that.
Before any action, that internally invokes allocations, we explicitly check that allocator has enough memory for that.
To achieve this we need to somehow calculate upper-bound for memory that will be required by the action in each particular case.
There're two 'kinds' of allocations:
1. Allocation made by our runtime (`array<mixed>::mutate_if_shared()`, …

Make master outlive confdata out of shared memory errors

---

compiler/kphp2cpp.cpp

Started from ubuntu 21.04 there is default LTO optimisation for all installing deb package include kphp. It's causes errors then kphp transpiling php script. Fix is just flag to disable LTO.

Fix jammy installing from deb package

---

vkext/vkext-rpc.h

For history :)
The code to reproduce the problem:
tl scheme:
```
---types---
kphp.testResponse
elements:(%Vector int) = kphp.TestResponse;
---functions---
@kphp
kphp.testQuery count: int = kphp.TestResponse;
```
simple server (build by kphp2cpp and run with -r port arg):
```
<?php
try {
/** @var \VK\TL\RpcFunction */
$request = rpc_server_fetch_request();
if ($request instanceof \VK\TL\kphp\Functions\kphp_testQuery) {
$value = array_fill(0, $request->count, 7);
$response = \VK\TL\kphp\Functions\kphp_testQuery::createRpcServerResponse($value);
rpc_server_store_response($response);
} else {
store_error(-2001, "Unsupported function");
}
} catch (Exception $e) {
warning('Fatal error: ' . $e->getMessage());
store_error(-2002, $e->getMessage());
}
```
client (run like php script):
```
<?php …
```

increasing the maximum length of an rpc query in vkext

---

server/confdata-binlog-replay.cpp
server/confdata-binlog-replay.h
server/php-engine.cpp

Now it's possible to disable confdata degradation mode (see #946) by specifiying `--confdata-soft-oom-ratio 1.0` start option

Add toggle to disable confdata soft OOM degradation mode

---

cmake/init-compilation-flags.cmake

Since Ubuntu 22.04, lto is enabled by default. It  breaks some builds, let's add `-fno-lto` link option in CMake  by default!

Add link -fno-lto option

---

runtime/kphp_tracing.h

```
kphp_source/runtime/memory_usage.h:152:16: error: ‘struct C$KphpSpan’ has no member named ‘accept’
value.get()->accept(visitor);
pid [11216] failed or terminated : return code 1
```

Fix issue with get_global_vars_memory_stats()

---

builtin-functions/_functions.txt
builtin-functions/spl.txt
runtime/exception.cpp
runtime/exception.h
runtime/math_functions.cpp
runtime/math_functions.h
tests/kphp_tester.py
tests/phpt/dl/385_random_bytes.php
tests/phpt/dl/386_random_int.php
tests/phpt/exceptions/spl/02_builtin_exceptions.php
tests/phpt/exceptions/spl/02_builtin_exceptions_1.php
tests/python/lib/file_utils.py
tests/python/lib/testcase.py

This PR adds support of `random_int` and `random_bytes` functions added in `PHP8`. Also, it adds `Random\RandomException` class into runtime.

Add support of 'random_int' and 'random_bytes' builtins

---

runtime/array.inl
tests/phpt/array/032_array_concat.php

This optimization eliminates creation of a new array. It's valid in case at least one operand is empty.

[runtime] add array concat optimization

---

.github/workflows/Dockerfile.buster
docs/kphp-internals/developing-and-extending-kphp/compiling-kphp-from-sources.md

Previously had an error "The repository 'https://deb.debian.org/debian buster-backports Release' does not have a Release file."
For example: https://github.com/VKCOM/kphp/actions/runs/8739653713/job/23981827080?pr=983.
This PR fixes it.

Change deb.debian.org on archive.debian.org

---

compiler/code-gen/files/vars-cpp.cpp
compiler/kphp2cpp.cpp

* Increase default KPHP_GLOBAL_SPLIT_CNT
* Fix assert: number of file with global variables definitions less or equal than KPHP_GLOBAL_SPLIT_CNT

Fix KPHP_GLOBAL_SPLIT_CNT option

---

runtime/openssl.cpp
runtime/string_decl.inl
runtime/string_functions.cpp
tests/phpt/openssl/9_openssl_random_pseudo_bytes.php
tests/phpt/string_functions/010_xor_strings.php

SIGSEGV was caused by using wrong string's constructor. The constructor we used is an optimization for single-character strings.

Fix SIGSEGV in openssl_random_pseudo_bytes

---

CMakeLists.txt
cmake/init-compilation-flags.cmake
compiler/compiler-settings.cpp
compiler/data/vertex-adaptor.h
compiler/kphp2cpp.cpp

There are small improvements:
* Fix machinery with C++ standard
* Change default mode as k2-component
* Remove useless compile option
* Fix Compile Error with `operator==` in VertexAdaptor

Small improvements to light branch

---

compiler/data/vertex-adaptor.h

Some things about `VertexAdaptor`:
*  Comparison Operator Limitation: the comparison operator is defined only when there is a single template parameter.
*  Template Friends: this class utilizes template friends classes to itself.
* Constructor/Assignment Operator Overloading: there is a constructor/assignment operator that takes the same class with a different template parameter.
* Cross-Instance Comparison and Implicit Conversions: when comparing two instances of the class with different template parameters, one instance is implicitly converted to the other. The intention is to use a hierarchy of casting defined by `op_type_is_base_of`. However, the static_assert does not establish the conversion algorithm, leading the compiler to consider that any class with any template parameter can …

Fix `VertexAdaptor` comparison

---

compiler/threading/tls.h

Previously, we had failing `assert` when forces compiler to use 102 threads, meanwhile 102 equals `MAX_THREADS_COUNT`.
Example:
```
$ ./objs/bin/kphp2cpp dev_kphp/echo.php -t 102 -o a
Starting php to cpp transpiling...
dl_assert failed [tls.h:35: TLS<T>::TLSRaw* TLS<T>::get_raw(int) [with T = ZAllocatorRaw]]: 0 <= id && id <= MAX_THREADS_COUNT
[pid 38283] [time 1714728309] SIGSEGV caught, terminating program
```
It was because TLS storage does not consider an additional thread that is reserved for `CppDestDirInitializer`. This PR adds comment in the code and fixes the problem.

Fix `kphp2cpp` assertion failure when using thread count is equal to `MAX_THREADS_COUNT`

---

runtime-light/allocator/allocator.cpp

Code like this
```php
<?php
$m = ["a" => "b"];
````
leads to array initialization on the image creation step. The script allocator is not available at this time, as it will be created during the component creation phase. It means that dl::allocate call leads to SIGSEGV.
This pr add unlikely if in dl::allocate and similar functions

fix sigsegv in init_php_scripts_once_in_master

---

CMakeLists.txt
common/tl/tl.cmake
common/tlo-parsing/tlo-parsing.cmake
flex/flex.cmake

The problem I'm trying to solve is described in the corresponding issue #997.
The patch replaces hardcoded installation paths with paths from GNUInstallDirs. This should help ensure cross-distribution builds, at least at the directory compatibility level.

Added GNUInstallDirs CMake module

---

compiler/pipes/collect-required-and-classes.cpp
tests/phpt/modulite/010_mod_unreachable/Utils010/.modulite.yaml
tests/phpt/modulite/010_mod_unreachable/Utils010/UnreachableNs/BnotherUn010.php

Related to #1015.
When a modulite exports a method of a class, and the class itself is not reachable in any other ways, now it leads to a compilation error.
This PR fixes this. Resolving from classes in a modulite was earlier done, here I've just added resolving from methods.

Resolve classes from `export` methods in .modulite.yaml

---

compiler/pipes/collect-required-and-classes.cpp
tests/phpt/cl/030_resolve_from_phpdoc.php

Purpose: when a class occurs only in `@param` and is actually never created, resolve it in `CollectRequiredPass`.
Previously, `@param` weren't analyzed there, because phpdocs haven't been parsed up to that execution point, and I didn't want to perform parsing twice.
Unfortunately, the only way to reach the goal is to do parsing twice :( Considering current vkcom codebase. It's very ugly, since parsing is quite a heavy operation.
Ideally, types in phpdoc should be parsed once in gentree, but actually, vkcom has so much syntax-invalid phpdocs, that it's unavailable. (that "invalid" functions aren't reachable in fact, they just exist in a dead codebase, so their phpdocs aren't analyzed later, but trying to parse them in gentree leads to 10k errors)

Resolve classes from `@param` phpdoc

---

compiler/data/class-data.cpp
tests/phpt/clone_keyword/010_clone_abstract.php

Previously, there was a bug that sometimes generated empty `__virt_clone()` implementations. It led to incorrect behavior and reasonable g++ errors (with nocc local fallback).

Fix invalid `__virt_clone()` generation for abstract classes

---

server/php-master.cpp
server/server-config.cpp
server/server-config.h
server/statshouse/statshouse-client.h
server/statshouse/statshouse-manager.cpp

Supposed to use for distinguishing instances on baremetall and different cloud environments

Added environment to `StatsHouse` and `engine.stat`

---

cmake/init-global-vars.cmake

Made for reasons described in discussion #998
Briefly:
When compiler is installing with custom `CMAKE_INSTALL_PREFIX`, the `usr` directories are duplicated. Setting an absolute path resolves this issue.

Set absolute path for VK_INSTALL_DIR

---

compiler/pipes/check-classes.cpp
compiler/pipes/filter-only-actually-used.cpp
compiler/pipes/generate-virtual-methods.cpp
tests/phpt/lambdas/020_uses_in_lambda.php

Sometimes, one could face the following compilation error:
```
var Lambda$ufa6f526451637135_0::$tmp_var is declared but never written; please, provide a default value
```
That happened in such a scenario:
1. A lambda with `use` capturing was in an instance function 
2. That instance function was actually unused
3. That lambda was passed to a typed callable
The reason of an error was that a parent (instance) function was unused, but a lambda itself was used (from a typed callable switch-case dispatching). And since `use` capturing actually declares a field in a lambda class, a type of that field couldn't be inferred (since a type inferer never visits its parent function, it's unused).
The provided solution is to detect such cases (after marking used/unused functions) and to manually
1. …

Fix compilation error for lambdas in unused functions

---

common/kernel-version.cpp
common/kernel-version.h
runtime/files.cpp
server/php-engine.cpp

Now we invoke uname syscall only once on master start and cache it for the next usages.

Cache uname syscall invocation

---

.gitignore
runtime-light/stdlib/rpc/rpc-api.cpp
runtime-light/stdlib/rpc/rpc-api.h
runtime-light/stdlib/rpc/rpc-buffer.h
runtime-light/stdlib/rpc/rpc-context.h
runtime-light/stdlib/rpc/rpc-extra-headers.cpp
runtime-light/stdlib/rpc/rpc-extra-info.cpp
runtime-light/stdlib/rpc/rpc-extra-info.h
runtime-light/stdlib/rpc/rpc-tl-defs.h
runtime-light/stdlib/rpc/rpc-tl-query.cpp
runtime-light/stdlib/rpc/rpc-tl-request.cpp
runtime-light/tl/tl-builtins.cpp
runtime-light/tl/tl-builtins.h
tests/k2-components/scheme.tl
tests/k2-components/test_rpc_memcached.php

Fix a bug in store_string caused by incorrect usage of string_buffer.
Add RpcBuffer class that prevents us from similar bugs in the future.

Make RPC in light runtime more robust

---

runtime-light/stdlib/rpc/rpc-api.cpp
runtime-light/streams/interface.cpp
runtime-light/streams/interface.h

Remove RPC fetch and store of large TL strings since it requires support of large strings in runtime.

Disable RPC fetch of large strings

---

common/exit-codes.h
common/server/signals.cpp
common/server/signals.h
compiler/kphp2cpp.cpp
compiler/make/make.cpp
compiler/stage.cpp
compiler/stage.h

Introduce special exit codes for` PHP -> CPP`, `CPP -> Object files` and `Object files -> binary` stages.
Let's discuss values of exit codes and whether should we do something different from `abort()` for compiler asserts.

Change exit codes

---

compiler/code-gen/files/const-vars-init.cpp

General
-----------
Now for this example
```php
<?php
class B {
public int $value;
public function __construct(int $x) {
// B::$static_int += 1;  // accessing globals in constructor in const classes crashes const_init; todo how to detect it in the future?
$this->value = $x;
}
public function getValue() {
return $this->value;
}
}
const b = new B(42);
echo b->value;
```
Generated initialization looks like this 
```c++
void const_init_level1_file0() noexcept {
c_obj$2ad134878d768207 = f$B$$__construct(class_instance<C$B>().alloc(), 42_i64);
}
```
Since `c_obj...` has no reference counter equal to `ExtraRefCnt::for_global_const` its destructor is called during process termination. It leads to UB in runtime and to sigsegv in runtime-light.
This pr improve initialization to 
```c++
void …
```

fix ub on process termination

---

.gitignore
runtime/tl/tl_builtins.h

Reserve enough space to prevent array reallocations

TL fetch: optimize tl_Dictionary

---

compiler/code-gen/vertex-compiler.cpp
runtime-core/utils/hash.h
runtime-light/coroutine/awaitable.h
runtime-light/coroutine/task.h
runtime-light/scheduler/scheduler.cpp
runtime-light/scheduler/scheduler.h
runtime-light/stdlib/fork/fork-api.h
runtime-light/stdlib/fork/fork-context.h
runtime-light/stdlib/rpc/rpc-api.cpp
runtime-light/stdlib/rpc/rpc-context.cpp
runtime-light/stdlib/rpc/rpc-context.h
runtime-light/stdlib/timer/timer.h
runtime-light/streams/interface.cpp
runtime-light/streams/interface.h

Now RPC in K2 runtime uses forks for:
1. waiting for RPC response;
2. updating RPC response extra info.
Also, this PR adds:
1. execution policy to `start_fork_t` which makes it possible to choose whether we want to run fork immediately or not;
2. cancellable awaitables.

Make K2 RPC asynchronous

---

compiler/data/kphp-json-tags.cpp
compiler/data/var-data.h
compiler/pipes/optimization.cpp
tests/phpt/json/38_optimized_init_val.php

Before this PR empty values are eliminated for string and arrays, so 
```php
class User {
public string $name = '';
public string $password = '';
}
``` 
and 
```php
class User {
public string $name;
public string $password;
}
```
are treated as same.
While it is true technically, this lead to unwanted consequences. Value absence marks such fields as `required` during JSON deserialization. Removed default value changes class semantics and has strong implication of `string` having default value of `''`.
Suggested changes are about storing fact user provided value was optimized and eliminated.
But the fact it was there is used by later steps to correctly process values.

Do not remove empty default values for string and array respectively

---

runtime-core/runtime-core.cmake

Use `-fPIC` only with light runtime

Fix runtime core flags

---

compiler/code-gen/files/init-scripts.cpp
compiler/code-gen/files/tl2cpp/tl-combinator.cpp
compiler/compiler-core.cpp
compiler/compiler-core.h
compiler/compiler-settings.cpp
compiler/compiler-settings.h
compiler/kphp2cpp.cpp
compiler/make/make.cpp
compiler/pipes/calc-bad-vars.cpp
compiler/pipes/code-gen.cpp
runtime-light/component/component.cpp
runtime-light/component/component.h
runtime-light/core/globals/php-script-globals.h
runtime-light/stdlib/exit/exit-functions.cpp
runtime-light/streams/streams.cpp
tests/kphp_tester.py

Rework K2 component modes. Previously we had two component modes: `oneshot`, `multshot`. In this PR I introduce following modes:
1. `k2-cli`: most simple mode. Semantically equivalent to regular `PHP` script;
2. `k2-server`: semantically equivalent to current `KPHP`-server;
3. `k2-oneshot`: K2 oneshot component;
4. `k2-multishot`: K2 multishot component.

Update K2 component modes

---

builtin-functions/kphp-full/_functions.txt
runtime/streams.cpp
runtime/streams.h
runtime/string_functions.cpp
runtime/string_functions.h
tests/phpt/string_functions/011_str_getcsv.php
tests/zend-test-list

Add compatible with PHP 7.4.0 support of [`str_getcsv`](https://www.php.net/manual/en/function.str-getcsv.php) builtin.
Related issues: `KPHP-1856`

add `str_getcsv` builtin support

---

compiler/code-gen/declarations.cpp
compiler/pipes/check-classes.cpp
compiler/pipes/final-check.cpp
compiler/pipes/final-check.h
docs/kphp-language/howto-by-kphp/serialization-msgpack.md
tests/phpt/msgpack_serialize/026_serialize_with_base.php
tests/phpt/msgpack_serialize/027_serialize_intermediate.php
tests/phpt/msgpack_serialize/028_deserialize_inherited.php
tests/phpt/msgpack_serialize/103_serialize_with_base.php
tests/phpt/msgpack_serialize/113_duplicated_inherited_tags.php

Support serialization of inherited classes: 
```php
<?php
/**
* @kphp-serializable
*/
class A {
/**
* @var int
* @kphp-serialized-field 1
*/
public $id = 0;
/**
* @var int[]
* @kphp-serialized-field 2
*/
public $admin_user_ids = [];
}
/**
* @kphp-serializable
*/
class B extends A {
/**
* @var string
* @kphp-serialized-field 3
*/
public $str = "hello";
}
function demo() {
$b = new B();
$str = instance_serialize($b);
$x = instance_deserialize($str, B::class);
var_dump(instance_to_array($x));
}
demo();
```

Serialize inheritance

---

runtime-core/memory-resource/resource_allocator.h
runtime-light/stdlib/crypto/crypto-functions.cpp
runtime-light/tl/tl-core.cpp
runtime-light/tl/tl-core.h
runtime-light/tl/tl-functions.cpp
runtime-light/tl/tl-functions.h
runtime-light/tl/tl-types.cpp
runtime-light/tl/tl-types.h

This PR adds following changes:
1. enhances TL primitives for K2 job workers;
2. adds support for some general TL types, e.g., vector, dictionary, etc;
3. adds TL primitives for K2 confdata.

Enhance K2 TL

---

server/php-runner.cpp
server/php-runner.h
server/server-stats.cpp
server/server-stats.h
server/statshouse/statshouse-manager.cpp
server/statshouse/statshouse-manager.h

New metric represents a duration of maximum running interval when worker in script context 
Related issues: KPHP-1939

add `kphp_request_script_time_max_running_interval` mertric collecting

---

runtime/memcache.cpp
runtime/memcache.h

This PR adds new `MEMCACHE_JSON_SERIALIZED` flag that means that a value we got from MC is serialized in JSON format, so we need to deserialize it accordingly.

Add support for JSON serialized confdata values

---

runtime-light/component/init-functions.cpp
runtime-light/stdlib/confdata/confdata-functions.cpp
runtime-light/stdlib/crypto/crypto-functions.cpp
runtime-light/stdlib/job-worker/job-worker-api.cpp
runtime-light/stdlib/rpc/rpc-api.cpp
runtime-light/tl/tl-core.cpp
runtime-light/tl/tl-core.h
runtime-light/tl/tl-functions.cpp
runtime-light/tl/tl-functions.h
runtime-light/tl/tl-types.cpp
runtime-light/tl/tl-types.h

This PR also does some small refactoring of K2 TL.

K2: add TL types and functions for HTTP queries

---

common/server/crash-dump.cpp

Context: in POSIX-compatible platforms signal handlers can get `ucontext_t` as a parameter, for example, for restoring machine state in moment of handler work.
Now we have a mistake: we get pointer to `ucontext_t` and cast one to `libucontext_ucontext`. It looks good for compiler but leads to incorrect result in runtime. 
Following PR removes error-prone code.

remove error-prone dumper of aarch64 registers

---

builtin-functions/kphp-light/crypto.txt
builtin-functions/kphp-light/functions.txt
builtin-functions/kphp-light/kphp_internal.txt
builtin-functions/kphp-light/time.txt
builtin-functions/kphp-light/unsupported-functions.txt
runtime-light/stdlib/stdlib.cmake
runtime-light/stdlib/time/time-functions.cpp
runtime-light/stdlib/time/time-functions.h
tests/phpt/func_specializations/hrtime.php
tests/phpt/func_specializations/hrtime_error1.php
tests/phpt/func_specializations/hrtime_error2.php
tests/phpt/func_specializations/microtime.php
tests/phpt/func_specializations/microtime_error1.php
tests/phpt/func_specializations/microtime_error2.php
tests/phpt/pk/005_date.php

General
-----------
Add several time builtins. Functions `iso_week_number, date, fix_year` were toked from `datetime_functions.cpp` with few modifications. In the future, this should be moved to common

add time functions

---

common/common.cmake

Unfortunately, not all assemblers supports 64-bit dwarf. The safest way -- disable debug info for `asm` files.
Related issue: KPHP-1979

disable debug info for asm files

---

runtime/kphp_ml/kphp_ml_init.cpp

Previously we had segfault in case of `--kml-dir` parameter points to the directory that is owned by `root`, but the executor of compiled program is not `root`.
Related to [KPHP-1982](https://jira.mvk.com/browse/KPHP-1982)

Fix bug with traversal of directories during reading KML models

---

tests/python/tests/http_server/test_oom_handler.py

Exclude some flaky tests until will be fixed
Related issue: KPHP-1990

Temporary OOM functional tests disabling

---

server/php-runner.cpp
tests/python/tests/http_server/test_oom_handler.py

During the execution of OOM tests with AddressSanitizer enabled, we encountered an error like this:
```
==2123325==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x00000b72af0f at pc 0x000000e831ae bp 0x00000b72ade0 sp 0x00000b72add0
WRITE of size 1 at 0x00000b72af0f thread T0
#0 0xe831ad in kwrite_print_int /home/p-shumilov/Projects/kphp/common/kprintf.cpp:112
#1 0xe834f3 in kwrite(int, void const*, int) /home/p-shumilov/Projects/kphp/common/kprintf.cpp:131
#2 0xdaf788 in kwrite_str /home/p-shumilov/Projects/kphp/server/signal-handlers.cpp:23
#3 0xdb06d4 in sigusr2_handler /home/p-shumilov/Projects/kphp/server/signal-handlers.cpp:103
#4 0x79bd8244251f  (/lib/x86_64-linux-gnu/libc.so.6+0x4251f)
#5 0x79bd824969fb in __pthread_kill_implementation nptl/pthread_kill.c:43
#6 …
```

prevent false-positive `stack-buffer-overflow` ASan detections on signal stack 

---

server/php-runner.cpp
server/signal-handlers.cpp
server/signal-handlers.h

`__sanitizer_start_switch_fiber` and ` __sanitizer_finish_switch_fiber` are not sufficient for informing ASan about the alternate signal stack. In our case, when a signal occurs, the activation of the alternate signal stack mislead ASan about current actual stack and leads to incorrect behavior of `__asan_handle_no_return`:
```
==15381==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0x7f98b59d0000; bottom 0x00000bb21000; size: 0x7f98a9eaf000 (140293662502912)
False positive error reports may follow
For details see https://github.com/google/sanitizers/issues/189
```
Need to use explicit signal stack unpoisoning instead. 
Fix of #1201

prevent false-positive stack-buffer-overflow ASan detections on signal stack, attemp 2

---

builtin-functions/kphp-light/rpc.txt
runtime-light/stdlib/rpc/rpc-api.cpp
runtime-light/stdlib/rpc/rpc-api.h
runtime-light/stdlib/rpc/rpc-state.h
runtime-light/tl/tl-builtins.cpp

This PR adds implementation of following builtins:
- rpc_tl_pending_queries_count
- rpc_tl_query_result_synchronously
- set_fail_rpc_on_int32_overflow

[k2] add missing RPC bultins

---

tests/python/tests/job_workers/php/SharedMemoryPieceCopying/http_worker.php
tests/python/tests/job_workers/php/SharedMemoryPieceCopying/job_worker.php

The Instance Cache does not guarantee immediate and in-place data storage. To avoid flakiness, we need to ensure that key-value pairs are stored. Added the mechanic for making extra attempts to store key-value into IC.

add extra attempts to store into IC for flakiness avoidance, fix `test_shared_memory_piece_copying`

---

runtime-light/stdlib/array/array-functions.h
runtime-light/stdlib/crypto/crypto-functions.cpp
runtime-light/stdlib/crypto/crypto-functions.h
runtime-light/stdlib/exit/exit-functions.cpp
runtime-light/stdlib/exit/exit-functions.h
runtime-light/stdlib/file/file-system-functions.cpp
runtime-light/stdlib/file/file-system-functions.h
runtime-light/stdlib/time/timer-functions.h

It's generally unsafe to pass by reference, this PR fixes it.

Pass arguments by value instead of by const ref in coroutines

---

runtime-common/core/allocator/platform-allocator.h

The `platform_allocator` utilizes `heap_resource::allocate` when used with `KPHP`, and `k2::alloc` when used with `K2`.

add platform_allocator

---

runtime-common/stdlib/string/string-context.h
runtime-common/stdlib/string/string-functions.cpp
runtime-light/state/instance-state.h

This pull request enhances the performance of the HelloWorld benchmark for K2 by a factor of 32. Previously, we used zero-initialized `std::array` as a buffer in `StringLibContext`. This zeroing of the 8MB array at the start of each request consumed significant CPU time. By switching to uninitialized `std::array`, we avoid unnecessary initialization, resulting in substantial performance improvements.
Following benchmark is enough to see the difference:
```
?php
echo "Hello, World!\n";
```

do not initialize StringLibContext's static buffers

---

builtin-functions/kphp-light/array.txt
builtin-functions/kphp-light/unsupported/arrays.txt
compiler/code-gen/vertex-compiler.cpp
runtime-light/stdlib/array/array-functions.h
tests/phpt/lambdas/018_typed_array_reduce.php
tests/phpt/lambdas/037_template_internal_functions_as_callbacks.php
tests/phpt/nn/002_array_reduce.php
tests/phpt/phc/parsing/impure.php

This PR:
- add `array_reduce` implementation for K2 runtime
- refined the way return types are declared for implicit lambdas used in asynchronous built-in callbacks

[k2] implement array_reduce

---

runtime-light/stdlib/string/regex-functions.cpp
runtime-light/stdlib/string/regex-functions.h
runtime-light/stdlib/string/regex-state.h

This pull request enhances the handling of the `matches` parameter by making it a `Optional`. This change improves the flexibility and safety of the code by explicitly representing the presence or absence of a `matches` parameter to fill.
Key changes:
- The matches variable is now a `Optional`, allowing it to explicitly indicate whether a match is present.
- The use of RegexInstanceState has been eliminated. Previously, it was used to default-initialize certain parameters with lvalue references. This refactoring enhances the overall performance of regex functions since the call to `RegexInstanceState::get()` leads to accessing a thread-local variable inside k2 platform.

[k2] do not set matches in regex functions unless it's necessary

---

common/server/statsd-client.cpp
common/server/statsd-client.h

Before, prefix for statsd metrics was taken from `--server-config` yaml file as `cluster_name`. But sometimes, it's needed to separate statsd metrics by prefix different from cluster-name.
Now there's `--statsd-prefix` for thar, which overrides old behaviour.

Add --statsd-prefix option

---

cmake/init-global-vars.cmake
third-party/timelib-cmake/timelib.cmake

Moving  presence check of `re2c` into `timelib.cmake`

make re2c is not required for whole project

---

runtime-light/stdlib/file/file-system-functions.cpp

Add warning when `fopen()` is not succeed and notice when succeed.

Better fopen() logs

---

runtime/interface.cpp
tests/python/tests/shutdown_functions/php/index.php
tests/python/tests/shutdown_functions/test_shutdown_functions_capture_shared_mem.py

A specific workload might lead to issues due to the incorrect order of resource release by workers. 
This PR fixes order of worker's cleanup operations.

fix order of worker's cleanup operations

---

server/server.cmake

Add `OpenSSL` as dependency for `server` for avoidance of such errors:
```
In file included from .././common/kfs/kfs-common.h:11,
from .././common/kfs/kfs.h:11,
from ../server/confdata-binlog-replay.cpp:22:
.././common/crypto/aes256.h:29:5: error: 'AES_KEY' does not name a type; did you mean 'AF_KEY'?
29 |     AES_KEY key;
|     ^~~~~~~
|     AF_KEY
```

fix dependecy graph of build

---

common/binlog/binlog.cmake
common/common.cmake
compiler/compiler.cmake
net/net.cmake
server/server.cmake

Fix issues like this:
```
make[2]: *** No rule to make target '../objs/include/openssl/aes.h', needed by 'CMakeFiles/binlog-src-no-pic.dir/common/binlog/kdb-binlog-common.cpp.o'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:591: CMakeFiles/binlog-src-no-pic.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs..
```

fix incorrect reference to OpenSSL headers

---

runtime-light/server/http/init-functions.cpp
runtime-light/server/job-worker/init-functions.h
runtime-light/state/init-functions.cpp
runtime-light/stdlib/crypto/crypto-functions.cpp
runtime-light/stdlib/job-worker/job-worker-api.cpp
runtime-light/tl/tl-core.h
runtime-light/tl/tl-functions.cpp
runtime-light/tl/tl-functions.h
runtime-light/tl/tl-types.cpp
runtime-light/tl/tl-types.h

1. add missing `tl::int, tl::long, tl::float, tl::double` types and name them `tl::i32, tl::i64, tl::f32, tl::f64` respectively
2. use them instead of raw types
3. add `tl::` prefix everywhere

[k2] enhance TL library

---

vkext/vkext-rpc-tl-serialization.cpp

Fixed a bug where `tlgen` and `tl2php` converted the `bool` type as `boolean` and left `vkext` as is
https://github.com/VKCOM/kphp/blob/51c36da95e307dcd030c0466d3e2be6060ffaa5f/common/tl2php/combinator-to-php.cpp#L90

fixed a bug with bool type mapping in vkext

---

.github/workflows/debian.yml
.github/workflows/ubuntu.yml

Now in the `GitHub Actions` logs you can see the following error: `PytestUnknownMarkWarning: Unknown pytest.mark.k2_skip_suite - is this a typo?  You can register custom mark`.
https://github.com/VKCOM/kphp/actions/runs/15002660263/job/42153394928#step:13:488
It's a bit annoying and misleading. To fix it, I changed the path to `python` tests where the `pytest.ini` file lies.
**IMPORTANT**: the paths in `TeamCity` and `GitHub Actions` are now the same.
P.S. I **don't like** this method of running tests. It should be done through some kind of script / `make` / `python` script. Not by directly calling the `python` interpreter.

fixed the path to python tests in CI

---

tests/python/lib/k2_server.py

Basically python tests may run concurrently on same machine. But the problem happens when one of the running `k2-node` tries to gracefully shutdown. The problem is in that all of the running node are reading same unix-socket for graceful shutdown.
The solution is to pass unique unix-socket path for each `k2-node` instance.

[k2] Fix concurrent launching k2-node in tests

---

builtin-functions/kphp-light/stdlib/time-functions.txt
compiler/make/objs-to-k2-component-target.h
runtime-light/allocator-wrapper/libc-alloc-wrapper.cpp
runtime-light/k2-platform/k2-api.h
runtime-light/runtime-light.cmake
runtime-light/runtime-light.cpp
runtime-light/state/image-state.h
runtime-light/state/instance-state.h
runtime-light/stdlib/stdlib.cmake
runtime-light/stdlib/time/time-functions.cpp
runtime-light/stdlib/time/time-functions.h
runtime-light/stdlib/time/time-state.cpp
runtime-light/stdlib/time/time-state.h
runtime-light/stdlib/time/timelib-constants.h
runtime-light/stdlib/time/timelib-functions.cpp
runtime-light/stdlib/time/timelib-functions.h
runtime-light/stdlib/time/timelib-timezone-cache.h
tests/phpt/dl/459_strtotime.php
tests/phpt/pk/025_strtotime_next_week_day.php

Implement `strtotime` function using `timelib` library. As `timelib` doesn't support customising a memory manager, we use `libc_alloc_guard` to allow it to call `malloc`, `free` etc. These symbols are overridden to call script allocator instead of the system one. Also, in this PR we override `strdup` function since it's also used by `timelib` internally.

[k2] implement strtotime

---

runtime-light/stdlib/time/timer-functions.h

This pull request addresses the incorrect use of `shared_task<>` in the `set_timer` function, replacing it with `task<>` as originally intended during prior refactorings

[k2] fix set_timer by using task<> to start a fork

---

runtime-light/utils/logs.h

Introduce `floating_wrapper` to automatically ensure consistent logging of floating-point numbers with a fixed decimal precision. This fixes an issue where `std::format` could use `malloc` to format floating point types.

[k2] custom format for floating points in logs

---

compiler/pipes/optimization.cpp

Imagine the following snippet:
```php
<?php
const PREDEFINED_WILDCARDS = [
'lol',
'kek',
];
const ALL = [
PREDEFINED_WILDCARDS,
[1, 2, 3],
];
warning((string)get_reference_counter(ALL[0]));
```
It's supposed to print `0x7ffffff0`, special counter value for global constants. But previously it printed `2`.
The reason is that `PREDEFINED_WILDCARDS` is and object of type `array<string>`, `ALL` is of type `array<array<mixed>>`, and during global constants initialization, `PREDEFINED_WILDCARDS` was conversed into `array<mixed>`, and counter was changed. For now, we create a copy global constant of `PREDEFINED_WILDCARDS` that is of type `array<mixed>` and behavior is expected now.

Fix global vars refcnt

---

server/database-drivers/adaptor.h
server/php-engine-vars.cpp
server/php-engine-vars.h
server/php-engine.cpp

This PR combines already existing behaviour of `--workers-num N` and `--once` options. To enable this mode one needs just specify both options on start.
New special mode works as the following:
1. Starts N workers, as usual in pre-fork mode from option `--workers-num N`
2. Sends dummy RPC request to itself to run script in each worker M times, as usual with `--once [M]` option (by default `M = 1`)
3. When script is finished as many times as specified, worker process terminates
4. When master process realizes that some workers are terminated it recreates them and execution in each new worker continues from step 2
The main goal of such a strange mode - to automatically enable subsystems designed only for master-workers model in **CLI** mode (confdata, instance cache, errors and traces …

Implement special pre-fork run once mode

---

common/binlog/binlog-buffer-aio.cpp
common/binlog/binlog-buffer-replay.cpp
common/binlog/binlog-buffer.cpp
common/binlog/binlog-buffer.h
common/binlog/binlog-stats.h
common/binlog/binlog.cmake
common/common.cmake
common/kfs/kfs.cpp
common/server/engine-settings.h
common/server/init-binlog.cpp
server/confdata-binlog-replay.cpp
server/confdata-binlog-replay.h
server/confdata-stats.h
server/php-engine.cpp
server/statshouse/statshouse-manager.cpp
server/statshouse/statshouse-manager.h

Goals of this PR:
* Prevent exiting if the next binlog is not available
* Wait for the new binlog to be delivered and send alerts after a specified delay

make confdata reader more reliable

---

runtime-light/allocator/runtime-light-allocator.cpp
runtime-light/coroutine/shared-task.h
runtime-light/coroutine/task.h
runtime-light/state/instance-state.h

Each invocation of `k2::alloc` triggers an update to the component statistics. To eliminate this overhead, replace `k2::alloc` with a script allocator. This change is acceptable as long as coroutines are not launched before the lifetime of `InstanceState`.

[k2] use script allocator instead of k2::alloc for coroutine frames

---

runtime/curl.cpp
server/php-queries.h
server/php-runner.cpp
server/statshouse/statshouse-manager.cpp

This PR introduces a new StatsHouse metric to monitor slow CURL responses in KPHP:
- Metric Name: kphp_slow_curl_responses
- Threshold: Records responses that exceed 100ms
- Data Captured:
- Request duration
- Target host/endpoint (if available)

add kphp_slow_curl_response metric

---

builtin-functions/kphp-light/stdlib/kphp-tracing.txt
builtin-functions/kphp-light/stdlib/rpc.txt
runtime-light/stdlib/fork/fork-functions.h
runtime-light/stdlib/tracing/tracing-div.h
runtime-light/stdlib/tracing/tracing-functions.h
runtime-light/stdlib/tracing/tracing-span.h

Change presence and behavior of some builtins in runtime-light:
* Remove `rpc_tl_query_one(), typed_rpc_tl_query_result_synchronously(), typed_rpc_tl_query_result_one(), new_rpc_connection() ` and `RpcConnection` stubs
* Make `wait_queue_create()` noop stub
* Add `kphp_tracing_get_level(), KphpDiv::assignTraceCtx(), KphpDiv::generateTraceCtxForChild()` and `KphpSpan::finishWithError` noop stubs
* Stop emiting a warning when calls other tracing builtins

[k2] Add some tracing, wait queue stubs and remove some rpc ones

---

compiler/pipes/final-check.cpp
tests/phpt/instance_cache/10_instance_cache_abstract_error.php
tests/phpt/instance_cache/11_instance_cache_polymprphic_field.php
tests/phpt/instance_cache/12_instance_cache_polymprphic_field_error.php
tests/phpt/instance_cache/1_instance_cache.php
tests/phpt/instance_cache/5_instance_cache_polymorphic_simple.php
tests/phpt/instance_cache/6_instance_cache_polymorphic_error.php
tests/phpt/instance_cache/7_instance_cache_interface.php
tests/phpt/instance_cache/8_instance_cache_interface_error.php
tests/phpt/instance_cache/9_instance_cache_abstract.php
tests/phpt/interfaces/Classes/AAA.php
tests/python/tests/instance_cache/php/index.php
tests/python/tests/instance_cache/test_polymorphic.py
tests/python/tests/instance_cache/test_store_fetch_delete.py
tests/python/tests/job_workers/php/SharedMemoryPieceCopying/SomeContext.php
tests/python/tests/job_workers/php/SyncJobCommand.php
tests/python/tests/shutdown_functions/php/index.php

The goal is to simplify migration to a light runtime (K2) in the future.
Restricted:
- instance_cache_fetch;
- instance_cache_store.
Relates to KPHP-2098

check is serializable for IC methods
